// priority: 0

/**
 * Список хранит предметы,
 * у которых должны быть удалены тэги и они должны быть скрыты в REI.
 */
global.MINECRAFT_DISABLED_ITEMS = [
    // Дерево
    // Дуб
    "minecraft:oak_wood",
    "minecraft:oak_leaves",
    "minecraft:oak_sapling",
    "minecraft:stripped_oak_wood",
    "minecraft:oak_log",
    "minecraft:stripped_oak_log",
    "minecraft:oak_planks",
    "minecraft:oak_stairs",
    "minecraft:oak_slab",
    "minecraft:petrified_oak_slab",
    "minecraft:oak_pressure_plate",
    "minecraft:oak_fence",
    "minecraft:oak_fence_gate",
    "minecraft:oak_door",
    "minecraft:oak_trapdoor",
    "minecraft:oak_boat",
    "minecraft:oak_chest_boat",
    "minecraft:oak_sign",
    "minecraft:oak_hanging_sign",
    "minecraft:oak_button",

    // Темный дуб
    "minecraft:dark_oak_planks",
    "minecraft:dark_oak_sapling",
    "minecraft:dark_oak_log",
    "minecraft:stripped_dark_oak_log",
    "minecraft:stripped_dark_oak_wood",
    "minecraft:dark_oak_wood",
    "minecraft:dark_oak_leaves",
    "minecraft:dark_oak_slab",
    "minecraft:dark_oak_fence",
    "minecraft:dark_oak_stairs",
    "minecraft:dark_oak_button",
    "minecraft:dark_oak_pressure_plate",
    "minecraft:dark_oak_door",
    "minecraft:dark_oak_trapdoor",
    "minecraft:dark_oak_fence_gate",
    "minecraft:dark_oak_boat",
    "minecraft:dark_oak_chest_boat",
    "minecraft:dark_oak_sign",
    "minecraft:dark_oak_hanging_sign",

    // Acacia
    "minecraft:acacia_planks",
    "minecraft:acacia_sapling",
    "minecraft:acacia_log",
    "minecraft:stripped_acacia_log",
    "minecraft:stripped_acacia_wood",
    "minecraft:acacia_wood",
    "minecraft:acacia_leaves",
    "minecraft:acacia_slab",
    "minecraft:acacia_fence",
    "minecraft:acacia_stairs",
    "minecraft:acacia_button",
    "minecraft:acacia_pressure_plate",
    "minecraft:acacia_door",
    "minecraft:acacia_trapdoor",
    "minecraft:acacia_fence_gate",
    "minecraft:acacia_boat",
    "minecraft:acacia_chest_boat",
    "minecraft:acacia_sign",
    "minecraft:acacia_hanging_sign",

    // Birch
    "minecraft:birch_planks",
    "minecraft:birch_sapling",
    "minecraft:birch_log",
    "minecraft:stripped_birch_log",
    "minecraft:stripped_birch_wood",
    "minecraft:birch_wood",
    "minecraft:birch_leaves",
    "minecraft:birch_slab",
    "minecraft:birch_fence",
    "minecraft:birch_stairs",
    "minecraft:birch_button",
    "minecraft:birch_pressure_plate",
    "minecraft:birch_door",
    "minecraft:birch_trapdoor",
    "minecraft:birch_fence_gate",
    "minecraft:birch_boat",
    "minecraft:birch_chest_boat",
    "minecraft:birch_sign",
    "minecraft:birch_hanging_sign",

    // Jungle
    "minecraft:jungle_planks",
    "minecraft:jungle_sapling",
    "minecraft:jungle_log",
    "minecraft:stripped_jungle_log",
    "minecraft:stripped_jungle_wood",
    "minecraft:jungle_wood",
    "minecraft:jungle_leaves",
    "minecraft:jungle_slab",
    "minecraft:jungle_fence",
    "minecraft:jungle_stairs",
    "minecraft:jungle_button",
    "minecraft:jungle_pressure_plate",
    "minecraft:jungle_door",
    "minecraft:jungle_trapdoor",
    "minecraft:jungle_fence_gate",
    "minecraft:jungle_boat",
    "minecraft:jungle_chest_boat",
    "minecraft:jungle_sign",
    "minecraft:jungle_hanging_sign",

    // Spruce
    "minecraft:spruce_planks",
    "minecraft:spruce_sapling",
    "minecraft:spruce_log",
    "minecraft:stripped_spruce_log",
    "minecraft:stripped_spruce_wood",
    "minecraft:spruce_wood",
    "minecraft:spruce_leaves",
    "minecraft:spruce_slab",
    "minecraft:spruce_fence",
    "minecraft:spruce_stairs",
    "minecraft:spruce_button",
    "minecraft:spruce_pressure_plate",
    "minecraft:spruce_door",
    "minecraft:spruce_trapdoor",
    "minecraft:spruce_fence_gate",
    "minecraft:spruce_boat",
    "minecraft:spruce_chest_boat",
    "minecraft:spruce_sign",
    "minecraft:spruce_hanging_sign",

    // Cherry
    "minecraft:cherry_planks",
    "minecraft:cherry_sapling",
    "minecraft:cherry_log",
    "minecraft:stripped_cherry_log",
    "minecraft:stripped_cherry_wood",
    "minecraft:cherry_wood",
    "minecraft:cherry_leaves",
    "minecraft:cherry_slab",
    "minecraft:cherry_fence",
    "minecraft:cherry_stairs",
    "minecraft:cherry_button",
    "minecraft:cherry_pressure_plate",
    "minecraft:cherry_door",
    "minecraft:cherry_trapdoor",
    "minecraft:cherry_fence_gate",
    "minecraft:cherry_boat",
    "minecraft:cherry_chest_boat",
    "minecraft:cherry_sign",
    "minecraft:cherry_hanging_sign",

    // Mangrove
    "minecraft:mangrove_planks",
    "minecraft:mangrove_propagule",
    "minecraft:mangrove_log",
    "minecraft:mangrove_roots",
    "minecraft:muddy_mangrove_roots",
    "minecraft:stripped_mangrove_log",
    "minecraft:stripped_mangrove_wood",
    "minecraft:mangrove_wood",
    "minecraft:mangrove_leaves",
    "minecraft:mangrove_slab",
    "minecraft:mangrove_fence",
    "minecraft:mangrove_stairs",
    "minecraft:mangrove_button",
    "minecraft:mangrove_pressure_plate",
    "minecraft:mangrove_door",
    "minecraft:mangrove_trapdoor",
    "minecraft:mangrove_fence_gate",
    "minecraft:mangrove_boat",
    "minecraft:mangrove_chest_boat",
    "minecraft:mangrove_sign",
    "minecraft:mangrove_hanging_sign",

    // Other
    "minecraft:bookshelf",
    "minecraft:chiseled_bookshelf",
    "minecraft:sand",
    "minecraft:suspicious_sand",
    "minecraft:red_sand",
    "minecraft:chest",
    "minecraft:trapped_chest",

    "minecraft:wheat",
    "minecraft:composter",
    "minecraft:barrel",
    "minecraft:blast_furnace",
    "minecraft:furnace",
    "minecraft:furnace_minecart",

    "minecraft:anvil",
    "minecraft:chipped_anvil",
    "minecraft:damaged_anvil",
    "minecraft:torch",
    "minecraft:lantern",
    "minecraft:soul_torch",
    "minecraft:soul_lantern",

    // Seeds
    "minecraft:wheat_seeds",
    "minecraft:pumpkin_seeds",
    "minecraft:melon_seeds",
    "minecraft:torchflower_seeds",
    "minecraft:beetroot_seeds",
    
    // Fish
    "minecraft:cod",
    "minecraft:salmon",
    "minecraft:tropical_fish",
    "minecraft:pufferfish",
    "minecraft:cooked_cod",
    "minecraft:cooked_salmon",

    // Ores
    "minecraft:netherite_scrap",
    "minecraft:netherite_ingot",
    "minecraft:netherite_block",
    "minecraft:smithing_table",
    "minecraft:netherite_block",
    "minecraft:coal_ore",
    "minecraft:deepslate_coal_ore",
    "minecraft:iron_ore",
    "minecraft:deepslate_iron_ore",
    "minecraft:copper_ore",
    "minecraft:deepslate_copper_ore",
    "minecraft:gold_ore",
    "minecraft:deepslate_gold_ore",
    "minecraft:redstone_ore",
    "minecraft:deepslate_redstone_ore",
    "minecraft:emerald_ore",
    "minecraft:deepslate_emerald_ore",
    "minecraft:lapis_ore",
    "minecraft:deepslate_lapis_ore",
    "minecraft:diamond_ore",
    "minecraft:deepslate_diamond_ore",
    "minecraft:nether_gold_ore",
    "minecraft:nether_quartz_ore",
    "minecraft:ancient_debris",

    // Tools
    "minecraft:wooden_sword",
    "minecraft:wooden_pickaxe",
    "minecraft:wooden_axe",
    "minecraft:wooden_shovel",
    "minecraft:wooden_hoe",

    "minecraft:stone_sword",
    "minecraft:stone_pickaxe",
    "minecraft:stone_axe",
    "minecraft:stone_shovel",
    "minecraft:stone_hoe",

    "minecraft:iron_sword",
    "minecraft:iron_pickaxe",
    "minecraft:iron_axe",
    "minecraft:iron_shovel",
    "minecraft:iron_hoe",

    "minecraft:golden_sword",
    "minecraft:golden_pickaxe",
    "minecraft:golden_axe",
    "minecraft:golden_shovel",
    "minecraft:golden_hoe",

    "minecraft:diamond_sword",
    "minecraft:diamond_pickaxe",
    "minecraft:diamond_axe",
    "minecraft:diamond_shovel",
    "minecraft:diamond_hoe",

    "minecraft:netherite_sword",
    "minecraft:netherite_pickaxe",
    "minecraft:netherite_axe",
    "minecraft:netherite_shovel",
    "minecraft:netherite_hoe",

    // Armor
    // Horse
    "minecraft:iron_horse_armor",
    "minecraft:golden_horse_armor",
    "minecraft:diamond_horse_armor",
    // Player
    "minecraft:netherite_helmet",
    "minecraft:netherite_chestplate",
    "minecraft:netherite_leggings",
    "minecraft:netherite_boots",
    "minecraft:golden_helmet",
    "minecraft:golden_chestplate",
    "minecraft:golden_leggings",
    "minecraft:golden_boots",
    "minecraft:iron_helmet",
    "minecraft:iron_chestplate",
    "minecraft:iron_leggings",
    "minecraft:iron_boots",
    "minecraft:chainmail_helmet",
    "minecraft:chainmail_chestplate",
    "minecraft:chainmail_leggings",
    "minecraft:chainmail_boots",
    "minecraft:diamond_helmet",
    "minecraft:diamond_chestplate",
    "minecraft:diamond_leggings",
    "minecraft:diamond_boots",
];

global.VANILLA_WOOD_TYPES = [
    "oak",
    "spruce",
    "birch",
    "jungle",
    "acacia",
    "cherry",
    "dark_oak",
    "mangrove",
    "bamboo",
];

global.VANILLA_STONE_TYPES = [
    "sand",
    "red_sand",
    "gravel",
    "ore",
    "deepslate",
    "basalt",
    "endstone",
    "netherrack",
    "andesite",
    "diorite",
    "granite",
    "tuff",
];
