// priority: 0

const defaultProperty = [
    "ingot"
]

const nuggetProperty = [
    "nugget"
]

const dustProperty = [
    "dust",
    "dust_small",
    "dust_tiny",
]

const oreProperty = [
    "poor_raw",
    "normal_raw",
    "rich_raw"
]

const doubleIngotProperty = [
    "double_ingot"
]

const partProperty = [
    "sheet",
    "double_sheet",
    "rod",
    "block",
    "block_stairs",
    "block_slab"
]

const armorProperty = [
    "boots",
    "greaves",
    "chestplate",
    "helmet",
    "shield",
    "unfinished_boots",
    "unfinished_chestplate",
    "unfinished_greaves",
    "unfinished_helmet",
]

const toolProperty = [
    "axe_head",
    "axe",
    "chisel_head",
    "chisel",
    "hoe_head",
    "fish_hook",
    "fishing_rod",
    "hammer_head",
    "hammer",
    "hoe",
    "hoe_head",
    "horse_armor",
    "javelin_head",
    "javelin",
    "knife_blade",
    "knife",
    "mace_head",
    "mace",
    "pickaxe_head",
    "pickaxe",
    "propick_head",
    "propick",
    "saw_blade",
    "saw",
    "scythe_blade",
    "scythe",
    "shears",
    "shovel_head",
    "shovel",
    "sword_blade",
    "sword",
    "tuyere"
]

const utilityProperty = [
    "anvil",
    "bars",
    "chain",
    "lamp",
    "trapdoor",
    "unfinished_lamp"
]

const ItemHeats = {
    "nugget": { heat_capacity: 0.124, metal_amount: { 
        "bismuth": 16,
        "cassiterite": 16,
        "copper": 16,
        "garnierite": 14,
        "gold": 16,
        "hematite": 13,
        "iron": 16,
        "yellow_limonite": 14,
        "magnetite": 14,
        "malachite": 13,
        "nickel": 16,
        "pyrite": 12,
        "silver": 16,
        "sphalerite": 16,
        "tetrahedrite": 14,
        "tin": 16,
    }, input: (name) => { return { tag: `forge:nuggets/${name}` } }, output: (name) => { return { item: `gtceu:${name}_nugget` } }  },
    
    "dust": { heat_capacity: 1.429, metal_amount: { 
        "bismuth": 144,
        "cassiterite": 144,
        "copper": 144,
        "garnierite": 126,
        "gold": 144,
        "hematite": 117,
        "iron": 144,
        "yellow_limonite": 126,
        "magnetite": 126,
        "malachite": 117,
        "nickel": 144,
        "pyrite": 123,
        "silver": 144,
        "sphalerite": 144,
        "tetrahedrite": 126,
        "tin": 144,
    }, input: (name) => { return { tag: `forge:dusts/${name}` } }, output: (name) => { return { item: `gtceu:${name}_dust` } } },
    
    
    "dust_small": { heat_capacity: 0.714, metal_amount: { 
        "bismuth": 36,
        "cassiterite": 36,
        "copper": 36,
        "garnierite": 31,
        "gold": 36,
        "hematite": 29,
        "iron": 36,
        "yellow_limonite": 31,
        "magnetite": 31,
        "malachite": 29,
        "nickel": 36,
        "pyrite": 27,
        "silver": 36,
        "sphalerite": 36,
        "tetrahedrite": 31,
        "tin": 36,
    }, input: (name) => { return { tag: `forge:dusts/small/${name}` } }, output: (name) => { return { item: `gtceu:${name}_dust_small` } }  },
    
    
    "dust_tiny": { heat_capacity: 0.357, metal_amount: { 
        "bismuth": 16,
        "cassiterite": 16,
        "copper": 16,
        "garnierite": 14,
        "gold": 16,
        "hematite": 13,
        "iron": 16,
        "yellow_limonite": 14,
        "magnetite": 14,
        "malachite": 13,
        "nickel": 16,
        "pyrite": 12,
        "silver": 16,
        "sphalerite": 16,
        "tetrahedrite": 14,
        "tin": 16,
    }, input: (name) => { return { tag: `forge:dusts/tiny/${name}` } }, output: (name) => { return { item: `gtceu:${name}_dust_tiny` } } },
    
    
    "poor_raw": { heat_capacity: 1.429, metal_amount: { 
        "bismuth": 24,
        "cassiterite": 24,
        "copper": 24,
        "garnierite": 21,
        "gold": 24,
        "hematite": 18,
        "iron": 24,
        "yellow_limonite": 21,
        "magnetite": 21,
        "malachite": 18,
        "nickel": 24,
        "pyrite": 18,
        "silver": 24,
        "sphalerite": 24,
        "tetrahedrite": 21,
        "tin": 24,
    }, input: (name) => { return { tag: `forge:poor_raw_materials/${name}` } }, output: (name) => { return { item: `gtceu:poor_raw_${name}` } } },
    
    
    "normal_raw": { heat_capacity: 1.429, metal_amount: { 
        "bismuth": 36,
        "cassiterite": 36,
        "copper": 36,
        "garnierite": 31,
        "gold": 36,
        "hematite": 29,
        "iron": 36,
        "yellow_limonite": 31,
        "magnetite": 31,
        "malachite": 29,
        "nickel": 36,
        "pyrite": 27,
        "silver": 36,
        "sphalerite": 36,
        "tetrahedrite": 31,
        "tin": 36,
    }, input: (name) => { return { tag: `forge:raw_materials/${name}` } }, output: (name) => { return { item: `gtceu:raw_${name}` } } },
    
    
    "rich_raw": { heat_capacity: 1.429, metal_amount: { 
        "bismuth": 48,
        "cassiterite": 48,
        "copper": 48,
        "garnierite": 42,
        "gold": 48,
        "hematite": 39,
        "iron": 48,
        "yellow_limonite": 42,
        "magnetite": 42,
        "malachite": 39,
        "nickel": 48,
        "pyrite": 36,
        "silver": 48,
        "sphalerite": 48,
        "tetrahedrite": 42,
        "tin": 48,
    }, input: (name) => { return { tag: `forge:rich_raw_materials/${name}` } }, output: (name) => { return { item: `gtceu:rich_raw_${name}` } } },
    
    "block_slab": { heat_capacity: null }, // can't melt
    "block_stairs": { heat_capacity: null }, // can't melt
    
    "block": { heat_capacity: 2.857, metal_amount: 1296, 
        input: (name) => { return { tag: `forge:storage_blocks/${name}` } }, 
        output: (name) => { return { item: `gtceu:${name}_block` } } },
    "anvil": { heat_capacity: 40.0, metal_amount: 2016, 
        input: (name) => { return { item: `tfc:metal/anvil/${name}` } }, 
        output: (name) => { return { item: `tfc:metal/anvil/${name}` } } },
    "chain": { heat_capacity: 0.171, metal_amount: 9, 
        input: (name) => { return { item: `tfc:metal/chain/${name}` } }, 
        output: (name) => { return { item: `tfc:metal/chain/${name}` } } },
    "bars": { heat_capacity: 0.714, metal_amount: 36, 
        input: (name) => { return { item: `tfc:metal/bars/${name}` } }, 
        output: (name) => { return { item: `tfc:metal/bars/${name}` } } },
    "trapdoor": { heat_capacity: 5.714, metal_amount: 288, 
        input: (name) => { return { item: `tfc:metal/trapdoor/${name}` } }, 
        output: (name) => { return { item: `tfc:metal/trapdoor/${name}` } } },
    "lamp": { heat_capacity: 2.857, metal_amount: 144, 
        input: (name) => { return { item: `tfc:metal/lamp/${name}` } }, 
        output: (name) => { return { item: `tfc:metal/lamp/${name}` } } },
    "unfinished_lamp": { heat_capacity: 2.857, metal_amount: 144, 
        input: (name) => { return { item: `tfc:metal/unfinished_lamp/${name}` } }, 
        output: (name) => { return { item: `tfc:metal/unfinished_lamp/${name}` } } },
    
    "helmet": { heat_capacity: 17.143, metal_amount: 864, 
        input: (name) => { return { item: `tfc:metal/helmet/${name}` } }, 
        output: (name) => { return { item: `tfc:metal/helmet/${name}` } } },
    "chestplate": { heat_capacity: 22.857, metal_amount: 1152, 
        input: (name) => { return { item: `tfc:metal/chestplate/${name}` }}, 
        output: (name) => { return { item: `tfc:metal/chestplate/${name}` } } },
    "greaves": { heat_capacity: 17.143, metal_amount: 864, 
        input: (name) => { return { item: `tfc:metal/greaves/${name}` } }, 
        output: (name) => { return { item: `tfc:metal/greaves/${name}` } } },
    "boots": { heat_capacity: 11.429, metal_amount: 576, 
        input: (name) => { return { item: `tfc:metal/boots/${name}` } }, 
        output: (name) => { return { item: `tfc:metal/boots/${name}` } } },
    "unfinished_boots": { heat_capacity: 5.714, metal_amount: 288, 
        input: (name) => { return { item: `tfc:metal/unfinished_boots/${name}` } }, 
        output: (name) => { return { item: `tfc:metal/unfinished_boots/${name}` } } },
    "unfinished_chestplate": { heat_capacity: 11.429, metal_amount: 576, 
        input: (name) => { return { item: `tfc:metal/unfinished_chestplate/${name}` } }, 
        output: (name) => { return { item: `tfc:metal/unfinished_chestplate/${name}` } } },
    "unfinished_greaves": { heat_capacity: 11.429, metal_amount: 576, 
        input: (name) => { return { item: `tfc:metal/unfinished_greaves/${name}` } }, 
        output: (name) => { return { item: `tfc:metal/unfinished_greaves/${name}` } } },
    "unfinished_helmet": { heat_capacity: 11.429, metal_amount: 576, 
        input: (name) => { return { item: `tfc:metal/unfinished_helmet/${name}` } }, 
        output: (name) => { return { item: `tfc:metal/unfinished_helmet/${name}` } } },
    
    "horse_armor": { heat_capacity: 34.286, metal_amount: 1728, 
        input: (name) => { return { item: `tfc:metal/horse_armor/${name}` } }, 
        output: (name) => { return { item: `tfc:metal/horse_armor/${name}` } } },

    "sword_blade": { heat_capacity: 5.714, metal_amount: 288, 
        input: (name) => { return { tag: `forge:sword_heads/${name}` } }, 
        output: (name) => { return { item: `gtceu:${name}_sword_head` } } },
    "sword": { heat_capacity: 5.714, metal_amount: 288, 
        input: (name) => { return { item: `gtceu:${name}_sword` } }, 
        output: (name) => { return { item: `gtceu:${name}_sword` } } },
    "pickaxe_head": { heat_capacity: 2.857, metal_amount: 144, 
        input: (name) => { return { tag: `forge:pickaxe_heads/${name}` } }, 
        output: (name) => { return { tag: `forge:pickaxe_heads/${name}` } }  },
    "pickaxe": { heat_capacity: 2.857, metal_amount: 144, 
        input: (name) => { return { item: `gtceu:${name}_pickaxe` } }, 
        output: (name) => { return { item: `gtceu:${name}_pickaxe` } } },
    "axe_head": { heat_capacity: 2.857, metal_amount: 144, 
        input: (name) => { return { tag: `forge:axe_heads/${name}` } }, 
        output: (name) => { return { item: `gtceu:${name}_axe_head` } } },
    "axe": { heat_capacity: 2.857, metal_amount: 144, 
        input: (name) => { return { item: `gtceu:${name}_axe` } }, 
        output: (name) => { return { item: `gtceu:${name}_axe` } } },
    "shovel_head": { heat_capacity: 2.857, metal_amount: 144, 
        input: (name) => { return { tag: `forge:shovel_heads/${name}` } }, 
        output: (name) => { return { item: `gtceu:${name}_shovel_head` } } },
    "shovel": { heat_capacity: 2.857, metal_amount: 144, 
        input: (name) => { return { item: `gtceu:${name}_shovel` } }, 
        output: (name) => { return { item: `gtceu:${name}_shovel` } } },
    "hammer_head": { heat_capacity: 2.857, metal_amount: 144, 
        input: (name) => { return { tag: `forge:hammer_heads/${name}` } }, 
        output: (name) => { return { item: `gtceu:${name}_hammer_head` } } },
    "hammer": { heat_capacity: 2.857, metal_amount: 144, 
        input: (name) => { return { item: `gtceu:${name}_hammer` } }, 
        output: (name) => { return { item: `gtceu:${name}_hammer` } } },
    "hoe_head": { heat_capacity: 2.857, metal_amount: 144, 
        input: (name) => { return { tag: `forge:hoe_heads/${name}` } }, 
        output: (name) => { return { item: `gtceu:${name}_hoe_head` } } },
    "hoe": { heat_capacity: 2.857, metal_amount: 144, 
        input: (name) => { return { item: `gtceu:${name}_hoe` } }, 
        output: (name) => { return { item: `gtceu:${name}_hoe` } } },
    "knife_blade": { heat_capacity: 2.857, metal_amount: 144, 
        input: (name) => { return { tag: `forge:knife_heads/${name}` } }, 
        output: (name) => { return { item: `gtceu:${name}_knife_head` } } },
    "knife": { heat_capacity: 2.857, metal_amount: 144, 
        input: (name) => { return { item: `gtceu:${name}_knife` } },
        output: (name) => { return { item: `gtceu:${name}_knife` } } },
    "saw_blade": { heat_capacity: 2.857, metal_amount: 144, 
        input: (name) => { return { tag: `forge:saw_heads/${name}` } }, 
        output: (name) => { return { item: `gtceu:${name}_saw_head` } } },
    "saw": { heat_capacity: 2.857, metal_amount: 144, 
        input: (name) => { return { item: `gtceu:${name}_saw` } }, 
        output: (name) => { return { item: `gtceu:${name}_saw` } } },
    "scythe_blade": { heat_capacity: 2.857, metal_amount: 144, 
        input: (name) => { return { tag: `forge:scythe_heads/${name}` } }, 
        output: (name) => { return { item: `gtceu:${name}_scythe_head` } } },
    "scythe": { heat_capacity: 2.857, metal_amount: 144, 
        input: (name) => { return { item: `gtceu:${name}_scythe` } }, 
        output: (name) => { return { item: `gtceu:${name}_scythe` } } },
    "chisel_head": { heat_capacity: 2.857, metal_amount: 144, 
        input: (name) => { return { item: `tfc:metal/chisel_head/${name}` } }, 
        output: (name) => { return { item: `tfc:metal/chisel_head/${name}` } }, },
    "chisel": { heat_capacity: 2.857, metal_amount: 144, 
        input: (name) => { return { item: `tfc:metal/chisel/${name}` } }, 
        output: (name) => { return { item: `tfc:metal/chisel/${name}` } } },
    "javelin_head": { heat_capacity: 2.857, metal_amount: 144, 
        input: (name) => { return  { item: `tfc:metal/javelin_head/${name}` } }, 
        output: (name) => { return { item: `tfc:metal/javelin_head/${name}` } } },
    "javelin": { heat_capacity: 2.857, metal_amount: 144, 
        input: (name) => { return { item: `tfc:metal/javelin/${name}` } }, 
        output: (name) => { return { item: `tfc:metal/javelin/${name}` } } },
    "propick_head": { heat_capacity:  2.857, metal_amount: 144, 
        input: (name) => { return { item: `tfc:metal/propick_head/${name}` } }, 
        output: (name) => { return { item: `tfc:metal/propick_head/${name}` } } },
    "propick": { heat_capacity: 2.857, metal_amount: 144, 
        input: (name) => { return { item: `tfc:metal/propick/${name}` } }, 
        output: (name) => { return { item: `tfc:metal/propick/${name}` } } },
    "mace_head": { heat_capacity: 5.714, metal_amount: 288, 
        input: (name) => { return { item: `tfc:metal/mace_head/${name}` } }, 
        output: (name) => { return { item: `tfc:metal/mace_head/${name}` } } },
    "mace": { heat_capacity: 5.714, metal_amount: 288, 
        input: (name) => { return { item: `tfc:metal/mace/${name}` } }, 
        output: (name) => { return { item: `tfc:metal/mace/${name}` } } },
    "fish_hook": { heat_capacity: 5.714, metal_amount: 288, 
        input: (name) => { return { item: `tfc:metal/fish_hook/${name}` } }, 
        output: (name) => { return { item: `tfc:metal/fish_hook/${name}` } } },
    "fishing_rod": { heat_capacity: 5.714, metal_amount: 288, 
        input: (name) => { return { item: `tfc:metal/fishing_rod/${name}` } }, 
        output: (name) => { return { item: `tfc:metal/fishing_rod/${name}` } } },
    "tuyere": { heat_capacity: 11.429, metal_amount: 576, 
        input: (name) => { return { item: `tfc:metal/tuyere/${name}` } }, 
        output: (name) => { return { item: `tfc:metal/tuyere/${name}` } } },
    "shears": { heat_capacity: 5.714, metal_amount: 288, 
        input: (name) => { return { item: `tfc:metal/shears/${name}` } }, 
        output: (name) => { return { item: `tfc:metal/shears/${name}` } } },
    "shield": { heat_capacity: 11.429, metal_amount: 576, 
        input: (name) => { return { item: `tfc:metal/shield/${name}` } }, 
        output: (name) => { return { item: `tfc:metal/shield/${name}` } } },

    "ingot": { heat_capacity: 2.857, metal_amount: 144, 
        input: (name) => { return { tag: `forge:ingots/${name}` } }, 
        output: (name) => { return { item: Item.getId(ChemicalHelper.get(TagPrefix.ingot, GTMaterials.get(name), 1)) } } },
    "double_ingot": { heat_capacity: 5.714, metal_amount: 288, 
        input: (name) => { return { item: `tfc:metal/double_ingot/${name}` } }, 
        output: (name) => { return { item: `tfc:metal/double_ingot/${name}` } } },
    "sheet": { heat_capacity: 5.714, metal_amount: 288, 
        input: (name) => { return { tag: `forge:plates/${name}` } }, 
        output: (name) => { return { item: `gtceu:${name}_plate` } } },
    "double_sheet": { heat_capacity: 11.429, metal_amount: 576, 
        input: (name) => { return { tag: `forge:plates/double/${name}` } }, 
        output: (name) => { return { item: `gtceu:${name}_double_plate` } } },
    "rod": { heat_capacity: 1.429, metal_amount: 72, 
        input: (name) => { return { tag: `forge:rods/${name}` } }, 
        output: (name) => { return { item: `gtceu:${name}_rod` } } },
}

const Metals = {
    "bismuth": { forging_temp: 162, welding_temp: 216, melt_temp: 270, fluidName: "gtceu:bismuth", props: [].concat(defaultProperty, partProperty, doubleIngotProperty, oreProperty, dustProperty, nuggetProperty) },
    "brass": { forging_temp: 558, welding_temp: 744, melt_temp: 930, fluidName: "gtceu:brass", props: [].concat(defaultProperty, partProperty, doubleIngotProperty, dustProperty, nuggetProperty) },
    "gold": { forging_temp: 636, welding_temp: 848, melt_temp: 1060, fluidName: "gtceu:gold", props: [].concat(defaultProperty, partProperty, doubleIngotProperty, oreProperty, dustProperty, nuggetProperty) },
    "nickel": { forging_temp: 872, welding_temp: 1162, melt_temp: 1453, fluidName: "gtceu:nickel", props: [].concat(defaultProperty, partProperty, doubleIngotProperty, oreProperty, dustProperty, nuggetProperty) },
    "rose_gold": { forging_temp: 576, welding_temp: 768, melt_temp: 960, fluidName: "gtceu:rose_gold", props: [].concat(defaultProperty, partProperty, doubleIngotProperty, dustProperty, nuggetProperty) },
    "silver": { forging_temp: 577, welding_temp: 769, melt_temp: 961, fluidName: "gtceu:silver", props: [].concat(defaultProperty, partProperty, doubleIngotProperty, oreProperty, dustProperty, nuggetProperty) },
    "tin": { forging_temp: 138, welding_temp: 184, melt_temp: 230, fluidName: "gtceu:tin", props: [].concat(defaultProperty, partProperty, doubleIngotProperty, oreProperty, dustProperty, nuggetProperty) },
    "zinc": { forging_temp: 252, welding_temp: 336, melt_temp: 420, fluidName: "gtceu:zinc", props: [].concat(defaultProperty, partProperty, doubleIngotProperty, dustProperty, nuggetProperty) },
    "sterling_silver": { forging_temp: 570, welding_temp: 760, melt_temp: 950, fluidName: "gtceu:sterling_silver", props: [].concat(defaultProperty, partProperty, doubleIngotProperty, dustProperty, nuggetProperty) },
    "copper": { forging_temp: 648, welding_temp: 864, melt_temp: 1080, fluidName: "gtceu:copper", props: [].concat(defaultProperty, partProperty, doubleIngotProperty, armorProperty, toolProperty, utilityProperty, oreProperty, dustProperty, nuggetProperty) },
    "bismuth_bronze": { forging_temp: 591, welding_temp: 788, melt_temp: 985, fluidName: "gtceu:bismuth_bronze", props: [].concat(defaultProperty, partProperty, doubleIngotProperty, armorProperty, toolProperty, utilityProperty, dustProperty, nuggetProperty) },
    "bronze": { forging_temp: 570, welding_temp: 760, melt_temp: 950, fluidName: "gtceu:bronze", props: [].concat(defaultProperty, partProperty, doubleIngotProperty, armorProperty, toolProperty, utilityProperty, dustProperty, nuggetProperty) },
    "black_bronze": { forging_temp: 642, welding_temp: 856, melt_temp: 1070, fluidName: "gtceu:black_bronze", props: [].concat(defaultProperty, partProperty, doubleIngotProperty, armorProperty, toolProperty, utilityProperty, dustProperty, nuggetProperty) },
    "wrought_iron": { forging_temp: 921, welding_temp: 1228, melt_temp: 1535, fluidName: "gtceu:wrought_iron", props: [].concat(defaultProperty, partProperty, doubleIngotProperty, armorProperty, toolProperty, utilityProperty, dustProperty, nuggetProperty) },
    "iron": { forging_temp: 921, welding_temp: 1228, melt_temp: 1535, fluidName: "gtceu:iron", props: [].concat(defaultProperty, partProperty, oreProperty, dustProperty) },
    "cast_iron": { forging_temp: 921, welding_temp: 1228, melt_temp: 1535, fluidName: "gtceu:iron", props: [].concat(doubleIngotProperty) },
    "pig_iron": { forging_temp: 921, welding_temp: 1228, melt_temp: 1535, fluidName: "tfc:metal/pig_iron", props: defaultProperty},
    "steel": { forging_temp: 924, welding_temp: 1232, melt_temp: 1540, fluidName: "gtceu:steel", props: [].concat(defaultProperty, partProperty, doubleIngotProperty, armorProperty, toolProperty, utilityProperty, dustProperty, nuggetProperty) },
    "high_carbon_black_steel": { forging_temp: 924, melt_temp: 1540, welding_temp: 1232, fluidName: "tfc:metal/high_carbon_black_steel", props: defaultProperty },
    "high_carbon_red_steel": { forging_temp: 924, melt_temp: 1540, welding_temp: 1232, fluidName: "tfc:metal/high_carbon_red_steel", props: defaultProperty },
    "high_carbon_blue_steel": { forging_temp: 924, melt_temp: 1540, welding_temp: 1232, fluidName: "tfc:metal/high_carbon_blue_steel", props: defaultProperty },
    "weak_steel": {  forging_temp: 924, welding_temp: 1232, melt_temp: 1540, fluidName: "tfc:metal/weak_steel", props: defaultProperty },
    "weak_red_steel": { forging_temp: 924, welding_temp: 1232, melt_temp: 1540, fluidName: "tfc:metal/weak_red_steel", props: defaultProperty },
    "weak_blue_steel": { forging_temp: 924, welding_temp: 1232, melt_temp: 1540, fluidName: "tfc:metal/weak_blue_steel", props: defaultProperty },
    "black_steel": { forging_temp: 891, welding_temp: 1188, melt_temp: 1485, fluidName: "gtceu:black_steel", props: [].concat(defaultProperty, partProperty, doubleIngotProperty, armorProperty, toolProperty, utilityProperty, dustProperty, nuggetProperty) },
    "red_steel": { forging_temp: 924, welding_temp: 1232, melt_temp: 1540, fluidName: "gtceu:red_steel", props: [].concat(defaultProperty, partProperty, doubleIngotProperty, armorProperty, toolProperty, utilityProperty, dustProperty, nuggetProperty) },
    "blue_steel": { forging_temp: 924, welding_temp: 1232, melt_temp: 1540, fluidName: "gtceu:blue_steel", props: [].concat(defaultProperty, partProperty, doubleIngotProperty, armorProperty, toolProperty, utilityProperty, dustProperty, nuggetProperty) },
    "unknown": { forging_temp: 240, welding_temp: 320, melt_temp: 400, fluidName: "tfc:metal/unknown", props: defaultProperty },
    "cassiterite": { forging_temp: 138, welding_temp: 184, melt_temp: 230, fluidName: "gtceu:zinc", props: [].concat(oreProperty, dustProperty) },
    "garnierite": { forging_temp: 138, welding_temp: 184, melt_temp: 1453, fluidName: "gtceu:nickel", props: [].concat(oreProperty, dustProperty) },
    "hematite": { forging_temp: 138, welding_temp: 184, melt_temp: 1535, fluidName: "gtceu:iron", props: [].concat(oreProperty, dustProperty) },
    "yellow_limonite": { forging_temp: 138, welding_temp: 184, melt_temp: 1535, fluidName: "gtceu:iron", props: [].concat(oreProperty, dustProperty) },
    "magnetite": { forging_temp: 138, welding_temp: 184, melt_temp: 1535, fluidName: "gtceu:iron", props: [].concat(oreProperty, dustProperty) },
    "malachite": { forging_temp: 138, welding_temp: 184, melt_temp: 1080, fluidName: "gtceu:copper", props: [].concat(oreProperty, dustProperty) },
    "pyrite": { forging_temp: 138, welding_temp: 184, melt_temp: 1535, fluidName: "gtceu:iron", props: [].concat(oreProperty, dustProperty) },
    "sphalerite": { forging_temp: 138, welding_temp: 184, melt_temp: 420, fluidName: "gtceu:zinc", props: [].concat(oreProperty, dustProperty) },
    "tetrahedrite": { forging_temp: 138, welding_temp: 184, melt_temp: 1080, fluidName: "gtceu:copper", props: [].concat(oreProperty, dustProperty) }
}

const removeAllTagsItems = [
    'tfc:ore/amethyst', 
    'tfc:ore/diamond', 
    'tfc:ore/lapis_lazuli', 
    'tfc:ore/emerald', 
    'tfc:ore/pyrite', 
    'tfc:ore/opal', 
    'tfc:ore/ruby', 
    'tfc:ore/sapphire', 
    'tfc:ore/topaz',
    
    'tfc:gem/amethyst', 
    'tfc:gem/diamond', 
    'tfc:gem/lapis_lazuli', 
    'tfc:gem/emerald', 
    'tfc:gem/pyrite', 
    'tfc:gem/opal', 
    'tfc:gem/ruby', 
    'tfc:gem/sapphire', 
    'tfc:gem/topaz',

    'tfc:ore/bituminous_coal',
    'tfc:ore/lignite'
]
