// priority: 0

const defaultProperty = [
    "ingot"
]

const dustProperty = [
    "nugget",
    "dust",
    "dust_small",
    "dust_tiny",
]

const oreProperty = [
    "poor_raw",
    "normal_raw",
    "rich_raw"
]

const partProperty = [
    "double_ingot",
    "sheet",
    "double_sheet",
    "rod",
    "block",
    "block_stairs",
    "block_slab"
]

const armorProperty = [
    "boots",
    "greaves",
    "chestplate",
    "helmet",
    "shield",
    "unfinished_boots",
    "unfinished_chestplate",
    "unfinished_greaves",
    "unfinished_helmet",
]

const toolProperty = [
    "axe_head",
    "axe",
    "chisel_head",
    "chisel",
    "hoe_head",
    "fish_hook",
    "fishing_rod",
    "hammer_head",
    "hammer",
    "hoe",
    "hoe_head",
    "horse_armor",
    "javelin_head",
    "javelin",
    "knife_blade",
    "knife",
    "mace_head",
    "mace",
    "pickaxe_head",
    "pickaxe",
    "propick_head",
    "propick",
    "saw_blade",
    "saw",
    "scythe_blade",
    "scythe",
    "shears",
    "shovel_head",
    "shovel",
    "sword_blade",
    "sword",
    "tuyere"
]

const utilityProperty = [
    "anvil",
    "bars",
    "block",
    "block_stairs",
    "block_slab",
    "chain",
    "lamp",
    "trapdoor",
    "unfinished_lamp"
]

const ItemHeats = {
    "nugget": { heat_capacity : 0.124, metal_amount: { 
        "bismuth": { metalName: "bismuth", amount: 16 },
        "cassiterite": { metalName: "tin", amount: 16 },
        "copper": { metalName: "copper", amount: 16 },
        "garnierite": { metalName: "nickel", amount: 14 },
        "gold": { metalName: "gold", amount: 16 },
        "hematite": { metalName: "iron", amount: 13 },
        "iron": { metalName: "iron", amount: 16 },
        "limonite": { metalName: "iron", amount: 14 },
        "magnetite": { metalName: "iron", amount: 14 },
        "malachite": { metalName: "copper", amount: 13 },
        "nickel": { metalName: "nickel", amount: 16 },
        "pyrite": { metalName: "iron", amount: 12 },
        "silver": { metalName: "silver", amount: 16 },
        "sphalerite": { metalName: "tin", amount: 16 },
        "tetrahedrite": { metalName: "copper", amount: 14 },
        "tin": { metalName: "tin", amount: 16 },
    }, input: (name) => { return { tag: `forge:nuggets/${name}` } }, output : { item: 'gtceu:%s_nugget' } },
    
    "dust": { heat_capacity : 1.429, metal_amount: { 
        "bismuth": { metalName: "bismuth", amount: 144 },
        "cassiterite": { metalName: "tin", amount: 144 },
        "copper": { metalName: "copper", amount: 144 },
        "garnierite": { metalName: "nickel", amount: 126 },
        "gold": { metalName: "gold", amount: 144 },
        "hematite": { metalName: "iron", amount: 117 },
        "iron": { metalName: "iron", amount: 144 },
        "limonite": { metalName: "iron", amount: 126 },
        "magnetite": { metalName: "iron", amount: 126 },
        "malachite": { metalName: "copper", amount: 117 },
        "nickel": { metalName: "nickel", amount: 144 },
        "pyrite": { metalName: "iron", amount: 123 },
        "silver": { metalName: "silver", amount: 144 },
        "sphalerite": { metalName: "tin", amount: 144 },
        "tetrahedrite": { metalName: "copper", amount: 126 },
        "tin": { metalName: "tin", amount: 144 },
    }, input : { tag: 'forge:dusts/%s' }, output : { item: 'gtceu:%s_dust' } },
    
    
    "dust_small": { heat_capacity : 0.714, metal_amount: { 
        "bismuth": { metalName: "bismuth", amount: 36 },
        "cassiterite": { metalName: "tin", amount: 36 },
        "copper": { metalName: "copper", amount: 36 },
        "garnierite": { metalName: "nickel", amount: 31 },
        "gold": { metalName: "gold", amount: 36 },
        "hematite": { metalName: "iron", amount: 29 },
        "iron": { metalName: "iron", amount: 36 },
        "limonite": { metalName: "iron", amount: 31 },
        "magnetite": { metalName: "iron", amount: 31 },
        "malachite": { metalName: "copper", amount: 29 },
        "nickel": { metalName: "nickel", amount: 36 },
        "pyrite": { metalName: "iron", amount: 27 },
        "silver": { metalName: "silver", amount: 36 },
        "sphalerite": { metalName: "tin", amount: 36 },
        "tetrahedrite": { metalName: "copper", amount: 31 },
        "tin": { metalName: "tin", amount: 36 },
    }, input : { tag: 'forge:dusts/small/%s' }, output : { item: 'gtceu:%s_dust_small' } },
    
    
    "dust_tiny": { heat_capacity : 0.357, metal_amount: { 
        "bismuth": { metalName: "bismuth", amount: 16 },
        "cassiterite": { metalName: "tin", amount: 16 },
        "copper": { metalName: "copper", amount: 16 },
        "garnierite": { metalName: "nickel", amount: 14 },
        "gold": { metalName: "gold", amount: 16 },
        "hematite": { metalName: "iron", amount: 13 },
        "iron": { metalName: "iron", amount: 16 },
        "limonite": { metalName: "iron", amount: 14 },
        "magnetite": { metalName: "iron", amount: 14 },
        "malachite": { metalName: "copper", amount: 13 },
        "nickel": { metalName: "nickel", amount: 16 },
        "pyrite": { metalName: "iron", amount: 12 },
        "silver": { metalName: "silver", amount: 16 },
        "sphalerite": { metalName: "tin", amount: 16 },
        "tetrahedrite": { metalName: "copper", amount: 14 },
        "tin": { metalName: "tin", amount: 16 },
    }, input : { tag: 'forge:dusts/tiny/%s' }, output : { item: 'gtceu:%s_dust_tiny' } },
    
    
    "poor_raw": { heat_capacity : 1.429, metal_amount: { 
        "bismuth": { metalName: "bismuth", amount: 24 },
        "cassiterite": { metalName: "tin", amount: 24 },
        "copper": { metalName: "copper", amount: 24 },
        "garnierite": { metalName: "nickel", amount: 21 },
        "gold": { metalName: "gold", amount: 24 },
        "hematite": { metalName: "iron", amount: 18 },
        "iron": { metalName: "iron", amount: 24 },
        "limonite": { metalName: "iron", amount: 21 },
        "magnetite": { metalName: "iron", amount: 21 },
        "malachite": { metalName: "copper", amount: 18 },
        "nickel": { metalName: "nickel", amount: 24 },
        "pyrite": { metalName: "iron", amount: 18 },
        "silver": { metalName: "silver", amount: 24 },
        "sphalerite": { metalName: "tin", amount: 24 },
        "tetrahedrite": { metalName: "copper", amount: 21 },
        "tin": { metalName: "tin", amount: 24 },
    }, input : { tag: 'forge:poor_raw_materials/%s' }, output : { item: 'gtceu:poor_raw_%s' } },
    
    
    "normal_raw": { heat_capacity : 1.429, metal_amount: { 
        "bismuth": { metalName: "bismuth", amount: 36 },
        "cassiterite": { metalName: "tin", amount: 36 },
        "copper": { metalName: "copper", amount: 36 },
        "garnierite": { metalName: "nickel", amount: 31 },
        "gold": { metalName: "gold", amount: 36 },
        "hematite": { metalName: "iron", amount: 29 },
        "iron": { metalName: "iron", amount: 36 },
        "limonite": { metalName: "iron", amount: 31 },
        "magnetite": { metalName: "iron", amount: 31 },
        "malachite": { metalName: "copper", amount: 29 },
        "nickel": { metalName: "nickel", amount: 36 },
        "pyrite": { metalName: "iron", amount: 27 },
        "silver": { metalName: "silver", amount: 36 },
        "sphalerite": { metalName: "tin", amount: 36 },
        "tetrahedrite": { metalName: "copper", amount: 31 },
        "tin": { metalName: "tin", amount: 36 },
    }, input : { tag: 'forge:raw_materials/%s' }, output : { item: 'gtceu:raw_%s' } },
    
    
    "rich_raw": { heat_capacity : 1.429, metal_amount: { 
        "bismuth": { metalName: "bismuth", amount: 48 },
        "cassiterite": { metalName: "tin", amount: 48 },
        "copper": { metalName: "copper", amount: 48 },
        "garnierite": { metalName: "nickel", amount: 42 },
        "gold": { metalName: "gold", amount: 48 },
        "hematite": { metalName: "iron", amount: 39 },
        "iron": { metalName: "iron", amount: 48 },
        "limonite": { metalName: "iron", amount: 42 },
        "magnetite": { metalName: "iron", amount: 42 },
        "malachite": { metalName: "copper", amount: 39 },
        "nickel": { metalName: "nickel", amount: 48 },
        "pyrite": { metalName: "iron", amount: 36 },
        "silver": { metalName: "silver", amount: 48 },
        "sphalerite": { metalName: "tin", amount: 48 },
        "tetrahedrite": { metalName: "copper", amount: 42 },
        "tin": { metalName: "tin", amount: 48 },
    }, input : { tag: 'forge:rich_raw_materials/%s' }, output : { item: 'gtceu:rich_raw_%s' } },
    
    "block_slab": { heat_capacity : null },
    "block_stairs": { heat_capacity : null },
    
    "block": { heat_capacity : 2.857, metal_amount: 1296, input : { tag: 'forge:storage_blocks/%s' }, output : { item: 'gtceu:%s_block' } },
    "anvil": { heat_capacity : 40.0, metal_amount: 2016, input : { item: 'tfc:metal/anvil/%s' }, output : { item: 'tfc:metal/anvil/%s' } },
    "chain": { heat_capacity : 0.171, metal_amount: 9, input : { item: 'tfc:metal/chain/%s' }, output : { item: 'tfc:metal/chain/%s' } },
    "bars": { heat_capacity : 0.714, metal_amount: 36, input : { item: 'tfc:metal/bars/%s' }, output : { item: 'tfc:metal/bars/%s' } },
    "trapdoor": { heat_capacity : 5.714, metal_amount: 288, input : { item: 'tfc:metal/trapdoor/%s' }, output : { item: 'tfc:metal/trapdoor/%s' } },
    "lamp": { heat_capacity : 2.857, metal_amount: 144, input : { item: 'tfc:metal/lamp/%s' }, output : { item: 'tfc:metal/lamp/%s' } },
    "unfinished_lamp": { heat_capacity : 2.857, metal_amount: 144, input : { item: 'tfc:metal/unfinished_lamp/%s' }, output : { item: 'tfc:metal/unfinished_lamp/%s' } },
    
    "helmet": { heat_capacity : 17.143, metal_amount: 864, input : { item: 'tfc:metal/helmet/%s' }, output : { item: 'tfc:metal/helmet/%s' } },
    "chestplate": { heat_capacity : 22.857, metal_amount: 1152, input : { item: 'tfc:metal/chestplate/%s' }, output : { item: 'tfc:metal/chestplate/%s' } },
    "greaves": { heat_capacity : 17.143, metal_amount: 864, input : { item: 'tfc:metal/greaves/%s' }, output : { item: 'tfc:metal/greaves/%s' } },
    "boots": { heat_capacity : 11.429, metal_amount: 576, input : { item: 'tfc:metal/boots/%s' }, output : { item: 'tfc:metal/boots/%s' } },
    "unfinished_boots": { heat_capacity : 5.714, metal_amount: 288, input : { item: 'tfc:metal/unfinished_boots/%s' }, output : { item: 'tfc:metal/unfinished_boots/%s' } },
    "unfinished_chestplate": { heat_capacity : 11.429, metal_amount: 576, input : { item: 'tfc:metal/unfinished_chestplate/%s' }, output : { item: 'tfc:metal/unfinished_chestplate/%s' } },
    "unfinished_greaves": { heat_capacity : 11.429, metal_amount: 576, input : { item: 'tfc:metal/unfinished_greaves/%s' }, output : { item: 'tfc:metal/unfinished_greaves/%s' } },
    "unfinished_helmet": { heat_capacity : 11.429, metal_amount: 576, input : { item: 'tfc:metal/unfinished_helmet/%s' }, output : { item: 'tfc:metal/unfinished_helmet/%s' } },
    
    "horse_armor": { heat_capacity : 34.286, metal_amount: 1728, input : { item: 'tfc:metal/horse_armor/%s' }, output : { item: 'tfc:metal/horse_armor/%s' } },

    "sword_blade": { heat_capacity : 5.714, metal_amount: 288, input : { tag: 'forge:sword_heads/%s' }, output : { item: 'gtceu:%s_sword_head' } },
    "sword": { heat_capacity : 5.714, metal_amount: 288, input : { item: 'gtceu:%s_sword' }, output : { item: 'gtceu:%s_sword' } },
    "pickaxe_head": { heat_capacity : 2.857, metal_amount: 144, input : { tag: 'forge:pickaxe_heads/%s' }, output : { tag: 'forge:pickaxe_heads/%s' }  },
    "pickaxe": { heat_capacity : 2.857, metal_amount: 144, input : { item: 'gtceu:%s_pickaxe' }, output : { item: 'gtceu:%s_pickaxe' } },
    "axe_head": { heat_capacity : 2.857, metal_amount: 144, input : { tag: 'forge:axe_heads/%s' }, output : { item: 'gtceu:%s_axe_head' } },
    "axe": { heat_capacity : 2.857, metal_amount: 144, input : { item: 'gtceu:%s_axe' }, output : { item: 'gtceu:%s_axe' } },
    "shovel_head": { heat_capacity : 2.857, metal_amount: 144, input : { tag: 'forge:shovel_heads/%s' }, output : { item: 'gtceu:%s_shovel_head' } },
    "shovel": { heat_capacity : 2.857, metal_amount: 144, input : { item: 'gtceu:%s_shovel' }, output : { item: 'gtceu:%s_shovel' } },
    "hammer_head": { heat_capacity : 2.857, metal_amount: 144, input : { tag: 'forge:hammer_heads/%s' }, output : { item: 'gtceu:%s_hammer_head' } },
    "hammer": { heat_capacity : 2.857, metal_amount: 144, input : { item: 'gtceu:%s_hammer' }, output : { item: 'gtceu:%s_hammer' } },
    "hoe_head": { heat_capacity : 2.857, metal_amount: 144, input : { tag: 'forge:hoe_heads/%s' }, output : { item: 'gtceu:%s_hoe_head' } },
    "hoe": { heat_capacity : 2.857, metal_amount: 144, input : { item: 'gtceu:%s_hoe' }, output : { item: 'gtceu:%s_hoe' } },
    "knife_blade": { heat_capacity : 2.857, metal_amount: 144, input : { tag: 'forge:knife_heads/%s' }, output : { item: 'gtceu:%s_knife_head' } },
    "knife": { heat_capacity : 2.857, metal_amount: 144, input : { item: 'gtceu:%s_knife' }, output : { item: 'gtceu:%s_knife' } },
    "saw_blade": { heat_capacity : 2.857, metal_amount: 144, input : { tag: 'forge:saw_heads/%s' }, output : { item: 'gtceu:%s_saw_head' } },
    "saw": { heat_capacity : 2.857, metal_amount: 144, input : { item: 'gtceu:%s_saw' }, output : { item: 'gtceu:%s_saw' } },
    "scythe_blade": { heat_capacity : 2.857, metal_amount: 144, input : { tag: 'forge:scythe_heads/%s' }, output : { item: 'gtceu:%s_scythe_head' } },
    "scythe": { heat_capacity : 2.857, metal_amount: 144, input : { item: 'gtceu:%s_scythe' }, output : { item: 'gtceu:%s_scythe' } },
    "chisel_head": { heat_capacity : 2.857, input : { item: 'tfc:metal/chisel_head/%s' }, output : { item: 'tfc:metal/chisel_head/%s' }, },
    "chisel": { heat_capacity : 2.857, metal_amount: 144, input : { item: 'tfc:metal/chisel/%s' }, output : { item: 'tfc:metal/chisel/%s' } },
    "javelin_head": { heat_capacity : 2.857, metal_amount: 144, input : { item: 'tfc:metal/javelin_head/%s' }, output : { item: 'tfc:metal/javelin_head/%s' } },
    "javelin": { heat_capacity : 2.857, metal_amount: 144, input : { item: 'tfc:metal/javelin/%s' }, output : { item: 'tfc:metal/javelin/%s' } },
    "propick_head": { heat_capacity :  2.857, metal_amount: 144, input : { item: 'tfc:metal/propick_head/%s' }, output : { item: 'tfc:metal/propick_head/%s' } },
    "propick": { heat_capacity : 2.857, metal_amount: 144, input : { item: 'tfc:metal/propick/%s' }, output : { item: 'tfc:metal/propick/%s' } },
    "mace_head": { heat_capacity : 5.714, metal_amount: 288, input : { item: 'tfc:metal/mace_head/%s' }, output : { item: 'tfc:metal/mace_head/%s' } },
    "mace": { heat_capacity : 5.714, metal_amount: 288, input : { item: 'tfc:metal/mace/%s' }, output : { item: 'tfc:metal/mace/%s' } },
    "fish_hook": { heat_capacity : 5.714, metal_amount: 288, input : { item: 'tfc:metal/fish_hook/%s' }, output : { item: 'tfc:metal/fish_hook/%s' } },
    "fishing_rod": { heat_capacity : 5.714, metal_amount: 288, input : { item: 'tfc:metal/fishing_rod/%s' }, output : { item: 'tfc:metal/fishing_rod/%s' } },
    "tuyere": { heat_capacity : 11.429, metal_amount: 576, input : { item: 'tfc:metal/tuyere/%s' }, output : { item: 'tfc:metal/tuyere/%s' } },
    "shears": { heat_capacity : 5.714, metal_amount: 288, input : { item: 'tfc:metal/shears/%s' }, output : { item: 'tfc:metal/shears/%s' } },
    "shield": { heat_capacity : 11.429, metal_amount: 576, input : { item: 'tfc:metal/shield/%s' }, output : { item: 'tfc:metal/shield/%s' } },

    "ingot": { heat_capacity : 2.857, metal_amount: 144, input : { tag: 'forge:ingots/%s' }, output : { item: Item.getId(ChemicalHelper.get(TagPrefix.ingot, GTMaterials.Bronze, 1)) } },
    "double_ingot": { heat_capacity : 5.714, metal_amount: 288, input : { tag: 'forge:double_ingots/%s' }, output : { item: 'tfc:metal/double_ingot/%s' } },
    "sheet": { heat_capacity : 5.714, metal_amount: 288, input : { tag: 'forge:plates/%s' }, output : { item: 'gtceu:%s_plate' } },
    "double_sheet": { heat_capacity : 11.429, metal_amount: 576, input : { tag: 'forge:plates/double/%s' }, output : { item: 'gtceu:%s_double_plate' } },
    "rod": { heat_capacity : 1.429, metal_amount: 72, input : { tag: 'forge:rods/%s' }, output : { item: 'gtceu:%s_rod' } },
}

const Metals = {
    "bismuth" : { forging_temp: 162, welding_temp: 216, melt_temp: 270, props: [].concat(defaultProperty, partProperty, oreProperty, dustProperty) },
    "brass" : { forging_temp: 558, welding_temp: 744, melt_temp: 930, props: [].concat(defaultProperty, partProperty, oreProperty, dustProperty) },
    "gold" : { forging_temp: 636, welding_temp: 848, melt_temp: 1060, props: [].concat(defaultProperty, partProperty, oreProperty, dustProperty) },
    "nickel" : { forging_temp: 872, welding_temp: 1162, melt_temp: 1453, props: [].concat(defaultProperty, partProperty, oreProperty, dustProperty) },
    "rose_gold" : { forging_temp: 576, welding_temp: 768, melt_temp: 960, props: [].concat(defaultProperty, partProperty, oreProperty, dustProperty) },
    "silver" : { forging_temp: 577, welding_temp: 769, melt_temp: 961, props: [].concat(defaultProperty, partProperty, oreProperty, dustProperty) },
    "tin" : { forging_temp: 138, welding_temp: 184, melt_temp: 230, props: [].concat(defaultProperty, partProperty, oreProperty, dustProperty) },
    "zinc" : { forging_temp: 252, welding_temp: 336, melt_temp: 420, props: [].concat(defaultProperty, partProperty, dustProperty) },
    "sterling_silver": { forging_temp: 570, welding_temp: 760, melt_temp: 950, props: [].concat(defaultProperty, partProperty, dustProperty) },
    "copper" : { forging_temp: 648, welding_temp: 864, melt_temp: 1080, props: [].concat(defaultProperty, partProperty, armorProperty, toolProperty, utilityProperty, oreProperty, dustProperty) },
    "bismuth_bronze" : { forging_temp: 591, welding_temp: 788, melt_temp: 985, props: [].concat(defaultProperty, partProperty, armorProperty, toolProperty, utilityProperty, dustProperty) },
    "bronze" : { forging_temp: 570, welding_temp: 760, melt_temp: 950, props: [].concat(defaultProperty, partProperty, armorProperty, toolProperty, utilityProperty, dustProperty) },
    "black_bronze" : { forging_temp: 642, welding_temp: 856, melt_temp: 1070, props: [].concat(defaultProperty, partProperty, armorProperty, toolProperty, utilityProperty, dustProperty) },
    "wrought_iron" : { forging_temp: 921, welding_temp: 1228, melt_temp: 1535, props: [].concat(defaultProperty, partProperty, armorProperty, toolProperty, utilityProperty, oreProperty, dustProperty) },
    "cast_iron" : { forging_temp: 921, welding_temp: 1228, melt_temp: 1535, customName: "iron", props: [].concat(defaultProperty, partProperty, oreProperty, dustProperty) },
    "pig_iron" : { forging_temp: 921, welding_temp: 1228, melt_temp: 1535, props: defaultProperty},
    "steel" : { forging_temp: 924, welding_temp: 1232, melt_temp: 1540, props: [].concat(defaultProperty, partProperty, armorProperty, toolProperty, utilityProperty, dustProperty) },
    "high_carbon_black_steel" : { forging_temp: 924, melt_temp: 1540, welding_temp: 1232, props: defaultProperty },
    "high_carbon_red_steel" : { forging_temp: 924, melt_temp: 1540, welding_temp: 1232, props: defaultProperty },
    "high_carbon_blue_steel" : { forging_temp: 924, melt_temp: 1540, welding_temp: 1232, props: defaultProperty },
    "weak_steel" : {  forging_temp: 924, welding_temp: 1232, melt_temp: 1540, props: defaultProperty },
    "weak_red_steel" : { forging_temp: 924, welding_temp: 1232, melt_temp: 1540, props: defaultProperty },
    "weak_blue_steel" : { forging_temp: 924, welding_temp: 1232, melt_temp: 1540, props: defaultProperty },
    "black_steel" : { forging_temp: 891, welding_temp: 1188, melt_temp: 1485, props: [].concat(defaultProperty, partProperty, armorProperty, toolProperty, utilityProperty, dustProperty) },
    "red_steel" : { forging_temp: 924, welding_temp: 1232, melt_temp: 1540, props: [].concat(defaultProperty, partProperty, armorProperty, toolProperty, utilityProperty, dustProperty) },
    "blue_steel" : { forging_temp: 924, welding_temp: 1232, melt_temp: 1540, props: [].concat(defaultProperty, partProperty, armorProperty, toolProperty, utilityProperty, dustProperty) },
    "unknown" : { forging_temp: 240, welding_temp: 320, melt_temp: 400, props: defaultProperty },
    "cassiterite" : { forging_temp: 138, welding_temp: 184, melt_temp: 230, props: [].concat(oreProperty, dustProperty) },
    "garnierite" : { forging_temp: 138, welding_temp: 184, melt_temp: 1453, props: [].concat(oreProperty, dustProperty) },
    "hematite" : { forging_temp: 138, welding_temp: 184, melt_temp: 1535, props: [].concat(oreProperty, dustProperty) },
    "limonite" : { forging_temp: 138, welding_temp: 184, melt_temp: 1535, props: [].concat(oreProperty, dustProperty) },
    "magnetite" : { forging_temp: 138, welding_temp: 184, melt_temp: 1535, props: [].concat(oreProperty, dustProperty) },
    "malachite" : { forging_temp: 138, welding_temp: 184, melt_temp: 1080, props: [].concat(oreProperty, dustProperty) },
    "pyrite" : { forging_temp: 138, welding_temp: 184, melt_temp: 1535, props: [].concat(oreProperty, dustProperty) },
    "sphalerite" : { forging_temp: 138, welding_temp: 184, melt_temp: 420, props: [].concat(oreProperty, dustProperty) },
    "tetrahedrite" : { forging_temp: 138, welding_temp: 184, melt_temp: 1080, props: [].concat(oreProperty, dustProperty) }
}


const asdas = {
    "1": { cock: 1, dead: (dead) => {}}
}

const removeAllTagsItems = [
    'tfc:ore/amethyst', 
    'tfc:ore/diamond', 
    'tfc:ore/lapis_lazuli', 
    'tfc:ore/emerald', 
    'tfc:ore/pyrite', 
    'tfc:ore/opal', 
    'tfc:ore/ruby', 
    'tfc:ore/sapphire', 
    'tfc:ore/topaz',
    
    'tfc:gem/amethyst', 
    'tfc:gem/diamond', 
    'tfc:gem/lapis_lazuli', 
    'tfc:gem/emerald', 
    'tfc:gem/pyrite', 
    'tfc:gem/opal', 
    'tfc:gem/ruby', 
    'tfc:gem/sapphire', 
    'tfc:gem/topaz',

    'tfc:ore/bituminous_coal',
    'tfc:ore/lignite'
]
