// priority: -100
"use strict";

global.RAIL_WAYS_DISABLED_ITEMS = [
    
    // Tracks
    'railways:track_dark_oak_narrow', 
    'railways:track_oak_narrow', 
    'railways:track_ender_narrow', 
    'railways:track_mangrove_narrow', 
    'railways:track_dark_oak', 
    'railways:track_oak', 
    'railways:track_ender', 
    'railways:track_mangrove', 
    'railways:track_dark_oak_wide', 
    'railways:track_oak_wide', 
    'railways:track_ender_wide', 
    'railways:track_mangrove_wide', 

    // Incompleted Tracks
    'railways:track_incomplete_ender_narrow', 
    'railways:track_incomplete_dark_oak_narrow', 
    'railways:track_incomplete_mangrove_narrow', 
    'railways:track_incomplete_dark_oak', 
    'railways:track_incomplete_oak', 
    'railways:track_incomplete_ender', 
    'railways:track_incomplete_mangrove', 
    'railways:track_incomplete_oak_wide', 
    'railways:track_incomplete_ender_wide', 
    'railways:track_incomplete_dark_oak_wide', 
    'railways:track_incomplete_mangrove_wide', 
    'railways:track_incomplete_oak_narrow', 
    'railways:track_incomplete_phantom',

    // Incomplete Caps
    'railways:white_incomplete_conductor_cap',
    'railways:orange_incomplete_conductor_cap',
    'railways:magenta_incomplete_conductor_cap',
    'railways:light_blue_incomplete_conductor_cap',
    'railways:yellow_incomplete_conductor_cap',
    'railways:lime_incomplete_conductor_cap',
    'railways:pink_incomplete_conductor_cap',
    'railways:gray_incomplete_conductor_cap',
    'railways:light_gray_incomplete_conductor_cap',
    'railways:cyan_incomplete_conductor_cap',
    'railways:purple_incomplete_conductor_cap',
    'railways:blue_incomplete_conductor_cap',
    'railways:brown_incomplete_conductor_cap',
    'railways:green_incomplete_conductor_cap',
    'railways:red_incomplete_conductor_cap',
    'railways:black_incomplete_conductor_cap',

    // Other
    'railways:conductor_vent',
    'railways:jukeboxcart',
    'railways:benchcart',

    // Dyes
    'railways:paint_brush',
    'railways:empty_paint_pitcher',
    'railways:sandy_paint_pitcher',
    'railways:brown_paint_pitcher',
    'railways:maroon_paint_pitcher',
    'railways:red_paint_pitcher',
    'railways:vermilion_paint_pitcher',
    'railways:orange_paint_pitcher',
    'railways:granite_paint_pitcher',
    'railways:dripstone_paint_pitcher',
    'railways:ochrum_paint_pitcher',
    'railways:yellow_paint_pitcher',
    'railways:chartreuse_paint_pitcher',
    'railways:olive_green_paint_pitcher',
    'railways:lime_paint_pitcher',
    'railways:green_paint_pitcher',
    'railways:pine_green_paint_pitcher',
    'railways:cyan_paint_pitcher',
    'railways:sea_green_paint_pitcher',
    'railways:turquoise_paint_pitcher',
    'railways:light_blue_paint_pitcher',
    'railways:blue_paint_pitcher',
    'railways:royal_blue_paint_pitcher',
    'railways:purple_paint_pitcher',
    'railways:magenta_paint_pitcher',
    'railways:pink_paint_pitcher',
    'railways:white_paint_pitcher',
    'railways:diorite_paint_pitcher',
    'railways:limestone_paint_pitcher',
    'railways:light_gray_paint_pitcher',
    'railways:tuff_paint_pitcher',
    'railways:gray_paint_pitcher',
    'railways:scorchia_paint_pitcher',
    'railways:black_paint_pitcher',
];
