// priority: 0

global.RAIL_WAYS_DISABLED_ITEMS = [
    
    // Tracks
    'railways:track_ender_narrow', 
    'railways:track_birch_narrow', 
    'railways:track_blackstone_narrow', 
    'railways:track_dark_oak_narrow', 
    'railways:track_jungle_narrow', 
    'railways:track_mangrove_narrow', 
    'railways:track_crimson_narrow', 
    'railways:track_acacia', 
    'railways:track_birch', 
    'railways:track_crimson', 
    'railways:track_dark_oak', 
    'railways:track_jungle', 
    'railways:track_oak', 
    'railways:track_spruce', 
    'railways:track_warped', 
    'railways:track_blackstone', 
    'railways:track_ender', 
    'railways:track_phantom', 
    'railways:track_mangrove', 
    'railways:track_oak_wide', 
    'railways:track_warped_wide', 
    'railways:track_spruce_wide', 
    'railways:track_acacia_wide', 
    'railways:track_ender_wide', 
    'railways:track_birch_wide', 
    'railways:track_blackstone_wide', 
    'railways:track_dark_oak_wide', 
    'railways:track_jungle_wide', 
    'railways:track_mangrove_wide', 
    'railways:track_crimson_wide', 
    'railways:track_oak_narrow', 
    'railways:track_spruce_narrow', 
    'railways:track_warped_narrow', 
    'railways:track_acacia_narrow',
    // Возможно включим позже
    'railways:track_tieless',
    'railways:track_tieless_narrow',
    'railways:track_tieless_wide',

    // Incompleted Tracks
    'railways:track_incomplete_ender_narrow', 
    'railways:track_incomplete_birch_narrow', 
    'railways:track_incomplete_blackstone_narrow', 
    'railways:track_incomplete_dark_oak_narrow', 
    'railways:track_incomplete_jungle_narrow', 
    'railways:track_incomplete_mangrove_narrow', 
    'railways:track_incomplete_crimson_narrow', 
    'railways:track_incomplete_acacia', 
    'railways:track_incomplete_birch', 
    'railways:track_incomplete_crimson', 
    'railways:track_incomplete_dark_oak', 
    'railways:track_incomplete_jungle', 
    'railways:track_incomplete_oak', 
    'railways:track_incomplete_spruce', 
    'railways:track_incomplete_warped', 
    'railways:track_incomplete_blackstone', 
    'railways:track_incomplete_ender', 
    'railways:track_incomplete_phantom', 
    'railways:track_incomplete_mangrove', 
    'railways:track_incomplete_oak_wide', 
    'railways:track_incomplete_warped_wide', 
    'railways:track_incomplete_spruce_wide', 
    'railways:track_incomplete_acacia_wide', 
    'railways:track_incomplete_ender_wide', 
    'railways:track_incomplete_birch_wide', 
    'railways:track_incomplete_blackstone_wide', 
    'railways:track_incomplete_dark_oak_wide', 
    'railways:track_incomplete_jungle_wide', 
    'railways:track_incomplete_mangrove_wide', 
    'railways:track_incomplete_crimson_wide', 
    'railways:track_incomplete_oak_narrow', 
    'railways:track_incomplete_spruce_narrow', 
    'railways:track_incomplete_warped_narrow', 
    'railways:track_incomplete_acacia_narrow',
    // Возможно включим позже
    'railways:track_incomplete_tieless',
    'railways:track_incomplete_tieless_narrow',
    'railways:track_incomplete_tieless_wide',

    // Caps
    'railways:white_conductor_cap',
    'railways:orange_conductor_cap',
    'railways:magenta_conductor_cap',
    'railways:light_blue_conductor_cap',
    'railways:yellow_conductor_cap',
    'railways:lime_conductor_cap',
    'railways:pink_conductor_cap',
    'railways:gray_conductor_cap',
    'railways:light_gray_conductor_cap',
    'railways:cyan_conductor_cap',
    'railways:purple_conductor_cap',
    'railways:blue_conductor_cap',
    'railways:brown_conductor_cap',
    'railways:green_conductor_cap',
    'railways:red_conductor_cap',
    'railways:black_conductor_cap',

    // Incomplete Caps
    'railways:white_incomplete_conductor_cap',
    'railways:orange_incomplete_conductor_cap',
    'railways:magenta_incomplete_conductor_cap',
    'railways:light_blue_incomplete_conductor_cap',
    'railways:yellow_incomplete_conductor_cap',
    'railways:lime_incomplete_conductor_cap',
    'railways:pink_incomplete_conductor_cap',
    'railways:gray_incomplete_conductor_cap',
    'railways:light_gray_incomplete_conductor_cap',
    'railways:cyan_incomplete_conductor_cap',
    'railways:purple_incomplete_conductor_cap',
    'railways:blue_incomplete_conductor_cap',
    'railways:brown_incomplete_conductor_cap',
    'railways:green_incomplete_conductor_cap',
    'railways:red_incomplete_conductor_cap',
    'railways:black_incomplete_conductor_cap',

    // Other
    'railways:conductor_vent',
    'railways:jukeboxcart',
    'railways:benchcart'
];