project_id_env: '${{ vars.CROWDIN_ID }}'
api_token_env: '${{ secrets.CROWDIN_TOKEN }}'
base_url: 'https://api.crowdin.com'
preserve_hierarchy: 1
pull_request_title: New Crowdin updates
pull_request_labels:
  - 'Pull request: Translation'
commit_message: '[translation] New translations {fileName} ({languageName})'
files:
  - source: /kubejs/assets/*/lang/en_us.json
    translation: /%original_path%/%locale_with_underscore%.json
    update_option: update_without_changes
    languages_mapping:
      locale_with_underscore:
        en-US: en_us
        en-GB: en_gb
        ru: ru_ru
        uk: uk_ua
        ja: ja_jp
        zh-CN: zh_cn
        zh-TW: zh_tw
        es-ES: es_es
        de: de_de
        fr: fr_fr
