// priority: 0
"use strict";

global.CREATE_ADDITIONS_DISABLED_ITEMS = [
    'createaddition:electrum_ingot', 
    'createaddition:electrum_nugget', 
    'createaddition:electrum_amulet', 
    'createaddition:biomass_pellet', 
    'createaddition:diamond_grit', 
    'createaddition:biomass', 
    'createaddition:creative_energy', 
    'createaddition:electrum_rod', 
    'createaddition:gold_rod', 
    'createaddition:copper_rod', 
    'createaddition:iron_rod', 
    'createaddition:electrum_wire', 
    'createaddition:brass_rod', 
    'createaddition:iron_wire', 
    'createaddition:gold_wire', 
    'createaddition:electrum_sheet', 
    'createaddition:zinc_sheet', 
    'createaddition:copper_wire',
    'createaddition:seed_oil_bucket',
    'createaddition:bioethanol_bucket',
    'createaddition:tesla_coil',
    'createaddition:capacitor',
    'createaddition:large_connector',
    'createaddition:electrum_spool',
    'createaddition:gold_spool',
    'createaddition:biomass_pellet_block',
    'createaddition:connector', 
    'createaddition:redstone_relay',
    'createaddition:spool', 
    'createaddition:copper_spool', 
    'createaddition:festive_spool', 
    'createaddition:small_light_connector',
    'createaddition:electrum_block',
    'createaddition:portable_energy_interface',
    'createaddition:straw'
];
