const registerGTCEuRecipeTypes = (event) => {

	event.create('steam_bloomery')
		.category('steam_bloomery')
		.setEUIO('in')
		.setMaxIOSize(2, 1, 0, 0)
		.setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)
		.setSound(GTSoundEntries.FIRE)

	event.create('large_solar_panel')
		.category('generator')
		.setEUIO('out')
		.setMaxIOSize(2, 0, 2, 1)
		.setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)
		.setSound(GTSoundEntries.COOLING)

	event.create('large_solar_panel_tier2')
		.category('generator')
		.setEUIO('out')
		.setMaxIOSize(2, 0, 2, 1)
		.setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)
		.setSound(GTSoundEntries.COOLING)

	event.create('large_solar_panel_tier3')
		.category('generator')
		.setEUIO('out')
		.setMaxIOSize(2, 0, 2, 1)
		.setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)
		.setSound(GTSoundEntries.COOLING)

	event.create('nuclear_fuel_factory')
		.category('nuclear_fuel_factory')
		.setEUIO('in')
		.setMaxIOSize(6, 1, 1, 0)
		.setSlotOverlay(false, false, GuiTextures.ATOMIC_OVERLAY_1)
		.setProgressBar(GuiTextures.PROGRESS_BAR_LATHE, FillDirection.LEFT_TO_RIGHT)
		.setSound(GTSoundEntries.CUT)

	event.create('heat_exchanger')
		.category('heat_exchanger')
		.setEUIO('in')
		.setMaxIOSize(0, 0, 4, 4)
		.setSlotOverlay(false, false, GuiTextures.ATOMIC_OVERLAY_1)
		.setProgressBar(GuiTextures.PROGRESS_BAR_GAS_COLLECTOR, FillDirection.LEFT_TO_RIGHT)
		.setSound(GTSoundEntries.TURBINE)
/* Just keeping it in case we got mod issues
	event.create('fission_reactor')
		.category('fission_reactor')
		.setEUIO('in')
		.setMaxIOSize(1, 0, 1, 2)
		.setSlotOverlay(false, false, GuiTextures.ATOMIC_OVERLAY_1)
		.setProgressBar(GuiTextures.PROGRESS_BAR_FUSION, FillDirection.LEFT_TO_RIGHT)
		.setSound(GTSoundEntries.ARC)
*/
	event.create('ostrum_harvester')
        .category('ostrum_harvester')
        .setEUIO('in')
        .setMaxIOSize(0, 1, 1, 0)
		.setSlotOverlay(false, false, GuiTextures.EXTRACTOR_OVERLAY)
        .setProgressBar(GuiTextures.PROGRESS_BAR_GAS_COLLECTOR, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.TURBINE)

	event.create('moon_dust_harvester')
        .category('moon_dust_harvester')
        .setEUIO('in')
        .setMaxIOSize(1, 1, 0, 0)
		.setSlotOverlay(false, false, GuiTextures.DUST_OVERLAY)
        .setProgressBar(GuiTextures.PROGRESS_BAR_GAS_COLLECTOR, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.TURBINE)

	event.create('ostrum_linear_accelerator')
        .category('ostrum_linear_accelerator')
        .setEUIO('in')
        .setMaxIOSize(1, 3, 3, 3)
		.setSlotOverlay(false, false, GuiTextures.EXTRACTOR_OVERLAY)
        .setProgressBar(GuiTextures.PROGRESS_BAR_EXTRACT, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.BATH)

}
