// priority: 0
"use strict";

function registerImmersiveVehiclesEnginesRecipes(event) {
	
	// LV
	event.recipes.gtceu.assembler('mts:mtsofficialpack.enginefranklin0335')
		.itemInputs('#forge:rotors/cobalt_brass', '4x mts:mtsofficialpack.sparkplug', '10x #forge:tiny_fluid_pipes/steel', '#forge:frames/invar', 'gtceu:lv_fluid_regulator', 'gtceu:lv_electric_piston', '8x #forge:foils/invar', '#tfg:rubber_belts')
		.inputFluids(Fluid.of('gtceu:lubricant', 2000))
		.itemOutputs('mts:mtsofficialpack.enginefranklin0335')
		.EUt(GTValues.VA[GTValues.LV])
		.duration(20 * 20)
		.circuit(1)
		.addMaterialInfo(true)

	event.recipes.gtceu.assembler('mts:mtsofficialpack.enginebristolmercury')
		.itemInputs('#forge:rotors/cobalt_brass', '4x mts:mtsofficialpack.sparkplug', '9x #forge:tiny_fluid_pipes/steel', '2x #forge:frames/invar', 'gtceu:lv_fluid_regulator', '2x gtceu:lv_electric_piston', '8x #forge:foils/invar', '#tfg:rubber_belts')
		.inputFluids(Fluid.of('gtceu:lubricant', 2000))
		.itemOutputs('mts:mtsofficialpack.enginebristolmercury')
		.EUt(GTValues.VA[GTValues.LV])
		.duration(20 * 20)
		.circuit(2)
		.addMaterialInfo(true)

	event.recipes.gtceu.assembler('mts:belroftmotors.engine_tuna')
		.itemInputs('4x mts:mtsofficialpack.sparkplug', '4x #forge:tiny_fluid_pipes/steel', '#forge:frames/invar', 'gtceu:lv_fluid_regulator', 'gtceu:lv_electric_piston', '8x #forge:foils/invar', '8x #tfg:rubber_rings', '#tfg:rubber_belts')
		.inputFluids(Fluid.of('gtceu:lubricant', 2000))
		.itemOutputs('mts:belroftmotors.engine_tuna')
		.EUt(GTValues.VA[GTValues.LV])
		.duration(20 * 20)
		.circuit(3)
		.addMaterialInfo(true)

	event.recipes.gtceu.assembler('mts:belroftmotors.engine_mahogany')
		.itemInputs('2x mts:mtsofficialpack.sparkplug', '4x #forge:tiny_fluid_pipes/steel', '#forge:frames/invar', 'gtceu:lv_fluid_regulator', 'gtceu:lv_electric_piston', '8x #forge:foils/invar', '8x #tfg:rubber_rings', '#tfg:rubber_belts')
		.inputFluids(Fluid.of('gtceu:lubricant', 2000))
		.itemOutputs('mts:belroftmotors.engine_mahogany')
		.EUt(GTValues.VA[GTValues.LV])
		.duration(20 * 20)
		.circuit(4)
		.addMaterialInfo(true)

	event.recipes.gtceu.assembler('mts:mtsofficialpack.enginequad')
		.itemInputs('4x mts:mtsofficialpack.sparkplug', '2x #forge:tiny_fluid_pipes/steel', '#forge:frames/invar', 'gtceu:lv_electric_pump', 'gtceu:lv_electric_piston', '8x #forge:foils/invar', '8x #tfg:rubber_rings', '#tfg:rubber_plates')
		.inputFluids(Fluid.of('gtceu:lubricant', 2000))
		.itemOutputs('mts:mtsofficialpack.enginequad')
		.EUt(GTValues.VA[GTValues.LV])
		.duration(20 * 20)
		.circuit(5)
		.addMaterialInfo(true)

	event.recipes.gtceu.assembler('mts:belroftmotors.bee_i3_engine')
		.itemInputs('2x mts:mtsofficialpack.sparkplug', '4x #forge:tiny_fluid_pipes/steel', '#forge:frames/invar', 'gtceu:lv_fluid_regulator', 'gtceu:lv_electric_piston', '8x #forge:foils/invar', '8x #tfg:rubber_rings', '#tfg:rubber_belts')
		.inputFluids(Fluid.of('gtceu:lubricant', 2000))
		.itemOutputs('mts:belroftmotors.bee_i3_engine')
		.EUt(GTValues.VA[GTValues.LV])
		.duration(20 * 20)
		.circuit(6)
		.addMaterialInfo(true)

	event.recipes.gtceu.assembler('mts:belroftmotors.enginepounderv8')
		.itemInputs('4x mts:mtsofficialpack.sparkplug', '8x #forge:tiny_fluid_pipes/steel', '#forge:frames/invar', 'gtceu:lv_fluid_regulator', '2x gtceu:lv_electric_piston', '8x #forge:foils/invar', '8x #tfg:rubber_rings', '#tfg:rubber_belts')
		.inputFluids(Fluid.of('gtceu:lubricant', 2000))
		.itemOutputs('mts:belroftmotors.enginepounderv8')
		.EUt(GTValues.VA[GTValues.LV])
		.duration(20 * 20)
		.circuit(7)
		.addMaterialInfo(true)

	event.recipes.gtceu.assembler('mts:mtsofficialpack.engineamci4')
		.itemInputs('4x mts:mtsofficialpack.sparkplug', '8x #forge:tiny_fluid_pipes/steel', '#forge:frames/invar', 'gtceu:lv_fluid_regulator', '2x gtceu:lv_electric_piston', '8x #forge:foils/wrought_iron', '8x #tfg:rubber_rings', '#tfg:rubber_belts')
		.inputFluids(Fluid.of('gtceu:lubricant', 2000))
		.itemOutputs('mts:mtsofficialpack.engineamci4')
		.EUt(GTValues.VA[GTValues.LV])
		.duration(20 * 20)
		.circuit(8)
		.addMaterialInfo(true)

	event.recipes.gtceu.assembler('mts:mtsofficialpack.enginedetroitdiesel')
		.itemInputs('6x mts:mtsofficialpack.sparkplug', '8x #forge:tiny_fluid_pipes/steel', '#forge:frames/invar', 'gtceu:lv_fluid_regulator', '2x gtceu:lv_electric_piston', '8x #forge:foils/wrought_iron', '8x #tfg:rubber_rings', '#tfg:rubber_belts')
		.inputFluids(Fluid.of('gtceu:lubricant', 2000))
		.itemOutputs('mts:mtsofficialpack.enginedetroitdiesel')
		.EUt(GTValues.VA[GTValues.LV])
		.duration(20 * 20)
		.circuit(9)
		.addMaterialInfo(true)

	// MV
	event.recipes.gtceu.assembler('mts:mtsofficialpack.engineallison250')
		.itemInputs('2x #forge:rotors/magnalium', '8x mts:mtsofficialpack.sparkplug', '12x #forge:tiny_fluid_pipes/aluminium', '2x #forge:frames/magnalium', '2x gtceu:mv_fluid_regulator', '3x gtceu:mv_electric_piston', '16x #forge:foils/magnalium', '16x #tfg:rubber_rings')
		.inputFluids(Fluid.of('gtceu:lubricant', 4000))
		.itemOutputs('mts:mtsofficialpack.engineallison250')
		.EUt(GTValues.VA[GTValues.MV])
		.duration(20 * 20)
		.circuit(1)
		.addMaterialInfo(true)

	event.recipes.gtceu.assembler('mts:mtsofficialpack.enginelycomingo360')
		.itemInputs('2x #forge:rotors/magnalium', '8x mts:mtsofficialpack.sparkplug', '12x #forge:tiny_fluid_pipes/aluminium', '2x #forge:frames/magnalium', '2x gtceu:mv_fluid_regulator', '3x gtceu:mv_electric_piston', '16x #forge:foils/magnalium', '16x #tfg:rubber_rings')
		.inputFluids(Fluid.of('gtceu:lubricant', 4000))
		.itemOutputs('mts:mtsofficialpack.enginelycomingo360')
		.EUt(GTValues.VA[GTValues.MV])
		.duration(20 * 20)
		.circuit(2)
		.addMaterialInfo(true)

	event.recipes.gtceu.assembler('mts:belroftmotors.engine_barracuda')
		.itemInputs('2x mts:mtsofficialpack.sparkplug', '6x #forge:tiny_fluid_pipes/aluminium', '#forge:frames/magnalium', 'gtceu:mv_fluid_regulator', '2x gtceu:mv_electric_piston', '16x #forge:foils/magnalium', '16x #tfg:rubber_rings', '#tfg:rubber_belts')
		.inputFluids(Fluid.of('gtceu:lubricant', 2000))
		.itemOutputs('mts:belroftmotors.engine_barracuda')
		.EUt(GTValues.VA[GTValues.MV])
		.duration(20 * 20)
		.circuit(3)
		.addMaterialInfo(true)

	event.recipes.gtceu.assembler('mts:belroftmotors.engine_highlander_v8')
		.itemInputs('4x mts:mtsofficialpack.sparkplug', '10x #forge:tiny_fluid_pipes/aluminium', '2x #forge:frames/magnalium', '2x gtceu:mv_fluid_regulator', '2x gtceu:mv_electric_piston', '16x #forge:foils/magnalium', '16x #tfg:rubber_rings', '#tfg:rubber_belts')
		.inputFluids(Fluid.of('gtceu:lubricant', 2000))
		.itemOutputs('mts:belroftmotors.engine_highlander_v8')
		.EUt(GTValues.VA[GTValues.MV])
		.duration(20 * 20)
		.circuit(4)
		.addMaterialInfo(true)

	event.shapeless('mts:belroftmotors.engine_highlander_v8_snorkel', ['mts:belroftmotors.engine_highlander_v8', 'tfg:snorkel', '#forge:tools/wrenches'])
		.id('tfg:shapeless/who_up_snorkeling_they_engine')

	event.recipes.tfc.extra_products_shapeless_crafting(
		'tfg:snorkel',
		event.shapeless('mts:belroftmotors.engine_highlander_v8', ['mts:belroftmotors.engine_highlander_v8_snorkel', '#forge:tools/wrenches']))
		.id('tfg:shapeless/unsnorkels_ur_engine')

	event.recipes.gtceu.assembler('mts:belroftmotors.engine_granite')
		.itemInputs('6x mts:mtsofficialpack.sparkplug', '12x #forge:tiny_fluid_pipes/aluminium', '2x #forge:frames/magnalium', '2x gtceu:mv_fluid_regulator', '2x gtceu:mv_electric_piston', '16x #forge:foils/magnalium', '16x #tfg:rubber_rings', '#tfg:rubber_belts')
		.inputFluids(Fluid.of('gtceu:lubricant', 2000))
		.itemOutputs('mts:belroftmotors.engine_granite')
		.EUt(GTValues.VA[GTValues.MV])
		.duration(20 * 20)
		.circuit(5)
		.addMaterialInfo(true)

	event.recipes.gtceu.assembler('mts:belroftmotors.engine_turbo_hauler_v8')
		.itemInputs('6x mts:mtsofficialpack.sparkplug', '10x #forge:tiny_fluid_pipes/aluminium', '2x #forge:frames/magnalium', '2x gtceu:mv_fluid_regulator', '2x gtceu:mv_electric_piston', '16x #forge:foils/magnalium', '16x #tfg:rubber_rings', '#tfg:rubber_belts')
		.inputFluids(Fluid.of('gtceu:lubricant', 2000))
		.itemOutputs('mts:belroftmotors.engine_turbo_hauler_v8')
		.EUt(GTValues.VA[GTValues.MV])
		.duration(20 * 20)
		.circuit(6)
		.addMaterialInfo(true)

	// HV
	event.recipes.gtceu.assembler('mts:mtsofficialpack.enginepw610f')
		.itemInputs('4x #forge:rotors/chromium', '64x #forge:bolts/stainless_steel', '16x #forge:plates/rene_41', '20x #forge:tiny_fluid_pipes/stainless_steel', '4x #forge:frames/mo_50_re', '4x gtceu:hv_fluid_regulator', '32x #forge:foils/vanadium_steel', '32x #tfg:rubber_rings')
		.inputFluids(Fluid.of('gtceu:lubricant', 8000))
		.itemOutputs('mts:mtsofficialpack.enginepw610f')
		.EUt(GTValues.VA[GTValues.HV])
		.duration(20 * 20)
		.circuit(1)
		.addMaterialInfo(true)

	event.recipes.gtceu.assembler('mts:mtsofficialpack.enginefordfe428')
		.itemInputs('16x mts:mtsofficialpack.sparkplug', '16x #forge:tiny_fluid_pipes/stainless_steel', '2x #forge:frames/mo_50_re', '4x gtceu:hv_fluid_regulator', '4x gtceu:hv_electric_piston', '32x #forge:foils/vanadium_steel', '32x #tfg:rubber_rings', '#tfg:rubber_belts')
		.inputFluids(Fluid.of('gtceu:lubricant', 8000))
		.itemOutputs('mts:mtsofficialpack.enginefordfe428')
		.EUt(GTValues.VA[GTValues.HV])
		.duration(20 * 20)
		.circuit(2)
		.addMaterialInfo(true)

	event.recipes.gtceu.assembler('mts:mtsofficialpack.enginemercedesm102')
		.itemInputs('16x mts:mtsofficialpack.sparkplug', '16x #forge:tiny_fluid_pipes/stainless_steel', '2x #forge:frames/mo_50_re', '4x gtceu:hv_fluid_regulator', '4x gtceu:hv_electric_piston', '32x #forge:foils/vanadium_steel', '32x #tfg:rubber_rings', '#tfg:rubber_belts')
		.inputFluids(Fluid.of('gtceu:lubricant', 8000))
		.itemOutputs('mts:mtsofficialpack.enginemercedesm102')
		.EUt(GTValues.VA[GTValues.HV])
		.duration(20 * 20)
		.circuit(3)
		.addMaterialInfo(true)

}