// priority: 0
"use strict";

// This file was generated by OresToFieldGuide, do not manually edit

const registerTFGOreVeinFeatures = (event) => {

	// #region earth ores

	event.add('tfc:in_biome/veins', 'tfg:earth/vein/deep_garnet_amethyst')
	event.add('tfc:in_biome/veins', 'tfg:earth/vein/deep_garnet_opal')
	event.add('tfc:in_biome/veins', 'tfg:earth/vein/deep_gold')
	event.add('tfc:in_biome/veins', 'tfg:earth/vein/deep_hematite')
	event.add('tfc:in_biome/veins', 'tfg:earth/vein/deep_limonite')
	event.add('tfc:in_biome/veins', 'tfg:earth/vein/deep_magnetite')
	event.add('tfc:in_biome/veins', 'tfg:earth/vein/deep_molybdenum')
	event.add('tfc:in_biome/veins', 'tfg:earth/vein/deep_pitchblende')
	event.add('tfc:in_biome/veins', 'tfg:earth/vein/deep_sapphire')
	event.add('tfc:in_biome/veins', 'tfg:earth/vein/deep_scheelite')
	event.add('tfc:in_biome/veins', 'tfg:earth/vein/deep_sheldonite')
	event.add('tfc:in_biome/veins', 'tfg:earth/vein/deep_topaz')
	event.add('tfc:in_biome/veins', 'tfg:earth/vein/normal_apatite')
	event.add('tfc:in_biome/veins', 'tfg:earth/vein/normal_basaltic_sands')
	event.add('tfc:in_biome/veins', 'tfg:earth/vein/normal_beryllium')
	event.add('tfc:in_biome/veins', 'tfg:earth/vein/normal_bismuthinite')
	event.add('tfc:in_biome/veins', 'tfg:earth/vein/normal_cassiterite')
	event.add('tfc:in_biome/veins', 'tfg:earth/vein/normal_coal')
	event.add('tfc:in_biome/veins', 'tfg:earth/vein/normal_copper')
	event.add('tfc:in_biome/veins', 'tfg:earth/vein/normal_garnet_tin')
	event.add('tfc:in_biome/veins', 'tfg:earth/vein/normal_garnierite')
	event.add('tfc:in_biome/veins', 'tfg:earth/vein/normal_gold')
	event.add('tfc:in_biome/veins', 'tfg:earth/vein/normal_graphite')
	event.add('tfc:in_biome/veins', 'tfg:earth/vein/normal_hematite')
	event.add('tfc:in_biome/veins', 'tfg:earth/vein/normal_lapis')
	event.add('tfc:in_biome/veins', 'tfg:earth/vein/normal_limonite')
	event.add('tfc:in_biome/veins', 'tfg:earth/vein/normal_lubricant')
	event.add('tfc:in_biome/veins', 'tfg:earth/vein/normal_magnetite')
	event.add('tfc:in_biome/veins', 'tfg:earth/vein/normal_manganese')
	event.add('tfc:in_biome/veins', 'tfg:earth/vein/normal_mica')
	event.add('tfc:in_biome/veins', 'tfg:earth/vein/normal_monazite')
	event.add('tfc:in_biome/veins', 'tfg:earth/vein/normal_oilsands')
	event.add('tfc:in_biome/veins', 'tfg:earth/vein/normal_olivine')
	event.add('tfc:in_biome/veins', 'tfg:earth/vein/normal_quartz')
	event.add('tfc:in_biome/veins', 'tfg:earth/vein/normal_redstone')
	event.add('tfc:in_biome/veins', 'tfg:earth/vein/normal_salt')
	event.add('tfc:in_biome/veins', 'tfg:earth/vein/normal_saltpeter')
	event.add('tfc:in_biome/veins', 'tfg:earth/vein/normal_silver')
	event.add('tfc:in_biome/veins', 'tfg:earth/vein/normal_sphalerite')
	event.add('tfc:in_biome/veins', 'tfg:earth/vein/normal_spodumene')
	event.add('tfc:in_biome/veins', 'tfg:earth/vein/normal_sulfur')
	event.add('tfc:in_biome/veins', 'tfg:earth/vein/normal_tetrahedrite')
	event.add('tfc:in_biome/veins', 'tfg:earth/vein/surface_bismuthinite')
	event.add('tfc:in_biome/veins', 'tfg:earth/vein/surface_cassiterite')
	event.add('tfc:in_biome/veins', 'tfg:earth/vein/surface_copper')
	event.add('tfc:in_biome/veins', 'tfg:earth/vein/surface_sphalerite')
	event.add('tfc:in_biome/veins', 'tfg:earth/vein/surface_tetrahedrite')

	// #endregion


	// #region moon ores

	event.add('tfg:moon_veins', 'tfg:moon/vein/moon_apatite')
	event.add('tfg:moon_veins', 'tfg:moon/vein/moon_bauxite')
	event.add('tfg:moon_veins', 'tfg:moon/vein/moon_beryllium')
	event.add('tfg:moon_veins', 'tfg:moon/vein/moon_desh')
	event.add('tfg:moon_veins', 'tfg:moon/vein/moon_garnierite')
	event.add('tfg:moon_veins', 'tfg:moon/vein/moon_graphite')
	event.add('tfg:moon_veins', 'tfg:moon/vein/moon_lubricant')
	event.add('tfg:moon_veins', 'tfg:moon/vein/moon_magnetite')
	event.add('tfg:moon_veins', 'tfg:moon/vein/moon_manganese')
	event.add('tfg:moon_veins', 'tfg:moon/vein/moon_mica')
	event.add('tfg:moon_veins', 'tfg:moon/vein/moon_molybdenum')
	event.add('tfg:moon_veins', 'tfg:moon/vein/moon_monazite')
	event.add('tfg:moon_veins', 'tfg:moon/vein/moon_pyrolusite')
	event.add('tfg:moon_veins', 'tfg:moon/vein/moon_quartz')
	event.add('tfg:moon_veins', 'tfg:moon/vein/moon_redstone')
	event.add('tfg:moon_veins', 'tfg:moon/vein/moon_saltpeter')
	event.add('tfg:moon_veins', 'tfg:moon/vein/moon_sapphire')
	event.add('tfg:moon_veins', 'tfg:moon/vein/moon_scheelite')
	event.add('tfg:moon_veins', 'tfg:moon/vein/moon_sheldonite')
	event.add('tfg:moon_veins', 'tfg:moon/vein/moon_silver')
	event.add('tfg:moon_veins', 'tfg:moon/vein/moon_sphalerite')
	event.add('tfg:moon_veins', 'tfg:moon/vein/moon_topaz')

	// #endregion


	// #region nether ores

	event.add('tfg:nether_veins', 'tfg:nether/vein/nether_anthracite')
	event.add('tfg:nether_veins', 'tfg:nether/vein/nether_apatite')
	event.add('tfg:nether_veins', 'tfg:nether/vein/nether_basaltic_sands')
	event.add('tfg:nether_veins', 'tfg:nether/vein/nether_beryllium')
	event.add('tfg:nether_veins', 'tfg:nether/vein/nether_cassiterite')
	event.add('tfg:nether_veins', 'tfg:nether/vein/nether_copper')
	event.add('tfg:nether_veins', 'tfg:nether/vein/nether_garnet')
	event.add('tfg:nether_veins', 'tfg:nether/vein/nether_garnet_tin')
	event.add('tfg:nether_veins', 'tfg:nether/vein/nether_garnierite')
	event.add('tfg:nether_veins', 'tfg:nether/vein/nether_goethite')
	event.add('tfg:nether_veins', 'tfg:nether/vein/nether_gold')
	event.add('tfg:nether_veins', 'tfg:nether/vein/nether_graphite')
	event.add('tfg:nether_veins', 'tfg:nether/vein/nether_hematite')
	event.add('tfg:nether_veins', 'tfg:nether/vein/nether_lapis')
	event.add('tfg:nether_veins', 'tfg:nether/vein/nether_lubricant')
	event.add('tfg:nether_veins', 'tfg:nether/vein/nether_magnetite')
	event.add('tfg:nether_veins', 'tfg:nether/vein/nether_manganese')
	event.add('tfg:nether_veins', 'tfg:nether/vein/nether_mica')
	event.add('tfg:nether_veins', 'tfg:nether/vein/nether_molybdenum')
	event.add('tfg:nether_veins', 'tfg:nether/vein/nether_monazite')
	event.add('tfg:nether_veins', 'tfg:nether/vein/nether_naquadah')
	event.add('tfg:nether_veins', 'tfg:nether/vein/nether_olivine')
	event.add('tfg:nether_veins', 'tfg:nether/vein/nether_pitchblende')
	event.add('tfg:nether_veins', 'tfg:nether/vein/nether_quartz')
	event.add('tfg:nether_veins', 'tfg:nether/vein/nether_redstone')
	event.add('tfg:nether_veins', 'tfg:nether/vein/nether_saltpeter')
	event.add('tfg:nether_veins', 'tfg:nether/vein/nether_sapphire')
	event.add('tfg:nether_veins', 'tfg:nether/vein/nether_scheelite')
	event.add('tfg:nether_veins', 'tfg:nether/vein/nether_sheldonite')
	event.add('tfg:nether_veins', 'tfg:nether/vein/nether_silver')
	event.add('tfg:nether_veins', 'tfg:nether/vein/nether_sphalerite')
	event.add('tfg:nether_veins', 'tfg:nether/vein/nether_sulfur')
	event.add('tfg:nether_veins', 'tfg:nether/vein/nether_sylvite')
	event.add('tfg:nether_veins', 'tfg:nether/vein/nether_tetrahedrite')
	event.add('tfg:nether_veins', 'tfg:nether/vein/nether_topaz')

	// #endregion

}
