// priority: 0
"use strict";

function registerMacawsForTFCItemTags(event) {
	global.MINECRAFT_DYE_NAMES.forEach(color => {
		event.remove(`mcw_tfc_aio:${color}_roofs`, `mcw_tfc_aio:roofs/${color}_roofs/${color}_roof_slab`);
	})
}

function registerMacawsBlockTags(event) {
    addAll(event, 'mcw_tfc_aio:attic_roofs', [
        'mcw_tfc_aio:roofs/acacia_roofs/acacia_attic_roof',
        'mcw_tfc_aio:roofs/acacia_roofs/acacia_planks_attic_roof',
        'mcw_tfc_aio:roofs/ash_roofs/ash_attic_roof',
        'mcw_tfc_aio:roofs/ash_roofs/ash_planks_attic_roof',
        'mcw_tfc_aio:roofs/aspen_roofs/aspen_attic_roof',
        'mcw_tfc_aio:roofs/aspen_roofs/aspen_planks_attic_roof',
        'mcw_tfc_aio:roofs/base_roofs/base_attic_roof',
        'mcw_tfc_aio:roofs/birch_roofs/birch_attic_roof',
        'mcw_tfc_aio:roofs/birch_roofs/birch_planks_attic_roof',
        'mcw_tfc_aio:roofs/black_concrete_roofs/black_concrete_attic_roof',
        'mcw_tfc_aio:roofs/black_roofs/black_attic_roof',
        'mcw_tfc_aio:roofs/black_terracotta_roofs/black_terracotta_attic_roof',
        'mcw_tfc_aio:roofs/blackwood_roofs/blackwood_attic_roof',
        'mcw_tfc_aio:roofs/blackwood_roofs/blackwood_planks_attic_roof',
        'mcw_tfc_aio:roofs/blue_concrete_roofs/blue_concrete_attic_roof',
        'mcw_tfc_aio:roofs/blue_terracotta_roofs/blue_terracotta_attic_roof',
        'mcw_tfc_aio:roofs/brick_roofs/bricks_attic_roof',
        'mcw_tfc_aio:roofs/brown_concrete_roofs/brown_concrete_attic_roof',
        'mcw_tfc_aio:roofs/brown_terracotta_roofs/brown_terracotta_attic_roof',
        'mcw_tfc_aio:roofs/chestnut_roofs/chestnut_attic_roof',
        'mcw_tfc_aio:roofs/chestnut_roofs/chestnut_planks_attic_roof',
        'mcw_tfc_aio:roofs/cyan_concrete_roofs/cyan_concrete_attic_roof',
        'mcw_tfc_aio:roofs/cyan_terracotta_roofs/cyan_terracotta_attic_roof',
        'mcw_tfc_aio:roofs/douglas_fir_roofs/douglas_fir_attic_roof',
        'mcw_tfc_aio:roofs/douglas_fir_roofs/douglas_fir_planks_attic_roof',
        'mcw_tfc_aio:roofs/gray_concrete_roofs/gray_concrete_attic_roof',
        'mcw_tfc_aio:roofs/gray_roofs/gray_attic_roof',
        'mcw_tfc_aio:roofs/gray_terracotta_roofs/gray_terracotta_attic_roof',
        'mcw_tfc_aio:roofs/green_concrete_roofs/green_concrete_attic_roof',
        'mcw_tfc_aio:roofs/green_terracotta_roofs/green_terracotta_attic_roof',
        'mcw_tfc_aio:roofs/hickory_roofs/hickory_attic_roof',
        'mcw_tfc_aio:roofs/hickory_roofs/hickory_planks_attic_roof',
        'mcw_tfc_aio:roofs/kapok_roofs/kapok_attic_roof',
        'mcw_tfc_aio:roofs/kapok_roofs/kapok_planks_attic_roof',
        'mcw_tfc_aio:roofs/light_blue_concrete_roofs/light_blue_concrete_attic_roof',
        'mcw_tfc_aio:roofs/light_blue_terracotta_roofs/light_blue_terracotta_attic_roof',
        'mcw_tfc_aio:roofs/light_gray_concrete_roofs/light_gray_concrete_attic_roof',
        'mcw_tfc_aio:roofs/light_gray_roofs/light_gray_attic_roof',
        'mcw_tfc_aio:roofs/light_gray_terracotta_roofs/light_gray_terracotta_attic_roof',
        'mcw_tfc_aio:roofs/lime_concrete_roofs/lime_concrete_attic_roof',
        'mcw_tfc_aio:roofs/lime_terracotta_roofs/lime_terracotta_attic_roof',
        'mcw_tfc_aio:roofs/magenta_concrete_roofs/magenta_concrete_attic_roof',
        'mcw_tfc_aio:roofs/magenta_terracotta_roofs/magenta_terracotta_attic_roof',
        'mcw_tfc_aio:roofs/mangrove_roofs/mangrove_attic_roof',
        'mcw_tfc_aio:roofs/mangrove_roofs/mangrove_planks_attic_roof',
        'mcw_tfc_aio:roofs/maple_roofs/maple_attic_roof',
        'mcw_tfc_aio:roofs/maple_roofs/maple_planks_attic_roof',
        'mcw_tfc_aio:roofs/oak_roofs/oak_attic_roof',
        'mcw_tfc_aio:roofs/oak_roofs/oak_planks_attic_roof',
        'mcw_tfc_aio:roofs/orange_concrete_roofs/orange_concrete_attic_roof',
        'mcw_tfc_aio:roofs/orange_terracotta_roofs/orange_terracotta_attic_roof',
        'mcw_tfc_aio:roofs/palm_roofs/palm_attic_roof',
        'mcw_tfc_aio:roofs/palm_roofs/palm_planks_attic_roof',
        'mcw_tfc_aio:roofs/pine_roofs/pine_attic_roof',
        'mcw_tfc_aio:roofs/pine_roofs/pine_planks_attic_roof',
        'mcw_tfc_aio:roofs/pink_concrete_roofs/pink_concrete_attic_roof',
        'mcw_tfc_aio:roofs/pink_terracotta_roofs/pink_terracotta_attic_roof',
        'mcw_tfc_aio:roofs/purple_concrete_roofs/purple_concrete_attic_roof',
        'mcw_tfc_aio:roofs/purple_terracotta_roofs/purple_terracotta_attic_roof',
        'mcw_tfc_aio:roofs/red_concrete_roofs/red_concrete_attic_roof',
        'mcw_tfc_aio:roofs/red_terracotta_roofs/red_terracotta_attic_roof',
        'mcw_tfc_aio:roofs/rosewood_roofs/rosewood_attic_roof',
        'mcw_tfc_aio:roofs/rosewood_roofs/rosewood_planks_attic_roof',
        'mcw_tfc_aio:roofs/sequoia_roofs/sequoia_attic_roof',
        'mcw_tfc_aio:roofs/sequoia_roofs/sequoia_planks_attic_roof',
        'mcw_tfc_aio:roofs/spruce_roofs/spruce_attic_roof',
        'mcw_tfc_aio:roofs/spruce_roofs/spruce_planks_attic_roof',
        'mcw_tfc_aio:roofs/sycamore_roofs/sycamore_attic_roof',
        'mcw_tfc_aio:roofs/sycamore_roofs/sycamore_planks_attic_roof',
        'mcw_tfc_aio:roofs/thatch_roofs/thatch_attic_roof',
        'mcw_tfc_aio:roofs/thatch2_roofs/thatch2_attic_roof',
        'mcw_tfc_aio:roofs/white_cedar_roofs/white_cedar_attic_roof',
        'mcw_tfc_aio:roofs/white_cedar_roofs/white_cedar_planks_attic_roof',
        'mcw_tfc_aio:roofs/white_concrete_roofs/white_concrete_attic_roof',
        'mcw_tfc_aio:roofs/white_roofs/white_attic_roof',
        'mcw_tfc_aio:roofs/white_terracotta_roofs/white_terracotta_attic_roof',
        'mcw_tfc_aio:roofs/willow_roofs/willow_attic_roof',
        'mcw_tfc_aio:roofs/willow_roofs/willow_planks_attic_roof',
        'mcw_tfc_aio:roofs/yellow_concrete_roofs/yellow_concrete_attic_roof',
        'mcw_tfc_aio:roofs/yellow_terracotta_roofs/yellow_terracotta_attic_roof',
    ]);

}