base_url: "https://api.crowdin.com"
base_path: "../../kubejs/assets"

project_id_env: "CROWDIN_ID"
api_token_env: "CROWDIN_TOKEN"

preserve_hierarchy: true

files:
  - source: "/tfc/patchouli_books/field_guide/en_us/**/*.json"
    translation: "/tfc/patchouli_books/field_guide/%locale_with_underscore%/**/%original_file_name%"
    update_option: "update_as_unapproved"

    ignore: [
      "/**/tfg_ores/*_index.json"
    ]

