base_url: "https://terrafirmagreg.api.crowdin.com"
base_path: "../../kubejs/assets"

project_id_env: "CROWDIN_ID"
api_token_env: "CROWDIN_TOKEN"

preserve_hierarchy: true

files:
  - source: "/*/lang/en_us.json"
    translation: "/%original_path%/%locale_with_underscore%.%file_extension%"
    update_option: "update_as_unapproved"
