// Priority: 0
"use strict";

const registerTFGCrops = (event) => {
	const $FarmlandBlockEntity = Java.loadClass("net.dries007.tfc.common.blockentities.FarmlandBlockEntity")

	//#region Earth Crops

	// Sunflower
	event.create('tfg:sunflower', 'tfc:double_crop')
		.translationKey('block.tfg.sunflower')
		.mapColor('plant')
		.soundType('crop')
		.nutrient($FarmlandBlockEntity.NutrientType.NITROGEN)
		.stages(4)
		.doubleStages(2)
		.hardness(0.4)
		.growthModifier(0.8)
		.tagBlock('minecraft:mineable/hoe')
		.tagBlock('minecraft:flowers')
		.productItem(product => {
			product.texture('tfg:item/sunflower_product')
		})
		.seedItem(seed => {
			seed.texture('tfg:item/sunflower_seed')
		})
		.deadBlock(dead => {
			dead.hardness(0.2)
			dead.soundType('crop')
			dead.tagBlock('minecraft:mineable/hoe')
		})
	event.create('tfg:sunflower_wild', 'tfc:wild_crop')
		.type('double')
		.soundType('crop')
		.seeds('tfg:sunflower_seeds')
		.food('tfg:sunflower_product')
		.hardness(0.2)
		.tagBoth('tfc:wild_crops')
		.tagBlock('minecraft:mineable/hoe')
		.tagBlock('minecraft:flowers')
		.tagBlock('tfc:can_be_snow_piled')
		.tagItem('c:hidden_from_recipe_viewers')

	// Rapeseed/ Canola
	event.create('tfg:rapeseed', 'tfc:double_crop')
		.mapColor('plant')
		.translationKey('block.tfg.rapeseed')
		.soundType('crop')
		.nutrient($FarmlandBlockEntity.NutrientType.PHOSPHOROUS)
		.stages(3)
		.doubleStages(3)
		.hardness(0.4)
		.tagBlock('minecraft:mineable/hoe')
		.tagBlock('minecraft:flowers')
		.deadBlock(dead => {
			dead.hardness(0.2)
			dead.soundType('crop')
			dead.tagBlock('minecraft:mineable/hoe')
		})
	event.create('tfg:rapeseed_wild', 'tfc:wild_crop')
		.type('double')
		.soundType('crop')
		.seeds('tfg:rapeseed_seeds')
		.food('tfg:rapeseed_product')
		.hardness(0.2)
		.tagBoth('tfc:wild_crops')
		.tagBlock('minecraft:mineable/hoe')
		.tagBlock('minecraft:flowers')
		.tagBlock('tfc:can_be_snow_piled')
		.tagItem('c:hidden_from_recipe_viewers')

	// Flax
	event.create('tfg:flax', 'tfc:double_crop')
		.mapColor('plant')
		.translationKey('block.tfg.flax')
		.soundType('crop')
		.nutrient($FarmlandBlockEntity.NutrientType.NITROGEN)
		.stages(5)
		.doubleStages(3)
		.hardness(0.4)
		.growthModifier(1.2)
		.expiryModifier(1.2)
		.tagBlock('minecraft:mineable/hoe')
		.productItem(product => {
			product.texture('tfg:item/flax_product')
			product.tag('tfc:scrapable')
		})
		.seedItem(seed => {
			seed.texture('tfg:item/flax_seed')
		})
		.deadBlock(dead => {
			dead.hardness(0.2)
			dead.soundType('crop')
			dead.tagBlock('minecraft:mineable/hoe')
		})
	event.create('tfg:flax_wild', 'tfc:wild_crop')
		.type('double')
		.soundType('crop')
		.seeds('tfg:flax_seeds')
		.food('tfg:flax_product')
		.hardness(0.2)
		.tagBoth('tfc:wild_crops')
		.tagBlock('minecraft:mineable/hoe')
		.tagBlock('tfc:can_be_snow_piled')
		.tagItem('c:hidden_from_recipe_viewers')

	// Lentils
	event.create('tfg:lentil', 'tfc:crop')
		.mapColor('plant')
		.soundType('crop')
		.nutrient($FarmlandBlockEntity.NutrientType.PHOSPHOROUS)
		.stages(5)
		.hardness(0.4)
		.tagBlock('minecraft:mineable/hoe')
		.productItem(product => {
			product.food(food => {
				food.hunger(4)
				food.saturation(1)
			})
		})
		.deadBlock(dead => {
			dead.hardness(0.2)
			dead.soundType('crop')
			dead.tagBlock('minecraft:mineable/hoe')
			dead.box(2, 0, 2, 14, 6, 14)
		})
	event.create('tfg:lentil_wild', 'tfc:wild_crop')
		.type('default')
		.soundType('crop')
		.seeds('tfg:lentil_seeds')
		.food('tfg:lentil_product')
		.hardness(0.2)
		.tagBoth('tfc:wild_crops')
		.tagBlock('minecraft:mineable/hoe')
		.tagBlock('tfc:can_be_snow_piled')
		.tagItem('c:hidden_from_recipe_viewers')

	// Radish
	event.create('tfg:radish', 'tfc:crop')
		.mapColor('plant')
		.soundType('crop')
		.nutrient($FarmlandBlockEntity.NutrientType.POTASSIUM)
		.stages(5)
		.hardness(0.4)
		.tagBlock('minecraft:mineable/hoe')
		.productItem(product => {
			product.food(food => {
				food.hunger(4)
				food.saturation(1)
			})
		})
		.deadBlock(dead => {
			dead.hardness(0.2)
			dead.soundType('crop')
			dead.tagBlock('minecraft:mineable/hoe')
			dead.box(2, 0, 2, 14, 6, 14)
		})
	event.create('tfg:radish_wild', 'tfc:wild_crop')
		.type('default')
		.soundType('crop')
		.seeds('tfg:radish_seeds')
		.food('tfg:radish_product')
		.hardness(0.2)
		.tagBoth('tfc:wild_crops')
		.tagBlock('minecraft:mineable/hoe')
		.tagBlock('tfc:can_be_snow_piled')
		.tagItem('c:hidden_from_recipe_viewers')

	// Cucumber
	event.create('tfg:cucumber', 'tfc:double_crop')
		.mapColor('plant')
		.soundType('crop')
		.nutrient($FarmlandBlockEntity.NutrientType.NITROGEN)
		.stages(3)
		.doubleStages(2)
		.hardness(0.4)
		.tagBlock('minecraft:mineable/hoe')
        .requiresStick(true)
		.productItem(product => {
			product.food(food => {
				food.hunger(4)
				food.saturation(1)
			})
		})
        .deadBlock(dead => {
            dead.models((variant, m) => {
                if (variant.stick()) {
                    m.parent('tfc:block/crop/stick');
                }
            })
        })
	event.create('tfg:cucumber_wild', 'tfc:wild_crop')
		.type('double')
		.soundType('crop')
		.seeds('tfg:cucumber_seeds')
		.food('tfg:cucumber_product')
		.hardness(0.2)
		.tagBoth('tfc:wild_crops')
		.tagBlock('minecraft:mineable/hoe')
		.tagBlock('minecraft:flowers')
		.tagBlock('tfc:can_be_snow_piled')
		.tagItem('c:hidden_from_recipe_viewers')

	//#endregion
	//#region Beneath Crops

	// Peanut
	event.create('tfg:peanut', 'tfc:crop')
		.mapColor('plant')
		.soundType('crop')
		.nutrient($FarmlandBlockEntity.NutrientType.POTASSIUM)
		.stages(5)
		.hardness(0.4)
		.tagBlock('minecraft:mineable/hoe')
		.productItem(product => {
			product.food(food => {
				food.hunger(4)
				food.saturation(1)
			})
		})
		.deadBlock(dead => {
			dead.hardness(0.2)
			dead.soundType('crop')
			dead.tagBlock('minecraft:mineable/hoe')
			dead.box(2, 0, 2, 14, 6, 14)
		})
	event.create('tfg:peanut_wild', 'tfc:wild_crop')
		.type('default')
		.soundType('crop')
		.seeds('tfg:peanut_seeds')
		.food('tfg:peanut_product')
		.hardness(0.2)
		.tagBoth('tfc:wild_crops')
		.tagBlock('minecraft:mineable/hoe')
		.tagBlock('tfc:can_be_snow_piled')
		.tagItem('c:hidden_from_recipe_viewers')

	// Cassava
	event.create('tfg:cassava', 'tfc:crop')
		.mapColor('plant')
		.soundType('crop')
		.nutrient($FarmlandBlockEntity.NutrientType.NITROGEN)
		.stages(5)
		.hardness(0.4)
		.tagBlock('minecraft:mineable/hoe')
		.productItem(product => {
			product.food(food => {
				food.hunger(4)
				food.saturation(1)
			})
		})
		.deadBlock(dead => {
			dead.hardness(0.2)
			dead.soundType('crop')
			dead.tagBlock('minecraft:mineable/hoe')
			dead.box(2, 0, 2, 14, 6, 14)
		})
	event.create('tfg:cassava_wild', 'tfc:wild_crop')
		.type('default')
		.soundType('crop')
		.seeds('tfg:cassava_seeds')
		.food('tfg:cassava_product')
		.hardness(0.2)
		.tagBoth('tfc:wild_crops')
		.tagBlock('minecraft:mineable/hoe')
		.tagBlock('tfc:can_be_snow_piled')
		.tagItem('c:hidden_from_recipe_viewers')

	// Beans
	event.create('tfg:beans', 'tfc:crop')
		.mapColor('plant')
		.soundType('crop')
		.nutrient($FarmlandBlockEntity.NutrientType.POTASSIUM)
		.stages(5)
		.hardness(0.4)
		.tagBlock('minecraft:mineable/hoe')
		.productItem(product => {
			product.food(food => {
				food.hunger(4)
				food.saturation(1)
			})
		})
		.deadBlock(dead => {
			dead.hardness(0.2)
			dead.soundType('crop')
			dead.tagBlock('minecraft:mineable/hoe')
			dead.box(2, 0, 2, 14, 6, 14)
		})
	event.create('tfg:beans_wild', 'tfc:wild_crop')
		.type('default')
		.soundType('crop')
		.seeds('tfg:beans_seeds')
		.food('tfg:beans_product')
		.hardness(0.2)
		.tagBoth('tfc:wild_crops')
		.tagBlock('minecraft:mineable/hoe')
		.tagBlock('tfc:can_be_snow_piled')
		.tagItem('c:hidden_from_recipe_viewers')

	// Ghost Pepper
	event.create('tfg:ghost_pepper', 'tfc:crop')
		.mapColor('plant')
		.soundType('crop')
		.nutrient($FarmlandBlockEntity.NutrientType.NITROGEN)
		.stages(5)
		.hardness(0.4)
		.tagBlock('minecraft:mineable/hoe')
		.existingProductItem('beneath:ghost_pepper')
		.deadBlock(dead => {
			dead.hardness(0.2)
			dead.soundType('crop')
			dead.tagBlock('minecraft:mineable/hoe')
			dead.box(2, 0, 2, 14, 6, 14)
		})
	event.create('tfg:ghost_pepper_wild', 'tfc:wild_crop')
		.type('default')
		.soundType('crop')
		.seeds('tfg:ghost_pepper_seeds')
		.food('beneath:ghost_pepper')
		.hardness(0.2)
		.tagBoth('tfc:wild_crops')
		.tagBlock('minecraft:mineable/hoe')
		.tagBlock('tfc:can_be_snow_piled')
		.tagItem('c:hidden_from_recipe_viewers')

	//#endregion
	//#region Mars Crops

	// Amber Root
	event.create('betterend:amber_root', 'tfc:crop')
		.mapColor('color_orange')
		.soundType('crop')
		.nutrient($FarmlandBlockEntity.NutrientType.PHOSPHOROUS)
		.stages(3)
		.hardness(0.4)
		.tagBlock('minecraft:mineable/hoe')
		.productItem(product => {
			product.food(food => {
				food.hunger(4)
				food.saturation(1)
			})
		})
		.deadBlock(dead => {
			dead.hardness(0.2)
			dead.soundType('crop')
			dead.tagBlock('minecraft:mineable/hoe')
			dead.box(2, 0, 2, 14, 6, 14)
		})
	event.create('betterend:amber_root_wild', 'tfc:wild_crop')
		.type('default')
		.soundType('crop')
		.seeds('betterend:amber_root_seeds')
		.food('betterend:amber_root_product')
		.hardness(0.2)
		.tagBoth('tfc:wild_crops')
		.tagBlock('minecraft:mineable/hoe')
		.tagBlock('tfc:can_be_snow_piled')
		.tagItem('c:hidden_from_recipe_viewers')

	// Blossom Berry
	event.create('betterend:blossom_berry', 'tfc:crop')
		.mapColor('color_pink')
		.soundType('crop')
		.nutrient($FarmlandBlockEntity.NutrientType.POTASSIUM)
		.stages(3)
		.hardness(0.4)
		.tagBlock('minecraft:mineable/hoe')
		.productItem(product => {
			product.food(food => {
				food.hunger(5)
				food.saturation(1)
			})
		})
		.deadBlock(dead => {
			dead.hardness(0.2)
			dead.soundType('crop')
			dead.tagBlock('minecraft:mineable/hoe')
			dead.box(2, 0, 2, 14, 9, 14)
		})
	event.create('betterend:blossom_berry_wild', 'tfc:wild_crop')
		.type('default')
		.soundType('crop')
		.seeds('betterend:blossom_berry_seeds')
		.food('betterend:blossom_berry_product')
		.hardness(0.2)
		.tagBoth('tfc:wild_crops')
		.tagBlock('minecraft:mineable/hoe')
		.tagBlock('tfc:can_be_snow_piled')
		.tagItem('c:hidden_from_recipe_viewers')

	// Cave Pumpkin
	event.create('betterend:cave_pumpkin')
		.mapColor('color_red')
		.soundType('cherry_wood')
		.tagBlock('minecraft:mineable/axe')
		.tagBlock('minecraft:mineable/hoe')
		.mapColor('color_red')
		.lightLevel(0.85)
		.requiresTool(false)
		.fullBlock(false)
		.opaque(false)
		.notSolid()

	event.create('betterend:cave_pumpkin_plant', 'tfc:spreading_crop')
		.mapColor('plant')
		.soundType('crop')
		.nutrient($FarmlandBlockEntity.NutrientType.NITROGEN)
		.stages(3)
		.hardness(0.4)
		.tagBlock('minecraft:mineable/hoe')
		.deadBlock(dead => {
			dead.hardness(0.2)
			dead.soundType('crop')
			dead.tagBlock('minecraft:mineable/hoe')
			dead.box(2, 0, 2, 14, 9, 14)
		})
		.fruitBlock('betterend:cave_pumpkin')
		.textureAt(0, "betterend:block/cave_pumpkin_stem_0")
		.textureAt(1, "betterend:block/cave_pumpkin_stem_1")
		.textureAt(2, "betterend:block/cave_pumpkin_stem_2")
		.textureAt(3, "betterend:block/cave_pumpkin_stem_3")
		.texture("side", "betterend:block/cave_pumpkin_stem_3_side")
	event.create('betterend:cave_pumpkin_wild', 'tfc:wild_crop')
		.type('spreading')
		.soundType('crop')
		.spreadingFruitBlock('betterend:cave_pumpkin')
		.seeds('betterend:cave_pumpkin_plant_seeds')
		.hardness(0.2)
		.tagBoth('tfc:wild_crops')
		.tagBlock('minecraft:mineable/hoe')
		.tagBlock('tfc:can_be_snow_piled')
		.tagItem('c:hidden_from_recipe_viewers')

	// Chorus Mushroom
	event.create('betterend:chorus_mushroom', 'tfc:crop')
		.mapColor('color_purple')
		.translationKey('block.betterend.chorus_mushroom')
		.soundType('nether_wart')
		.nutrient($FarmlandBlockEntity.NutrientType.PHOSPHOROUS)
		.stages(3)
		.hardness(0.4)
		.tagBlock('minecraft:mineable/hoe')
		.box(2, 0, 2, 14, 4, 14)
		.productItem(product => {
			product.food(food => {
				food.hunger(2)
				food.saturation(1)
				food.effect('minecraft:hunger', 30 * 20, 0, 1)
				food.effect('minecraft:weakness', 30 * 20, 0, 1)
			})
		})
		.deadBlock(dead => {
			dead.hardness(0.2)
			dead.box(2, 0, 2, 14, 4, 14)
			dead.soundType('nether_wart')
			dead.tagBlock('minecraft:mineable/hoe')
		})
    event.create('betterend:chorus_mushroom_wild', 'tfc:wild_crop')
        .type('default')
		.box(2, 0, 2, 14, 4, 14)
		.translationKey('block.betterend.chorus_mushroom_wild')
		.soundType('nether_wart')
		.seeds('betterend:chorus_mushroom_seeds')
		.food('betterend:chorus_mushroom_product')
		.hardness(0.2)
		.tagBoth('tfc:wild_crops')
		.tagBlock('minecraft:mineable/hoe')
		.tagBlock('tfc:can_be_snow_piled')
		.tagItem('c:hidden_from_recipe_viewers')

	// Shadow Berry
	event.create('betterend:shadow_berry', 'tfc:crop')
		.mapColor('color_blue')
		.soundType('crop')
		.box(2, 0, 2, 14, 3, 14)
		.nutrient($FarmlandBlockEntity.NutrientType.POTASSIUM)
		.stages(3)
		.hardness(0.4)
		.tagBlock('minecraft:mineable/hoe')
		.productItem(product => {
			product.food(food => {
				food.hunger(5)
				food.saturation(1)
				food.effect('minecraft:poison', 5 * 20, 0, 1)
			})
		})
		.deadBlock(dead => {
			dead.hardness(0.2)
			dead.soundType('crop')
			dead.tagBlock('minecraft:mineable/hoe')
			dead.box(2, 0, 2, 14, 3, 14)
		})
    event.create('betterend:shadow_berry_wild', 'tfc:wild_crop')
        .type('default')
		.box(2, 0, 2, 14, 3, 14)
		.soundType('crop')
		.seeds('betterend:shadow_berry_seeds')
		.food('betterend:shadow_berry_product')
		.hardness(0.2)
		.tagBoth('tfc:wild_crops')
		.tagBlock('minecraft:mineable/hoe')
		.tagBlock('tfc:can_be_snow_piled')
		.tagItem('c:hidden_from_recipe_viewers')

	// Bolux Mushroom
	event.create('betterend:bolux_mushroom', 'tfc:crop')
		.mapColor('color_orange')
		.soundType('nether_wart')
		.box(2, 0, 2, 14, 5, 14)
		.nutrient($FarmlandBlockEntity.NutrientType.PHOSPHOROUS)
		.stages(3)
		.hardness(0.4)
		.tagBlock('minecraft:mineable/hoe')
		.productItem(product => {
			product.food(food => {
				food.hunger(2)
				food.saturation(1)
				food.effect('tfc:thirst', 60 * 20, 0, 1)
				food.effect('minecraft:nausea', 30 * 20, 0, 1)
			})
		})
		.deadBlock(dead => {
			dead.hardness(0.2)
			dead.soundType('nether_wart')
			dead.tagBlock('minecraft:mineable/hoe')
			dead.box(2, 0, 2, 14, 5, 14)
		})
    event.create('betterend:bolux_mushroom_wild', 'tfc:wild_crop')
		.box(2, 0, 2, 14, 5, 14)
		.type('default')
		.soundType('nether_wart')
		.seeds('betterend:bolux_mushroom_seeds')
		.food('betterend:bolux_mushroom_product')
		.hardness(0.2)
		.tagBoth('tfc:wild_crops')
		.tagBlock('minecraft:mineable/hoe')
		.tagBlock('tfc:can_be_snow_piled')
		.tagItem('c:hidden_from_recipe_viewers')

	//#endregion
}