"use strict";

function registerTFGNetherBlocks(event) {
	const SHAPES = ['stairs', 'slab', 'wall']

	// #region Raw Stones
	SHAPES.forEach(shape => {
		event.create(`tfg:rock/deepslate_${shape}`, shape)
			.soundType('deepslate')
			.textureAll('minecraft:block/deepslate')
			.tagBoth(`minecraft:${shape}`)
			.tagBoth(`tfg:rock_${shape}`)
			.tagBoth('tfc:metamorphic_items')
			.mapColor('terracotta_grey')
			.tagBlock('minecraft:mineable/pickaxe')
			.fullBlock(true)
			.opaque(true)
	})

	// #endregion Raw Stones

	// #region Hardened Stones
	event.create('tfg:rock/hardened_deepslate')
		.soundType('deepslate')
		.property(BlockProperties.AXIS)
		.requiresTool(true)
		.item(item => {
			item.modelJson({ parent: 'minecraft:item/deepslate' })
		})
		.tagBlock('tfc:can_carve')
		.tagBoth('forge:stone')
		.tagBoth('tfc:rock/hardened')
		.tagBoth('tfc:metamorphic_items')
		.tagBlock('minecraft:mineable/pickaxe')
		.mapColor('terracotta_grey')
		.fullBlock(true)
		.opaque(true)

	event.create('tfg:rock/hardened_blackstone')
		.stoneSoundType()
		.requiresTool(true)
		.item(item => {
			item.modelJson({ parent: 'minecraft:item/blackstone' })
		})
		.tagBlock('tfc:can_carve')
		.tagBoth('forge:stone')
		.tagBoth('tfc:rock/hardened')
		.tagBoth('tfc:igneous_intrusive_items')
		.mapColor('color_black')
		.tagBlock('minecraft:mineable/pickaxe')
		.fullBlock(true)
		.opaque(true)

	event.create('tfg:rock/hardened_dripstone')
		.soundType('dripstone_block')
		.stoneSoundType()
		.requiresTool(true)
		.item(item => {
			item.modelJson({ parent: 'minecraft:item/dripstone_block' })
		})
		.tagBlock('tfc:can_carve')
		.tagBoth('forge:stone')
		.tagBoth('tfc:rock/hardened')
		.tagBoth('tfc:sedimentary_items')
		.tagBlock('minecraft:mineable/pickaxe')
		.mapColor('terracotta')
		.fullBlock(true)
		.opaque(true)

	// #endregion Hardened stones
	 
	// #region Spikes
	event.create('tfg:spike/dripstone_spike', 'tfc:rock_spike')
		.textureAll('minecraft:block/dripstone_block')
		.soundType('dripstone_block')
		.tagBoth('tfc:sedimentary_items')
		.hardness(0.8)
		.resistance(0.8)
		.requiresTool(true)
		.tagBlock('minecraft:mineable/pickaxe')

	event.create('tfg:spike/deepslate_spike', 'tfc:rock_spike')
		.textureAll('minecraft:block/deepslate')
		.soundType('deepslate')
		.tagBoth('tfc:metamorphic_items')
		.hardness(0.8)
		.resistance(0.8)
		.requiresTool(true)
		.tagBlock('minecraft:mineable/pickaxe')

	event.create('tfg:spike/blackstone_spike', 'tfc:rock_spike')
		.textureAll('minecraft:block/blackstone')
		.stoneSoundType()
		.tagBoth('tfc:igneous_intrusive_items')
		.hardness(0.8)
		.resistance(0.8)
		.requiresTool(true)
		.tagBlock('minecraft:mineable/pickaxe')

	// #endregion Spikes

  	// #region Loose rocks
	event.create('tfg:loose/deepslate', 'tfc:loose_rock')
		.itemTexture('tfg:item/loose/deepslate')
		.rockTypeModel('metamorphic')
		.soundType('deepslate')
		.translationKey("block.tfg.loose.deepslate")
		.tagBlock('tfc:loose_rocks')
		.tagItem('tfc:any_knapping')
		.tagItem('tfc:rock_knapping')
		.tagItem('tfc:metamorphic_rock')
		.tagItem("rnr:loose_rock_items")

	event.create('tfg:loose/dripstone', 'tfc:loose_rock')
		.itemTexture('tfg:item/loose/dripstone')
		.rockTypeModel('sedimentary')
		.soundType('dripstone_block')
		.translationKey("block.tfg.loose.dripstone")
		.tagBlock('tfc:loose_rocks')
		.tagItem('tfc:any_knapping')
		.tagItem('tfc:rock_knapping')
		.tagItem('tfc:sedimentary_rock')
		.tagItem("rnr:loose_rock_items")

	event.create('tfg:loose/crackrack', 'tfc:loose_rock')
		.itemTexture('tfg:item/loose/crackrack')
		.rockTypeModel('igneous_intrusive')
		.soundType('basalt')
		.translationKey("block.tfg.loose.crackrack")
		.tagBlock('tfc:loose_rocks')
		.tagItem('tfc:any_knapping')
		.tagItem('tfc:rock_knapping')
		.tagItem('tfc:igneous_intrusive_rock')
		.tagItem("rnr:loose_rock_items")
	
	// #endregion Loose rocks
	
	// #region Cobblestones
	
	// Deepslate
	event.create('tfg:rock/mossy_cobble_deepslate')
		.soundType('stone')
		.tagBoth('forge:cobblestone')
		.tagBoth('forge:cobblestone/normal')
		.tagBoth('tfc:metamorphic_items')
		.mapColor('terracotta_grey')
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('tfc:can_landslide')
		.fullBlock(true)
		.opaque(true)

	SHAPES.forEach(shape => {
		event.create(`tfg:rock/mossy_cobble_deepslate_${shape}`, shape)
			.soundType('deepslate')
			.tagBoth(`minecraft:${shape}`)
			.tagBoth(`tfg:rock_${shape}`)
			.tagBoth('tfc:metamorphic_items')
			.mapColor('terracotta_grey')
			.tagBlock('minecraft:mineable/pickaxe')
			.fullBlock(true)
			.opaque(true)
	})
	
	event.create('tfg:rock/cobble_blackstone')
		.soundType('stone')
		.tagBoth('forge:cobblestone')
		.tagBoth('forge:cobblestone/normal')
		.tagBoth('tfc:igneous_intrusive_items')
		.mapColor('color_black')
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('tfc:can_landslide')
		.fullBlock(true)
		.opaque(true)
	
	// Blackstone
	event.create('tfg:rock/mossy_cobble_blackstone')
		.soundType('stone')
		.tagBoth('forge:cobblestone')
		.tagBoth('forge:cobblestone/normal')
		.tagBoth('tfc:igneous_intrusive_items')
		.mapColor('color_black')
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('tfc:can_landslide')
		.fullBlock(true)
		.opaque(true)
	
	event.create('tfg:rock/cobble_dripstone')
		.soundType('dripstone_block')
		.tagBoth('forge:cobblestone')
		.tagBoth('forge:cobblestone/normal')
		.tagBoth('tfc:sedimentary_items')
		.mapColor('terracotta')
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('tfc:can_landslide')
		.fullBlock(true)
		.opaque(true)
	
	event.create('tfg:rock/mossy_cobble_dripstone')
		.soundType('dripstone_block')
		.tagBoth('forge:cobblestone')
		.tagBoth('forge:cobblestone/normal')
		.tagBoth('tfc:sedimentary_items')
		.mapColor('terracotta')
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('tfc:can_landslide')
		.fullBlock(true)
		.opaque(true)
	
	event.create('tfg:rock/cobble_crackrack')
		.soundType('netherrack')
		.tagBoth('forge:cobblestone')
		.tagBoth('forge:cobblestone/normal')
		.tagBoth('tfc:igneous_intrusive_items')
		.mapColor('crimson_stem')
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('tfc:can_landslide')
		.fullBlock(true)
		.opaque(true)
	
	event.create('tfg:rock/mossy_cobble_crackrack')
		.soundType('netherrack')
		.tagBoth('forge:cobblestone')
		.tagBoth('forge:cobblestone/normal')
		.tagBoth('tfc:igneous_intrusive_items')
		.mapColor('crimson_stem')
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('tfc:can_landslide')
		.fullBlock(true)
		.opaque(true)
	
	
	// #region Smooth (Polished/Cut) Stones

	event.create('tfg:rock/polished_crackrack')
		.soundType('basalt')
		.tagBoth('forge:smooth_stone')
		.tagBoth('tfc:igneous_intrusive_items')
		.tagBoth('tfc:rock/smooth')
		.mapColor('crimson_stem')
		.tagBlock('minecraft:mineable/pickaxe')
		.fullBlock(true)
		.opaque(true)
	
	// #endregion Smooth (Polished/Cut) Stones

	// #region Gravels
	event.create('tfg:rock/gravel_deepslate')
		.soundType('gravel')
		.tagBoth('forge:gravel')
		.tagBoth('tfc:rock/gravel')
		.tagBoth('tfc:metamorphic_items')
		.mapColor('terracotta_grey')
		.tagBlock('minecraft:mineable/shovel')
		.tagBlock('tfc:can_landslide')
		.fullBlock(true)
		.opaque(true)

	event.create('tfg:rock/gravel_blackstone')
		.soundType('gravel')
		.tagBoth('forge:gravel')
		.tagBoth('tfc:rock/gravel')
		.tagBoth('tfc:igneous_intrusive_items')
		.mapColor('color_black')
		.tagBlock('minecraft:mineable/shovel')
		.tagBlock('tfc:can_landslide')
		.fullBlock(true)
		.opaque(true)

	event.create('tfg:rock/gravel_dripstone')
		.soundType('gravel')
		.tagBoth('forge:gravel')
		.tagBoth('tfc:rock/gravel')
		.tagBoth('tfc:sedimentary_items')
		.mapColor('terracotta')
		.tagBlock('minecraft:mineable/shovel')
		.tagBlock('tfc:can_landslide')
		.fullBlock(true)
		.opaque(true)
	
	event.create('tfg:rock/gravel_crackrack')
		.soundType('gravel')
		.tagBoth('forge:gravel')
		.tagBoth('tfc:rock/gravel')
		.tagBoth('tfc:igneous_intrusive_items')
		.mapColor('crimson_stem')
		.tagBlock('minecraft:mineable/shovel')
		.tagBlock('tfc:can_landslide')
		.fullBlock(true)
		.opaque(true)
	
	// #endregion Gravels
	
	// #region Bricks / Decorative
	
	// Deepslate
	SHAPES.forEach(shape => {
		event.create(`tfg:rock/cracked_bricks_deepslate_${shape}`, shape)
			.soundType('deepslate')
			.textureAll('minecraft:block/cracked_deepslate_bricks')
			.tagBoth(`minecraft:${shape}`)
			.tagBoth(`tfg:brick_${shape}`)
			.tagBoth('tfc:metamorphic_items')
			.mapColor('terracotta_grey')
			.tagBlock('minecraft:mineable/pickaxe')
			.fullBlock(true)
			.opaque(true)
	})

	SHAPES.forEach(shape => {
		event.create(`tfg:rock/cracked_tiles_deepslate_${shape}`, shape)
			.soundType('deepslate')
			.textureAll('minecraft:block/cracked_deepslate_tiles')
			.tagBoth(`minecraft:${shape}`)
			.tagBoth(`tfg:brick_${shape}`)
			.tagBoth('tfc:metamorphic_items')
			.mapColor('terracotta_grey')
			.tagBlock('minecraft:mineable/pickaxe')
			.fullBlock(true)
			.opaque(true)
	})

	event.create('tfg:rock/mossy_bricks_deepslate')
		.soundType('deepslate')
		.tagBoth('minecraft:stone_bricks')
		.tagBoth('forge:stone_bricks')
		.tagBoth('tfc:rock/bricks')
		.tagBoth('tfc:metamorphic_items')
		.tagBoth('tfg:brick_index')
		.mapColor('terracotta_grey')
		.tagBlock('minecraft:mineable/pickaxe')
		.fullBlock(true)
		.opaque(true)
	
	SHAPES.forEach(shape => {
		event.create(`tfg:rock/mossy_bricks_deepslate_${shape}`, shape)
			.soundType('deepslate')
			.tagBoth(`minecraft:${shape}`)
			.tagBoth(`tfg:brick_${shape}`)
			.tagBoth('tfc:metamorphic_items')
			.mapColor('terracotta_grey')
			.tagBlock('minecraft:mineable/pickaxe')
			.fullBlock(true)
			.opaque(true)
	})
	
	// Blackstone
	event.create('tfg:rock/mossy_bricks_blackstone')
		.soundType('stone')
		.tagBoth('minecraft:stone_bricks')
		.tagBoth('forge:stone_bricks')
		.tagBoth('tfc:rock/bricks')
		.tagBoth('tfc:igneous_intrusive_items')
		.tagBoth('tfg:brick_index')
		.mapColor('color_black')
		.tagBlock('minecraft:mineable/pickaxe')
		.fullBlock(true)
		.opaque(true)
	
	event.create('tfg:rock/mossy_bricks_dripstone')
		.soundType('dripstone_block')
		.tagBoth('minecraft:stone_bricks')
		.tagBoth('forge:stone_bricks')
		.tagBoth('tfc:rock/bricks')
		.tagBoth('tfc:sedimentary_items')
		.tagBoth('tfg:brick_index')
		.mapColor('terracotta')
		.tagBlock('minecraft:mineable/pickaxe')
		.fullBlock(true)
		.opaque(true)
	
	event.create('tfg:rock/mossy_bricks_nether')
		.soundType('nether_bricks')
		.tagBoth('minecraft:stone_bricks')
		.tagBoth('forge:stone_bricks')
		.tagBoth('tfc:rock/bricks')
		.tagBoth('tfc:igneous_intrusive_items')
		.tagBoth('tfg:brick_index')
		.mapColor('nether')
		.tagBlock('minecraft:mineable/pickaxe')
		.fullBlock(true)
		.opaque(true)
	
	// #endregion Bricks / Decorative
	 
	// #region Plants
	event.create('tfg:mushroom_roots', 'tfg:decorative_plant')
		.soundType('nether_wart')
		.tagItem('tfc:plants')

	event.create('tfg:mushroom_sprouts', 'tfg:decorative_plant')
		.soundType('nether_wart')
		.tagItem('tfc:plants')

	event.create('tfg:charred_log')
		.fullBlock(true)
		.woodSoundType()
		.property(BlockProperties.AXIS)
		.tagBoth('minecraft:mineable/axe')
		.tagBoth('tfc:logs_that_log')
		.tagBoth('afc:logs_that_log')
		.tagBoth('minecraft:logs')
		.mapColor('black')
}