"use strict";

function registerTFGCasingBlocks(event) {

	event.create('tfg:bioculture_rotor_primary', 'tfg:active_particle_emitter')
		.translationKey('block.tfg.casings.bioculture_rotor_primary')
		.soundType('copper')
		.hardness(5)
		.resistance(6)
		.tagBlock('gtceu:mineable/pickaxe_or_wrench')
		.mapColor('color_light_gray')
		.activeParticles(a => a
			.range(1.6, 2, 1.6)
			.velocity(0, 0, 0)
			.particle('minecraft:landing_lava')
			.count(10)
			.forced(false))

	event.create('tfg:egh_planter', 'tfg:active_particle_emitter')
		.translationKey('block.tfg.egh_planter')
		.soundType('copper')
		.hardness(5)
		.resistance(6)
		.notSolid()
		.activeLight(12)
		.inactiveLight(0)
		.renderType('cutout')
		.tagBlock('gtceu:mineable/pickaxe_or_wrench')
		.mapColor('grass')
		.activeParticles(a => a
			.range(0.2, 0.0, 0.2)
			.velocity(0.0, 0.0, 0.0)
			.position(0.5, -0.1, 0.5)
			.count(1)
			.particle('minecraft:dripping_water')
			.forced(false))
		.hasTicker(true)
		.emitDelay(200)
		.tagBlock('tfc:tree_grows_on')
		.tagBlock('tfc:bush_plantable_on')
		.tagBlock('tfc:wild_crop_grows_on')
		.tagBlock('tfc:spreading_fruit_grows_on')
		.tagBlock('tfc:grass_plantable_on')
		.tagBlock('tfc:creeping_plantable_on')
		.tagBlock('minecraft:mushroom_grow_block')
		.tagBlock('minecraft:bamboo_plantable_on')
		.tagBoth('tfc:farmland');

	event.create('tfg:grow_light', 'tfg:active_particle_emitter')
		.translationKey('block.tfg.grow_light')
		.soundType('copper')
		.hardness(5)
		.resistance(6)
		.notSolid()
		.box(0, 12, 0, 16, 16, 16, true)
		.activeLight(12)
		.inactiveLight(0)
		.renderType('cutout')
		.tagBlock('gtceu:mineable/pickaxe_or_wrench')
		.mapColor('grass')
		.activeParticles(a => a
			.range(0.2, 0.0, 0.2)
			.velocity(0.0, 0.0, 0.0)
			.position(0.5, 0.5, 0.5)
			.count(1)
			.particle('minecraft:dripping_water')
			.forced(false))
		.hasTicker(true)
		.emitDelay(200);

	event.create('tfg:pisciculture_core', 'tfg:active_particle_emitter')
		.translationKey('block.tfg.pisciculture_core')
		.soundType('copper')
		.hardness(5)
		.resistance(6)
		.activeLight(12)
		.inactiveLight(0)
		.renderType('cutout')
		.tagBlock('gtceu:mineable/pickaxe_or_wrench')
		.activeParticles(a => a
			.particle('tfg:fish_school')
			.position(0.5, 1.5, 0.5)
			.range(0.0, 2.0, 0.0)
			.velocity(0.0, 0.0, 0.0)
			.count(5)
			.forced(false))
		.activeParticles(a => a
			.particle('minecraft:current_down')
			.position(0.0, 3.8, 0.0)
			.range(5.0, 0.0, 5.0)
			.velocity(0.0, 0.1, 0.0)
			.count(5)
			.forced(false))
		.activeParticles(a => a
			.particle('minecraft:current_down')
			.position(0.0, 3.8, 0.0)
			.range(0.5, 0.0, 0.5)
			.velocity(0.0, 0.1, 0.0)
			.count(5)
			.forced(false))
		.hasTicker(true)
		.emitDelay(20);
}