// priority: 0
"use strict";

function registerTFGIconSets(event) {

	event.create('tfc_borax').parent('rough')
	event.create('tfc_gypsum').parent('rough')
	event.create('tfc_graphite').parent('rough')
	event.create('tfc_saltpeter').parent('fine')
	event.create('tfc_sulfur').parent('fine')

	event.create('tfc_amethyst').parent('ruby')
	event.create('tfc_redstone').parent('fine')
	event.create('tfc_diamond').parent('diamond')
	event.create('tfc_emerald').parent('emerald')
	event.create('tfc_lapis').parent('lapis')
	event.create('tfc_opal').parent('opal')
	event.create('tfc_pyrite').parent('bright')
	event.create('tfc_ruby').parent('ruby')
	event.create('tfc_sapphire').parent('gem_horizontal')
	event.create('tfc_topaz').parent('gem_vertical')
	event.create('tfc_realgar').parent('emerald')
		
	event.create('tfc_bismuth').parent('bright')
	event.create('tfc_cassiterite').parent('bright')
	event.create('tfc_garnierite').parent('bright')
	event.create('tfc_hematite').parent('metallic')
	event.create('tfc_limonite').parent('metallic')
	event.create('tfc_magnetite').parent('dull')
	event.create('tfc_malachite').parent('shiny')
	event.create('tfc_copper').parent('bright')
	event.create('tfc_gold').parent('shiny')
	event.create('tfc_silver').parent('shiny')
	event.create('tfc_sphalerite').parent('dull')
	event.create('tfc_tetrahedrite').parent('dull')
	event.create('tfc_chromite').parent('dull')
		
	event.create('nether_quartz').parent('quartz')

    // Credits to Flare from the Cosmic Frontiers team
    event.create('chonky').parent('shiny')
}

function modifyTFGIconSets(event) {
	
    GTMaterials.Coal.setMaterialIconSet(GTMaterialIconSet.LIGNITE)
    GTMaterials.Borax.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_borax'))
    GTMaterials.Gypsum.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_gypsum'))
    GTMaterials.Graphite.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_graphite'))
    GTMaterials.Saltpeter.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_saltpeter'))
    GTMaterials.Sulfur.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_sulfur'))

    GTMaterials.Amethyst.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_amethyst'))
    GTMaterials.Redstone.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_redstone'))
    GTMaterials.Diamond.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_diamond'))
    GTMaterials.Emerald.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_emerald'))
    GTMaterials.Lapis.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_lapis'))
    GTMaterials.Opal.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_opal'))
    GTMaterials.Pyrite.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_pyrite'))
    GTMaterials.Ruby.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_ruby'))
    GTMaterials.Sapphire.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_sapphire'))
    GTMaterials.GreenSapphire.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_topaz'))
    GTMaterials.Topaz.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_topaz'))
    GTMaterials.BlueTopaz.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_sapphire'))
    
    GTMaterials.Bismuth.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_bismuth'))
    GTMaterials.Cassiterite.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_cassiterite'))
    GTMaterials.Tin.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_cassiterite'))
    GTMaterials.Garnierite.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_garnierite'))
    GTMaterials.Nickel.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_garnierite'))
    GTMaterials.Hematite.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_hematite'))
    GTMaterials.YellowLimonite.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_limonite'))
    GTMaterials.Magnetite.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_magnetite'))
    GTMaterials.Malachite.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_malachite'))
    GTMaterials.Copper.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_copper'))
    GTMaterials.Chalcocite.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_copper'))
    GTMaterials.Gold.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_gold'))
    GTMaterials.Silver.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_silver'))
    GTMaterials.Sphalerite.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_sphalerite'))
    GTMaterials.Tetrahedrite.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_tetrahedrite'))
    GTMaterials.Chalcopyrite.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_tetrahedrite'))
    GTMaterials.Chromite.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_chromite'))

    GTMaterials.NetherQuartz.setMaterialIconSet(GTMaterialIconSet.getByName('nether_quartz'))
    GTMaterials.CertusQuartz.setMaterialIconSet(GTMaterialIconSet.getByName('certus'))
    GTMaterials.Quartzite.setMaterialIconSet(GTMaterialIconSet.getByName('quartz'))
    GTMaterials.RedAlloy.setMaterialIconSet(GTMaterialIconSet.SHINY)
    GTMaterials.TinAlloy.setMaterialIconSet(GTMaterialIconSet.SHINY)
    GTMaterials.BismuthBronze.setMaterialIconSet(GTMaterialIconSet.BRIGHT)
    GTMaterials.Nickel.setMaterialIconSet(GTMaterialIconSet.BRIGHT)
    GTMaterials.BlackBronze.setMaterialIconSet(GTMaterialIconSet.SHINY)
    GTMaterials.Potin.setMaterialIconSet(GTMaterialIconSet.SHINY)
    GTMaterials.Cupronickel.setMaterialIconSet(GTMaterialIconSet.SHINY)
    
    GTMaterials.Aluminium.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_silver'))
    GTMaterials.Asbestos.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_gold'))
    GTMaterials.Almandine.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_realgar'))
    GTMaterials.Beryllium.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_copper'))
    GTMaterials.Cobalt.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_sphalerite'))
    GTMaterials.Cobaltite.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_borax'))
    GTMaterials.Lead.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_magnetite'))
    GTMaterials.Lazurite.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_ruby'))
    GTMaterials.Asbestos.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_graphite'))
    GTMaterials.Lithium.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_hematite'))
    GTMaterials.Galena.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_copper'))
    GTMaterials.Grossular.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_sapphire'))
    GTMaterials.Neodymium.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_limonite'))
    GTMaterials.Palladium.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_gold'))
    GTMaterials.Platinum.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_gold'))
    GTMaterials.Thorium.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_hematite'))
    GTMaterials.Goethite.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_silver'))
    GTMaterials.Calcite.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_borax'))
    GTMaterials.Cooperite.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_gold'))
    GTMaterials.Sodalite.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_opal'))
    GTMaterials.Molybdenum.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_chromite'))
    GTMaterials.Powellite.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_sphalerite'))
    GTMaterials.Pyrolusite.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_tetrahedrite'))
    GTMaterials.Apatite.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_opal'))
    GTMaterials.Pyrope.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_opal'))
    GTMaterials.Scheelite.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_saltpeter'))
    GTMaterials.Tantalite.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_saltpeter'))
    GTMaterials.Stibnite.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_sulfur'))
    GTMaterials.Tungstate.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_borax'))
    GTMaterials.Uraninite.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_limonite'))
    GTMaterials.Pitchblende.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_magnetite'))
    GTMaterials.VanadiumMagnetite.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_chromite'))
    GTMaterials.Wulfenite.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_borax'))
    GTMaterials.Realgar.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_realgar'))
    GTMaterials.Spodumene.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_gypsum'))
    GTMaterials.Mica.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_sulfur'))
    GTMaterials.Barite.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_graphite'))
    GTMaterials.Alunite.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_saltpeter'))
    GTMaterials.Pyrochlore.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_hematite'))
    GTMaterials.Olivine.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_topaz'))
    GTMaterials.GarnetYellow.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_realgar'))
    GTMaterials.Trona.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_pyrite'))
    GTMaterials.Zeolite.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_copper'))
    GTMaterials.Electrotine.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_garnierite'))
    GTMaterials.Bauxite.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_borax'))

    GTMaterials.Naquadah.setMaterialIconSet(GTMaterialIconSet.getByName('chonky'))
    GTMaterials.NaquadahEnriched.setMaterialIconSet(GTMaterialIconSet.getByName('chonky'))
    GTMaterials.Naquadria.setMaterialIconSet(GTMaterialIconSet.getByName('chonky'))
    GTMaterials.UraniumRhodiumDinaquadide.setMaterialIconSet(GTMaterialIconSet.getByName('chonky'))
    GTMaterials.EnrichedNaquadahTriniumEuropiumDuranide.setMaterialIconSet(GTMaterialIconSet.getByName('chonky'))
    GTMaterials.NaquadahAlloy.setMaterialIconSet(GTMaterialIconSet.getByName('chonky'))
    GTMaterials.Neutronium.setMaterialIconSet(GTMaterialIconSet.getByName('chonky'))
    GTMaterials.RutheniumTriniumAmericiumNeutronate.setMaterialIconSet(GTMaterialIconSet.getByName('chonky'))

    GTMaterials.Zirconium.setMaterialIconSet(GTMaterialIconSet.getByName('chonky'))
}