// priority: 0
"use strict";

function registerTFGIconSets(event) {

    let bladed = event.create('bladed').parent('lapis')
    event.create('botryoidal').parent('metallic')
    event.create('cubic_bright').parent('bright')
    event.create('cubic_shiny').parent('shiny')
    event.create('cubic_dull').parent('dull')
    event.create('cubic_ruby').parent('ruby')
    event.create('cubic_metallic').parent('metallic')
    event.create('cubic_gem_horizontal').parent('gem_horizontal')
    event.create('granular_opal').parent('opal')
    event.create('granular_fine').parent('fine')
    event.create('granular_lapis').parent('lapis')
    event.create('monoclinic_quartz').parent('quartz')
    event.create('monoclinic_dull').parent('dull')
    event.create('monoclinic_bright').parent('bright')
    event.create('monoclinic_ruby').parent('ruby')
    event.create('monoclinic_gem_horizontal').parent('gem_horizontal')
    event.create('monoclinic_diamond').parent('diamond')
    event.create('prismatic_ruby').parent('ruby')
    event.create('prismatic_gem_vertical').parent('gem_vertical')
    event.create('sheet_rough').parent('rough')
    event.create('sheet_metallic').parent('metallic')

    // Annoyingly, you can't create icon sets in kjs that use another kjs-created icon set as its parent
    event.create('tfc_borax').parent('rough')
	event.create('tfc_gypsum').parent('rough')
	event.create('tfc_graphite').parent('rough')
	event.create('tfc_saltpeter').parent('fine')
	event.create('tfc_sulfur').parent('fine')
	event.create('tfc_amethyst').parent('ruby')
	event.create('tfc_redstone').parent('sand')
	event.create('tfc_diamond').parent('diamond')
	event.create('tfc_emerald').parent('emerald')
	event.create('tfc_lapis').parent('lapis')
	event.create('tfc_opal').parent('opal')
	event.create('tfc_pyrite').parent('bright')
	event.create('tfc_ruby').parent('ruby')
	event.create('tfc_sapphire').parent('gem_horizontal')
	event.create('tfc_topaz').parent('gem_vertical')
		
	event.create('tfc_bismuth').parent('bright')
	event.create('tfc_cassiterite').parent('bright')
	event.create('tfc_garnierite').parent('bright')
	event.create('tfc_hematite').parent('metallic')
	event.create('tfc_limonite').parent('metallic')
	event.create('tfc_magnetite').parent('dull')
	event.create('tfc_malachite').parent('shiny')
	event.create('tfc_copper').parent('bright')
	event.create('tfc_gold').parent('shiny')
	event.create('tfc_silver').parent('shiny')
	event.create('tfc_sphalerite').parent('dull')
	event.create('tfc_tetrahedrite').parent('dull')
	event.create('tfc_chromite').parent('dull')
		
	event.create('nether_quartz').parent('quartz')
    event.create('anthracite').parent('lignite')


    // Looks like VI vanadium
    event.create('noodle').parent('metallic')
    // Looks like ad astra ostrum
    event.create('cereal_box').parent('bright')

    // Credits to Flare from the Cosmic Frontiers team
    event.create('chonky').parent('shiny')
}

function modifyTFGIconSets(event) {
	
    GTMaterials.Coal.setMaterialIconSet(GTMaterialIconSet.LIGNITE)
    GTMaterials.Borax.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_borax'))
    GTMaterials.Gypsum.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_gypsum'))
    GTMaterials.Graphite.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_graphite'))
    GTMaterials.Saltpeter.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_saltpeter'))
    GTMaterials.Sulfur.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_sulfur'))

    GTMaterials.Amethyst.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_amethyst'))
    GTMaterials.Redstone.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_redstone'))
    GTMaterials.Diamond.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_diamond'))
    GTMaterials.Emerald.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_emerald'))
    GTMaterials.Lapis.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_lapis'))
    GTMaterials.Opal.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_opal'))
    GTMaterials.Pyrite.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_pyrite'))
    GTMaterials.Ruby.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_ruby'))
    GTMaterials.Sapphire.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_sapphire'))
    GTMaterials.Topaz.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_topaz'))
    GTMaterials.BlueTopaz.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_topaz'))
    
    GTMaterials.Bismuth.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_bismuth'))
    GTMaterials.Cassiterite.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_cassiterite'))
    GTMaterials.Tin.setMaterialIconSet(GTMaterialIconSet.getByName('cubic_bright'))
    GTMaterials.Garnierite.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_garnierite'))
    GTMaterials.Nickel.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_garnierite'))
    GTMaterials.Hematite.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_hematite'))
    GTMaterials.Limonite.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_limonite'))
    GTMaterials.Magnetite.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_magnetite'))
    GTMaterials.Malachite.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_malachite'))
    GTMaterials.Copper.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_copper'))
    GTMaterials.Chalcocite.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_copper'))
    GTMaterials.Gold.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_gold'))
    GTMaterials.Silver.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_silver'))
    GTMaterials.Sphalerite.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_sphalerite'))
    GTMaterials.Tetrahedrite.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_tetrahedrite'))
    GTMaterials.Chalcopyrite.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_tetrahedrite'))
    GTMaterials.Chromite.setMaterialIconSet(GTMaterialIconSet.getByName('tfc_chromite'))

    GTMaterials.NetherQuartz.setMaterialIconSet(GTMaterialIconSet.getByName('nether_quartz'))
    GTMaterials.CertusQuartz.setMaterialIconSet(GTMaterialIconSet.CERTUS)
    GTMaterials.Quartzite.setMaterialIconSet(GTMaterialIconSet.getByName('quartz'))
    GTMaterials.RedAlloy.setMaterialIconSet(GTMaterialIconSet.SHINY)
    GTMaterials.TinAlloy.setMaterialIconSet(GTMaterialIconSet.SHINY)
    GTMaterials.BismuthBronze.setMaterialIconSet(GTMaterialIconSet.BRIGHT)
    GTMaterials.Nickel.setMaterialIconSet(GTMaterialIconSet.getByName('cubic_bright'))
    GTMaterials.BlackBronze.setMaterialIconSet(GTMaterialIconSet.SHINY)
    GTMaterials.Potin.setMaterialIconSet(GTMaterialIconSet.SHINY)
    GTMaterials.Cupronickel.setMaterialIconSet(GTMaterialIconSet.SHINY)
    GTMaterials.Osmium.setMaterialIconSet(GTMaterialIconSet.DULL)
    GTMaterials.Invar.setMaterialIconSet(GTMaterialIconSet.DULL)
    
    GTMaterials.Almandine.setMaterialIconSet(GTMaterialIconSet.getByName('cubic_shiny'))
    GTMaterials.Aluminium.setMaterialIconSet(GTMaterialIconSet.getByName('cubic_shiny'))
    GTMaterials.Alunite.setMaterialIconSet(GTMaterialIconSet.getByName('granular_fine'))
    GTMaterials.Apatite.setMaterialIconSet(GTMaterialIconSet.getByName('prismatic_ruby'))
    GTMaterials.Asbestos.setMaterialIconSet(GTMaterialIconSet.getByName('granular_fine'))
    GTMaterials.Barite.setMaterialIconSet(GTMaterialIconSet.getByName('bladed'))
    GTMaterials.BasalticMineralSand.setMaterialIconSet(GTMaterialIconSet.SAND)
    GTMaterials.Bastnasite.setMaterialIconSet(GTMaterialIconSet.getByName('prismatic_ruby'))
    GTMaterials.Bauxite.setMaterialIconSet(GTMaterialIconSet.getByName('granular_fine'))
    GTMaterials.Bentonite.setMaterialIconSet(GTMaterialIconSet.getByName('granular_fine'))
    GTMaterials.Beryllium.setMaterialIconSet(GTMaterialIconSet.getByName('monoclinic_bright'))
    GTMaterials.Bornite.setMaterialIconSet(GTMaterialIconSet.getByName('cubic_shiny'))
    GTMaterials.Calcite.setMaterialIconSet(GTMaterialIconSet.getByName('botryoidal'))
    GTMaterials.CassiteriteSand.setMaterialIconSet(GTMaterialIconSet.SAND)
    GTMaterials.Chalcocite.setMaterialIconSet(GTMaterialIconSet.getByName('monoclinic_dull'))
    GTMaterials.Chalcopyrite.setMaterialIconSet(GTMaterialIconSet.getByName('bladed'))
    GTMaterials.Cinnabar.setMaterialIconSet(GTMaterialIconSet.getByName('prismatic_gem_vertical'))
    GTMaterials.Cobalt.setMaterialIconSet(GTMaterialIconSet.getByName('monoclinic_dull'))
    GTMaterials.Cobaltite.setMaterialIconSet(GTMaterialIconSet.getByName('granular_fine'))
    GTMaterials.Cooperite.setMaterialIconSet(GTMaterialIconSet.getByName('botryoidal'))
    GTMaterials.Diatomite.setMaterialIconSet(GTMaterialIconSet.getByName('sheet_rough'))
    GTMaterials.Electrotine.setMaterialIconSet(GTMaterialIconSet.CERTUS)
    GTMaterials.FullersEarth.setMaterialIconSet(GTMaterialIconSet.FINE)
    GTMaterials.Galena.setMaterialIconSet(GTMaterialIconSet.getByName('cubic_shiny'))
    GTMaterials.GarnetSand.setMaterialIconSet(GTMaterialIconSet.SAND)
    GTMaterials.GarnetRed.setMaterialIconSet(GTMaterialIconSet.getByName('monoclinic_gem_horizontal'))
    GTMaterials.GarnetYellow.setMaterialIconSet(GTMaterialIconSet.getByName('monoclinic_gem_horizontal'))
    GTMaterials.GlauconiteSand.setMaterialIconSet(GTMaterialIconSet.SAND)
    GTMaterials.Goethite.setMaterialIconSet(GTMaterialIconSet.getByName('bladed'))
    GTMaterials.GraniticMineralSand.setMaterialIconSet(GTMaterialIconSet.SAND)
    GTMaterials.GreenSapphire.setMaterialIconSet(GTMaterialIconSet.getByName('monoclinic_gem_horizontal'))
    GTMaterials.Grossular.setMaterialIconSet(GTMaterialIconSet.getByName('monoclinic_ruby'))
    GTMaterials.Ilmenite.setMaterialIconSet(GTMaterialIconSet.getByName('monoclinic_gem_horizontal'))
    GTMaterials.Kyanite.setMaterialIconSet(GTMaterialIconSet.getByName('bladed'))
    GTMaterials.Lead.setMaterialIconSet(GTMaterialIconSet.getByName('cubic_dull'))
    GTMaterials.Lazurite.setMaterialIconSet(GTMaterialIconSet.getByName('cubic_ruby'))
    GTMaterials.Lepidolite.setMaterialIconSet(GTMaterialIconSet.getByName('sheet_rough'))
    GTMaterials.Lithium.setMaterialIconSet(GTMaterialIconSet.getByName('cubic_dull'))
    GTMaterials.Mica.setMaterialIconSet(GTMaterialIconSet.getByName('sheet_rough'))
    GTMaterials.Magnesite.setMaterialIconSet(GTMaterialIconSet.getByName('cubic_dull'))
    GTMaterials.Molybdenite.setMaterialIconSet(GTMaterialIconSet.getByName('cubic_dull'))
    GTMaterials.Molybdenum.setMaterialIconSet(GTMaterialIconSet.getByName('cubic_dull'))
    GTMaterials.Monazite.setMaterialIconSet(GTMaterialIconSet.getByName('monoclinic_diamond'))
    GTMaterials.Neodymium.setMaterialIconSet(GTMaterialIconSet.getByName('sheet_metallic'))
    GTMaterials.Oilsands.setMaterialIconSet(GTMaterialIconSet.SAND)
    GTMaterials.Olivine.setMaterialIconSet(GTMaterialIconSet.getByName('monoclinic_ruby'))
    GTMaterials.Palladium.setMaterialIconSet(GTMaterialIconSet.getByName('cubic_shiny'))
    GTMaterials.Pentlandite.setMaterialIconSet(GTMaterialIconSet.getByName('granular_lapis'))
    GTMaterials.Pitchblende.setMaterialIconSet(GTMaterialIconSet.getByName('botryoidal'))
    GTMaterials.Platinum.setMaterialIconSet(GTMaterialIconSet.getByName('cubic_shiny'))
    GTMaterials.Pollucite.setMaterialIconSet(GTMaterialIconSet.getByName('monoclinic_dull'))
    GTMaterials.Powellite.setMaterialIconSet(GTMaterialIconSet.getByName('sheet_metallic'))
    GTMaterials.Pyrochlore.setMaterialIconSet(GTMaterialIconSet.getByName('monoclinic_quartz'))
    GTMaterials.Pyrolusite.setMaterialIconSet(GTMaterialIconSet.getByName('botryoidal'))
    GTMaterials.Pyrope.setMaterialIconSet(GTMaterialIconSet.getByName('monoclinic_ruby'))
    GTMaterials.Realgar.setMaterialIconSet(GTMaterialIconSet.getByName('prismatic_ruby'))
    GTMaterials.RockSalt.setMaterialIconSet(GTMaterialIconSet.getByName('cubic_gem_horizontal')) // Sylvite
    GTMaterials.Salt.setMaterialIconSet(GTMaterialIconSet.getByName('cubic_gem_horizontal')) // Halite
    GTMaterials.Scheelite.setMaterialIconSet(GTMaterialIconSet.getByName('bladed'))
    GTMaterials.Soapstone.setMaterialIconSet(GTMaterialIconSet.getByName('monoclinic_gem_horizontal'))
    GTMaterials.Sodalite.setMaterialIconSet(GTMaterialIconSet.getByName('granular_lapis'))
    GTMaterials.Spessartine.setMaterialIconSet(GTMaterialIconSet.getByName('prismatic_ruby'))
    GTMaterials.Spodumene.setMaterialIconSet(GTMaterialIconSet.getByName('sheet_rough'))
    GTMaterials.Stibnite.setMaterialIconSet(GTMaterialIconSet.getByName('bladed'))
    GTMaterials.Talc.setMaterialIconSet(GTMaterialIconSet.getByName('monoclinic_dull'))
    GTMaterials.Tantalite.setMaterialIconSet(GTMaterialIconSet.getByName('sheet_metallic'))
    GTMaterials.Thorium.setMaterialIconSet(GTMaterialIconSet.getByName('cubic_metallic'))
    GTMaterials.TricalciumPhosphate.setMaterialIconSet(GTMaterialIconSet.getByName('sheet_rough'))
    GTMaterials.Trona.setMaterialIconSet(GTMaterialIconSet.getByName('bladed'))
    GTMaterials.Tungstate.setMaterialIconSet(GTMaterialIconSet.getByName('bladed'))
    GTMaterials.Uraninite.setMaterialIconSet(GTMaterialIconSet.getByName('botryoidal'))
    GTMaterials.VanadiumMagnetite.setMaterialIconSet(GTMaterialIconSet.getByName('cubic_dull'))
    GTMaterials.Wulfenite.setMaterialIconSet(GTMaterialIconSet.getByName('sheet_metallic'))
    GTMaterials.Zeolite.setMaterialIconSet(GTMaterialIconSet.getByName('granular_fine'))

    // Superconductors get noodle
    GTMaterials.ManganesePhosphide.setMaterialIconSet(GTMaterialIconSet.getByName('noodle'))
    GTMaterials.MagnesiumDiboride.setMaterialIconSet(GTMaterialIconSet.getByName('noodle'))
    GTMaterials.MercuryBariumCalciumCuprate.setMaterialIconSet(GTMaterialIconSet.getByName('noodle'))
    GTMaterials.UraniumTriplatinum.setMaterialIconSet(GTMaterialIconSet.getByName('noodle'))
    GTMaterials.SamariumIronArsenicOxide.setMaterialIconSet(GTMaterialIconSet.getByName('noodle'))
    GTMaterials.IndiumTinBariumTitaniumCuprate.setMaterialIconSet(GTMaterialIconSet.getByName('noodle'))
    GTMaterials.UraniumRhodiumDinaquadide.setMaterialIconSet(GTMaterialIconSet.getByName('noodle'))
    GTMaterials.EnrichedNaquadahTriniumEuropiumDuranide.setMaterialIconSet(GTMaterialIconSet.getByName('noodle'))
    GTMaterials.RutheniumTriniumAmericiumNeutronate.setMaterialIconSet(GTMaterialIconSet.getByName('noodle'))
    // Not a superconductor but it's where the icon comes from in the first place
    GTMaterials.Vanadium.setMaterialIconSet(GTMaterialIconSet.getByName('noodle'))

    // All naquadah/neutronium/zirconium materials get chonky
    GTMaterials.Naquadah.setMaterialIconSet(GTMaterialIconSet.getByName('chonky'))
    GTMaterials.NaquadahEnriched.setMaterialIconSet(GTMaterialIconSet.getByName('chonky'))
    GTMaterials.Naquadria.setMaterialIconSet(GTMaterialIconSet.getByName('chonky'))
    GTMaterials.UraniumRhodiumDinaquadide.setMaterialIconSet(GTMaterialIconSet.getByName('chonky'))
    GTMaterials.NaquadahAlloy.setMaterialIconSet(GTMaterialIconSet.getByName('chonky'))
    GTMaterials.Neutronium.setMaterialIconSet(GTMaterialIconSet.getByName('chonky'))

    GTMaterials.Zirconium.setMaterialIconSet(GTMaterialIconSet.getByName('chonky'))

    const $GreateMaterials = Java.loadClass("electrolyte.greate.registry.GreateMaterials")
	$GreateMaterials.RoseQuartz.setMaterialIconSet(GTMaterialIconSet.getByName('nether_quartz'))
}