name: "[💎]: Enhancement"
description: "Provide details for a gameplay enhancement or improvement."
title: "[💎]: "
labels: [ "Status: Backlog" ]
projects: ["TerraFirmaGreg-Team/10"]
type: "Enhancement"

body:
  - type: checkboxes
    id: exists
    attributes:
      label: "Was this enhancement suggested before?"
      description: "Please search OPEN/CLOSED issues before submitting, as the enhancement may have already been reported/addressed."
      options:
        - label: "No, it was not."
          required: true

  - type: textarea
    id: feature
    validations:
      required: true
    attributes:
      label: What would you like to be added/ changed?
      description: Enhancement requests should focus on gameplay improvements or additions that can be achieved without completely new features. Ex. Rebalancing the energy cost of a recipe.

  - type: textarea
    id: rationale
    validations:
      required: true
    attributes:
      label: Why is this needed?

  - type: markdown
    attributes:
      value: "Thanks for taking the time to fill out this enhancement request."