name: "[💡]: Feature request"
description: "Request a new feature or a new mod."
title: "[💡]: "
labels: [ "Status: Backlog" ]
projects: ["TerraFirmaGreg-Team/10"]
type: "Feature"

body:
  - type: checkboxes
    id: exists
    attributes:
      label: "Was this feature suggested before?"
      description: "Please search OPEN/CLOSED issues before submitting, as the feature may have already been reported/addressed."
      options:
        - label: "No, it was not."
          required: true

  - type: checkboxes
    id: blacklist
    attributes:
      label: "A list of popular features/mods the team has already considered and will not implement."
      description: |
        ### Mod Requests:
        - Other large tech mods (Immersive Engineering, Mekanism, etc.) will not be added to the pack due to overlap with Gregtech.
        - Magic mods (Thaumcraft, Botania, etc.) will not be added to the pack as we wish to be grounded in plausibility.
        - Create: the factory must grow. And other large Create mods. They do not work with Greate and we do not wish to focus on Create too much.
        - Create Clockworks & Valkyrian Skies. Both cool mods, but impossible to balance in TFG.
        - Stargate. Overdone in GT packs. We will work on something unique as an endgame goal.
        
        ### Feature Requests:
        - Dyson Spheres. Boring and overdone.
        - More GT Voltage Tiers. We would prefer to have larger more rounded tiers than many small ones.
      options:
        - label: "I understand :("
          required: true

  - type: textarea
    id: feature
    validations:
      required: true
    attributes:
      label: What would you like to be added?
      description: Feature requests should focus on new gameplay experiences or QoL additions.

  - type: textarea
    id: rationale
    validations:
      required: true
    attributes:
      label: Why is this needed?

  - type: markdown
    attributes:
      value: "Thanks for taking the time to fill out this feature request."
