name: "Feature request"
description: "Request a new feature or a change to an existing one."
title: "[🪶]: "
labels: [ "1. Type: Feature" ]

body:
  - type: checkboxes
    id: exists
    attributes:
      label: "Was this feature suggested before?"
      description: "Please search open/closed issues before submitting, as the issue may have already been reported/addressed."
      options:
        - label: "No, it was not."
          required: true

  - type: input
    id: version
    attributes:
      label: "Version modpack used"
      description: Write which version of the modpack you are using.
      placeholder: "Example: 0.1.1"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: "Related problem"
      description: If the feature you wish to change is related to a problem, please desscribe it. Leave this field blank if it is not related to a problem.
      placeholder: "Example: I'm always frustrated when..."
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: "Your solution"
      description: Describe the solution you would like to have happen.
      placeholder: "Example: If I could..."
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: "Additional information"
      description: Any additional information you wish to provide. Please add anything which did not fit into the other sections here.
      placeholder: "Example: This is likely achieveable by doing X because..."
    validations:
      required: false

  - type: markdown
    attributes:
      value: "Thanks for taking the time to fill out this feature request."
