name: "[❓]: Ask a Question"
description: "Ask a question regarding this project."
title: "[❓]: "
labels: [ "Status: Backlog" ]
type: "Question"

body:
  - type: checkboxes
    id: exists
    attributes:
      label: "Was this question asked before?"
      description: "Please search OPEN/CLOSED issues before submitting, as the issue may have already been reported/addressed."
      options:
        - label: "No, it was not."
          required: true

  - type: markdown
    attributes:
      value: |
        If you are in need of a quick response, [Discord](https://discord.gg/AEaCzCTUwQ) may be a better place.
        
        Most information is available in-game through Tooltips, EMI, Field Guide, or Quests.
        An online version of the [Field Guide](https://terrafirmagreg-team.github.io/Field-Guide-Modern/en_us/) is also available.
        
        For installing a development environment, please refer to the [Contributing Guide](https://github.com/TerraFirmaGreg-Team/Modpack-Modern/blob/dev/.github/CONTRIBUTING.md)
        For information about translating please read our [Localization Guide](https://github.com/TerraFirmaGreg-Team/Modpack-Modern/blob/dev/kubejs/README_IF_TRANSLATING.md)

  - type: textarea
    id: question
    validations:
      required: true
    attributes:
      label: Your Question
      description: Feel free to ask any question regarding this project here.
      placeholder: "Example: How can I...?"

  - type: markdown
    attributes:
      value: "Thank you for taking the time to ask us a question."
