"use strict";

function registerTFGRockBlocks(event) {

	const SHAPES = ['stairs', 'slab', 'wall']
	
	const AA_REGULAR_STONES = ['moon', 'mars', 'venus', 'mercury', 'glacio']

	// #region Raw Stones

	SHAPES.forEach(shape => {
		event.create(`tfg:rock/deepslate_${shape}`, shape)
			.soundType(global.STONE_CHARACS.deepslate.sound)
			.textureAll('minecraft:block/deepslate')
			.tagBoth(`tfg:rock_${shape}s`.replace(/ss/g, 's'))
			.tagBoth(`tfc:${global.STONE_CHARACS.deepslate.type}_items`)
			.mapColor(global.STONE_CHARACS.deepslate.mapColor)
			.tagBlock('minecraft:mineable/pickaxe')
			.fullBlock(true)
			.opaque(true)
	})

	SHAPES.forEach(shape => {
		event.create(`tfg:rock/dripstone_${shape}`, shape)
			.soundType(global.STONE_CHARACS.dripstone.sound)
			.textureAll('minecraft:block/dripstone_block')
			.tagBoth(`tfg:rock_${shape}s`.replace(/ss/g, 's'))
			.tagBoth(`tfc:${global.STONE_CHARACS.dripstone.type}_items`)
			.mapColor(global.STONE_CHARACS.dripstone.mapColor)
			.tagBlock('minecraft:mineable/pickaxe')
			.fullBlock(true)
			.opaque(true)
	})

	SHAPES.forEach(shape => {
		event.create(`tfg:rock/crackrack_${shape}`, shape)
			.soundType(global.STONE_CHARACS.crackrack.sound)
			.textureAll('beneath:block/crackrack')
			.tagBoth(`tfg:rock_${shape}s`.replace(/ss/g, 's'))
			.tagBoth(`tfc:${global.STONE_CHARACS.crackrack.type}_items`)
			.mapColor(global.STONE_CHARACS.crackrack.mapColor)
			.tagBlock('minecraft:mineable/pickaxe')
			.fullBlock(true)
			.opaque(true)
	})
	
	event.create('tfg:rock/moon_stone_wall', 'wall')
		.soundType(global.STONE_CHARACS.moon.sound)
		.textureAll('ad_astra:block/moon_stone')
		.tagBoth('tfg:rock_walls')
		.tagBoth(`tfc:${global.STONE_CHARACS.moon.type}_items`)
		.mapColor(global.STONE_CHARACS.moon.mapColor)
		.tagBlock('minecraft:mineable/pickaxe')
		.fullBlock(true)
		.opaque(true)

	SHAPES.forEach(shape => {
		event.create(`tfg:rock/moon_deepslate_${shape}`, shape)
			.soundType(global.STONE_CHARACS.moon_deepslate.sound)
			.textureAll('ad_astra:block/moon_deepslate')
			.tagBoth(`tfg:rock_${shape}s`.replace(/ss/g, 's'))
			.tagBoth(`tfc:${global.STONE_CHARACS.moon_deepslate.type}_items`)
			.mapColor(global.STONE_CHARACS.moon_deepslate.mapColor)
			.tagBlock('minecraft:mineable/pickaxe')
			.fullBlock(true)
			.opaque(true)
	})

	event.create('tfg:rock/mars_stone_wall', 'wall')
		.soundType(global.STONE_CHARACS.mars.sound)
		.textureAll('ad_astra:block/mars_stone')
		.tagBoth('tfg:rock_walls')
		.tagBoth(`tfc:${global.STONE_CHARACS.mars.type}_items`)
		.mapColor(global.STONE_CHARACS.mars.mapColor)
		.tagBlock('minecraft:mineable/pickaxe')
		.fullBlock(true)
		.opaque(true)
	
	event.create('tfg:rock/venus_stone_wall', 'wall')
		.soundType(global.STONE_CHARACS.venus.sound)
		.textureAll('ad_astra:block/venus_stone')
		.tagBoth('tfg:rock_walls')
		.tagBoth(`tfc:${global.STONE_CHARACS.venus.type}_items`)
		.mapColor(global.STONE_CHARACS.venus.mapColor)
		.tagBlock('minecraft:mineable/pickaxe')
		.fullBlock(true)
		.opaque(true)

	event.create('tfg:rock/mercury_stone_wall', 'wall')
		.soundType(global.STONE_CHARACS.mercury.sound)
		.textureAll('ad_astra:block/mercury_stone')
		.tagBoth('tfg:rock_walls')
		.tagBoth(`tfc:${global.STONE_CHARACS.mercury.type}_items`)
		.mapColor(global.STONE_CHARACS.mercury.mapColor)
		.tagBlock('minecraft:mineable/pickaxe')
		.fullBlock(true)
		.opaque(true)

	event.create('tfg:rock/glacio_stone_wall', 'wall')
		.soundType(global.STONE_CHARACS.glacio.sound)
		.textureAll('ad_astra:block/glacio_stone')
		.tagBoth('tfg:rock_walls')
		.tagBoth(`tfc:${global.STONE_CHARACS.glacio.type}_items`)
		.mapColor(global.STONE_CHARACS.glacio.mapColor)
		.tagBlock('minecraft:mineable/pickaxe')
		.fullBlock(true)
		.opaque(true)
	
	SHAPES.forEach(shape => {
		event.create(`tfg:rock/permafrost_${shape}`, shape)
			.soundType(global.STONE_CHARACS.permafrost.sound)
			.textureAll('ad_astra:block/permafrost')
			.tagBoth(`tfg:rock_${shape}s`.replace(/ss/g, 's'))
			.mapColor(global.STONE_CHARACS.permafrost.mapColor)
			.tagBlock('minecraft:mineable/pickaxe')
			.fullBlock(true)
			.opaque(true)
	})
	
	SHAPES.forEach(shape => {
		event.create(`tfg:rock/red_granite_${shape}`, shape)
			.soundType(global.STONE_CHARACS.red_granite.sound)
			.textureAll('gtceu:block/stones/red_granite/stone')
			.tagBoth(`tfg:rock_${shape}s`.replace(/ss/g, 's'))
			.tagBoth(`tfc:${global.STONE_CHARACS.red_granite.type}_items`)
			.mapColor(global.STONE_CHARACS.red_granite.mapColor)
			.tagBlock('minecraft:mineable/pickaxe')
			.fullBlock(true)
			.opaque(true)
	})

	// #endregion Raw Stones
	
	// #region Hardened Stones
	event.create('tfg:rock/hardened_deepslate')
		.soundType(global.STONE_CHARACS.deepslate.sound)
		.property(BlockProperties.AXIS)
		.requiresTool(true)
		.item(item => {
			item.modelJson({ parent: 'minecraft:item/deepslate' })
		})
		.tagBlock('tfc:can_carve')
		.tagBoth('forge:stone')
		.tagBoth('tfc:rock/hardened')
		.tagBoth(`tfc:${global.STONE_CHARACS.deepslate.type}_items`)
		.mapColor(global.STONE_CHARACS.deepslate.mapColor)
		.tagBlock('minecraft:mineable/pickaxe')
		.fullBlock(true)
		.opaque(true)

	event.create('tfg:rock/hardened_blackstone')
		.soundType(global.STONE_CHARACS.blackstone.sound)
		.requiresTool(true)
		.item(item => {
			item.modelJson({ parent: 'minecraft:item/blackstone' })
		})
		.tagBlock('tfc:can_carve')
		.tagBoth('forge:stone')
		.tagBoth('tfc:rock/hardened')
		.tagBoth(`tfc:${global.STONE_CHARACS.blackstone.type}_items`)
		.mapColor(global.STONE_CHARACS.blackstone.mapColor)
		.tagBlock('minecraft:mineable/pickaxe')
		.fullBlock(true)
		.opaque(true)

	event.create('tfg:rock/hardened_dripstone')
		.soundType(global.STONE_CHARACS.dripstone.sound)
		.stoneSoundType()
		.requiresTool(true)
		.item(item => {
			item.modelJson({ parent: 'minecraft:item/dripstone_block' })
		})
		.tagBlock('tfc:can_carve')
		.tagBoth('forge:stone')
		.tagBoth('tfc:rock/hardened')
		.tagBoth(`tfc:${global.STONE_CHARACS.dripstone.type}_items`)
		.mapColor(global.STONE_CHARACS.dripstone.mapColor)
		.tagBlock('minecraft:mineable/pickaxe')
		.fullBlock(true)
		.opaque(true)

	event.create('tfg:rock/hardened_moon_stone')
		.soundType(global.STONE_CHARACS.moon.sound)
		.requiresTool(true)
		.item(item => {
			item.modelJson({ parent: 'ad_astra:item/moon_stone' })
		})
		.tagBlock('tfc:can_carve')
		.tagBoth('forge:stone')
		.tagBoth('tfc:rock/hardened')
		.tagBoth(`tfc:${global.STONE_CHARACS.moon.type}_items`)
		.mapColor(global.STONE_CHARACS.moon.mapColor)
		.tagBlock('minecraft:mineable/pickaxe')
		.fullBlock(true)
		.opaque(true)

	event.create('tfg:rock/hardened_moon_deepslate')
		.soundType(global.STONE_CHARACS.moon_deepslate.sound)
		.requiresTool(true)
		.item(item => {
			item.modelJson({ parent: 'ad_astra:item/moon_deepslate' })
		})
		.tagBlock('tfc:can_carve')
		.tagBoth('forge:stone')
		.tagBoth('tfc:rock/hardened')
		.tagBoth(`tfc:${global.STONE_CHARACS.moon_deepslate.type}_items`)
		.mapColor(global.STONE_CHARACS.moon_deepslate.mapColor)
		.tagBlock('minecraft:mineable/pickaxe')
		.fullBlock(true)
		.opaque(true)

	event.create('tfg:rock/hardened_mars_stone')
		.soundType(global.STONE_CHARACS.mars.sound)
		.requiresTool(true)
		.item(item => {
			item.modelJson({ parent: 'ad_astra:item/mars_stone' })
		})
		.tagBlock('tfc:can_carve')
		.tagBoth('forge:stone')
		.tagBoth('tfc:rock/hardened')
		.tagBoth(`tfc:${global.STONE_CHARACS.mars.type}_items`)
		.mapColor(global.STONE_CHARACS.mars.mapColor)
		.tagBlock('minecraft:mineable/pickaxe')
		.fullBlock(true)
		.opaque(true)

	event.create('tfg:rock/hardened_venus_stone')
		.soundType(global.STONE_CHARACS.venus.sound)
		.requiresTool(true)
		.item(item => {
			item.modelJson({ parent: 'ad_astra:item/venus_stone' })
		})
		.tagBlock('tfc:can_carve')
		.tagBoth('forge:stone')
		.tagBoth('tfc:rock/hardened')
		.tagBoth(`tfc:${global.STONE_CHARACS.venus.type}_items`)
		.mapColor(global.STONE_CHARACS.venus.mapColor)
		.tagBlock('minecraft:mineable/pickaxe')
		.fullBlock(true)
		.opaque(true)

	event.create('tfg:rock/hardened_mercury_stone')
		.soundType(global.STONE_CHARACS.mercury.sound)
		.requiresTool(true)
		.item(item => {
			item.modelJson({ parent: 'ad_astra:item/mercury_stone' })
		})
		.tagBlock('tfc:can_carve')
		.tagBoth('forge:stone')
		.tagBoth('tfc:rock/hardened')
		.tagBoth(`tfc:${global.STONE_CHARACS.mercury.type}_items`)
		.mapColor(global.STONE_CHARACS.mercury.mapColor)
		.tagBlock('minecraft:mineable/pickaxe')
		.fullBlock(true)
		.opaque(true)

	event.create('tfg:rock/hardened_glacio_stone')
		.soundType(global.STONE_CHARACS.glacio.sound)
		.requiresTool(true)
		.item(item => {
			item.modelJson({ parent: 'ad_astra:item/glacio_stone' })
		})
		.tagBlock('tfc:can_carve')
		.tagBoth('forge:stone')
		.tagBoth('tfc:rock/hardened')
		.tagBoth(`tfc:${global.STONE_CHARACS.glacio.type}_items`)
		.mapColor(global.STONE_CHARACS.glacio.mapColor)
		.tagBlock('minecraft:mineable/pickaxe')
		.fullBlock(true)
		.opaque(true)

	event.create('tfg:rock/hardened_red_granite')
		.soundType(global.STONE_CHARACS.red_granite.sound)
		.requiresTool(true)
		.item(item => {
			item.modelJson({ parent: 'gtceu:item/red_granite' })
		})
		.tagBlock('tfc:can_carve')
		.tagBoth('forge:stone')
		.tagBoth('tfc:rock/hardened')
		.tagBoth(`tfc:${global.STONE_CHARACS.red_granite.type}_items`)
		.mapColor(global.STONE_CHARACS.red_granite.mapColor)
		.tagBlock('minecraft:mineable/pickaxe')
		.fullBlock(true)
		.opaque(true)

	// #endregion Hardened Stones
	
	// #region Loose Stones
	event.create('tfg:loose/deepslate', 'tfc:loose_rock')
		.soundType(global.STONE_CHARACS.deepslate.sound)
		.itemTexture('tfg:item/loose/deepslate')
		.rockTypeModel(global.STONE_CHARACS.deepslate.type)
		.translationKey("block.tfg.loose.deepslate")
		.mapColor(global.STONE_CHARACS.deepslate.mapColor)
		.tagBlock('tfc:loose_rocks')
		.tagItem('tfc:any_knapping')
		.tagItem('tfc:rock_knapping')
		.tagItem(`tfc:${global.STONE_CHARACS.deepslate.type}_rock`)
		.tagBoth(`tfc:${global.STONE_CHARACS.deepslate.type}_items`)
		.tagItem("rnr:loose_rock_items")

	event.create('tfg:loose/dripstone', 'tfc:loose_rock')
		.soundType(global.STONE_CHARACS.dripstone.sound)
		.itemTexture('tfg:item/loose/dripstone')
		.rockTypeModel(global.STONE_CHARACS.dripstone.type)
		.translationKey("block.tfg.loose.dripstone")
		.mapColor(global.STONE_CHARACS.blackstone.mapColor)
		.tagBlock('tfc:loose_rocks')
		.tagItem('tfc:any_knapping')
		.tagItem('tfc:rock_knapping')
		.tagItem(`tfc:${global.STONE_CHARACS.dripstone.type}_rock`)
		.tagBoth(`tfc:${global.STONE_CHARACS.dripstone.type}_items`)
		.tagItem("rnr:loose_rock_items")

	event.create('tfg:loose/crackrack', 'tfc:loose_rock')
		.soundType(global.STONE_CHARACS.crackrack.sound)
		.itemTexture('tfg:item/loose/crackrack')
		.rockTypeModel(global.STONE_CHARACS.crackrack.type)
		.translationKey("block.tfg.loose.crackrack")
		.mapColor(global.STONE_CHARACS.crackrack.mapColor)
		.tagBlock('tfc:loose_rocks')
		.tagItem('tfc:any_knapping')
		.tagItem('tfc:rock_knapping')
		.tagItem(`tfc:${global.STONE_CHARACS.crackrack.type}_rock`)
		.tagBoth(`tfc:${global.STONE_CHARACS.crackrack.type}_items`)
		.tagItem("rnr:loose_rock_items")

	event.create('tfg:loose/moon_stone', 'tfc:loose_rock')
		.soundType(global.STONE_CHARACS.moon.sound)
		.itemTexture('tfg:item/loose/moon_stone')
		.rockTypeModel(global.STONE_CHARACS.moon.type)
		.tagBlock('tfc:loose_rocks')
		.tagItem('tfc:any_knapping')
		.tagItem('tfc:rock_knapping')
		.tagItem(`tfc:${global.STONE_CHARACS.moon.type}_rock`)
		.tagBoth(`tfc:${global.STONE_CHARACS.moon.type}_items`)
		.tagItem("rnr:loose_rock_items")

	event.create('tfg:loose/moon_deepslate', 'tfc:loose_rock')
		.soundType(global.STONE_CHARACS.moon_deepslate.sound)
		.itemTexture('tfg:item/loose/moon_deepslate')
		.rockTypeModel(global.STONE_CHARACS.moon_deepslate.type)
		.tagBlock('tfc:loose_rocks')
		.tagItem('tfc:any_knapping')
		.tagItem('tfc:rock_knapping')
		.tagItem(`tfc:${global.STONE_CHARACS.moon_deepslate.type}_rock`)
		.tagBoth(`tfc:${global.STONE_CHARACS.moon_deepslate.type}_items`)
		.tagItem("rnr:loose_rock_items")

	event.create('tfg:loose/mars_stone', 'tfc:loose_rock')
		.soundType(global.STONE_CHARACS.mars.sound)
		.itemTexture('tfg:item/loose/mars_stone')
		.rockTypeModel(global.STONE_CHARACS.mars.type)
		.tagBlock('tfc:loose_rocks')
		.tagItem('tfc:any_knapping')
		.tagItem('tfc:rock_knapping')
		.tagItem(`tfc:${global.STONE_CHARACS.mars.type}_rock`)
		.tagBoth(`tfc:${global.STONE_CHARACS.mars.type}_items`)
		.tagItem("rnr:loose_rock_items")

	event.create('tfg:loose/venus_stone', 'tfc:loose_rock')
		.soundType(global.STONE_CHARACS.venus.sound)
		.itemTexture('tfg:item/loose/venus_stone')
		.rockTypeModel(global.STONE_CHARACS.venus.type)
		.tagBlock('tfc:loose_rocks')
		.tagItem('tfc:any_knapping')
		.tagItem('tfc:rock_knapping')
		.tagItem(`tfc:${global.STONE_CHARACS.venus.type}_rock`)
		.tagBoth(`tfc:${global.STONE_CHARACS.venus.type}_items`)
		.tagItem("rnr:loose_rock_items")

	event.create('tfg:loose/mercury_stone', 'tfc:loose_rock')
		.soundType(global.STONE_CHARACS.mercury.sound)
		.itemTexture('tfg:item/loose/mercury_stone')
		.rockTypeModel(global.STONE_CHARACS.mercury.type)
		.tagBlock('tfc:loose_rocks')
		.tagItem('tfc:any_knapping')
		.tagItem('tfc:rock_knapping')
		.tagItem(`tfc:${global.STONE_CHARACS.mercury.type}_rock`)
		.tagBoth(`tfc:${global.STONE_CHARACS.mercury.type}_items`)
		.tagItem("rnr:loose_rock_items")

	event.create('tfg:loose/glacio_stone', 'tfc:loose_rock')
		.soundType(global.STONE_CHARACS.glacio.sound)
		.itemTexture('tfg:item/loose/glacio_stone')
		.rockTypeModel(global.STONE_CHARACS.glacio.type)
		.tagBlock('tfc:loose_rocks')
		.tagItem('tfc:any_knapping')
		.tagItem('tfc:rock_knapping')
		.tagItem(`tfc:${global.STONE_CHARACS.glacio.type}_rock`)
		.tagBoth(`tfc:${global.STONE_CHARACS.glacio.type}_items`)
		.tagItem("rnr:loose_rock_items")

	event.create('tfg:loose/permafrost', 'tfc:loose_rock')
		.soundType(global.STONE_CHARACS.permafrost.sound)
		.itemTexture('tfg:item/loose/permafrost')
		.rockTypeModel(global.STONE_CHARACS.permafrost.type)
		.tagBlock('tfc:loose_rocks')
		.tagItem('tfc:any_knapping')
		.tagItem('tfc:rock_knapping')
		.tagItem("rnr:loose_rock_items")

	event.create('tfg:loose/red_granite', 'tfc:loose_rock')
		.soundType(global.STONE_CHARACS.red_granite.sound)
		.itemTexture('tfg:item/loose/red_granite')
		.rockTypeModel(global.STONE_CHARACS.red_granite.type)
		.tagBlock('tfc:loose_rocks')
		.tagItem('tfc:any_knapping')
		.tagItem('tfc:rock_knapping')
		.tagItem(`tfc:${global.STONE_CHARACS.red_granite.type}_rock`)
		.tagBoth(`tfc:${global.STONE_CHARACS.red_granite.type}_items`)
		.tagItem("rnr:loose_rock_items")

	// #endregion Loose stones
	
	// #region Spikes

	event.create('tfg:spike/deepslate_spike', 'tfc:rock_spike')
		.textureAll('minecraft:block/deepslate')
		.soundType(global.STONE_CHARACS.deepslate.sound)
		.tagBoth(`tfc:${global.STONE_CHARACS.deepslate.type}_items`)
		.mapColor(global.STONE_CHARACS.deepslate.mapColor)
		.tagBlock('minecraft:mineable/pickaxe')
		.hardness(0.8)
		.resistance(0.8)
		.requiresTool(true)

	event.create('tfg:spike/blackstone_spike', 'tfc:rock_spike')
		.textureAll('minecraft:block/blackstone')
		.soundType(global.STONE_CHARACS.blackstone.sound)
		.tagBoth(`tfc:${global.STONE_CHARACS.blackstone.type}_items`)
		.mapColor(global.STONE_CHARACS.blackstone.mapColor)
		.tagBlock('minecraft:mineable/pickaxe')
		.hardness(0.8)
		.resistance(0.8)
		.requiresTool(true)

	event.create('tfg:spike/dripstone_spike', 'tfc:rock_spike')
		.textureAll('minecraft:block/dripstone_block')
		.soundType(global.STONE_CHARACS.dripstone.sound)
		.tagBoth(`tfc:${global.STONE_CHARACS.dripstone.type}_items`)
		.mapColor(global.STONE_CHARACS.dripstone.mapColor)
		.tagBlock('minecraft:mineable/pickaxe')
		.hardness(0.8)
		.resistance(0.8)
		.requiresTool(true)

	event.create('tfg:spike/moon_stone_spike', 'tfc:rock_spike')
		.textureAll('ad_astra:block/moon_stone')
		.soundType(global.STONE_CHARACS.moon.sound)
		.tagBlock('minecraft:mineable/pickaxe')
		.hardness(0.8)
		.resistance(0.8)
		.requiresTool(true)

	event.create('tfg:spike/moon_deepslate_spike', 'tfc:rock_spike')
		.textureAll('ad_astra:block/moon_deepslate')
		.soundType(global.STONE_CHARACS.moon_deepslate.sound)
		.tagBlock('minecraft:mineable/pickaxe')
		.hardness(0.8)
		.resistance(0.8)
		.requiresTool(true)

	event.create('tfg:spike/mars_stone_spike', 'tfc:rock_spike')
		.textureAll('ad_astra:block/mars_stone')
		.soundType(global.STONE_CHARACS.mars.sound)
		.tagBlock('minecraft:mineable/pickaxe')
		.hardness(0.8)
		.resistance(0.8)
		.requiresTool(true)

	event.create('tfg:spike/venus_stone_spike', 'tfc:rock_spike')
		.textureAll('ad_astra:block/venus_stone')
		.soundType(global.STONE_CHARACS.venus.sound)
		.tagBlock('minecraft:mineable/pickaxe')
		.hardness(0.8)
		.resistance(0.8)
		.requiresTool(true)

	event.create('tfg:spike/mercury_stone_spike', 'tfc:rock_spike')
		.textureAll('ad_astra:block/mercury_stone')
		.soundType(global.STONE_CHARACS.mercury.sound)
		.tagBlock('minecraft:mineable/pickaxe')
		.hardness(0.8)
		.resistance(0.8)
		.requiresTool(true)

	event.create('tfg:spike/glacio_stone_spike', 'tfc:rock_spike')
		.textureAll('ad_astra:block/glacio_stone')
		.soundType(global.STONE_CHARACS.glacio.sound)
		.tagBlock('minecraft:mineable/pickaxe')
		.hardness(0.8)
		.resistance(0.8)
		.requiresTool(true)

	event.create('tfg:spike/permafrost_spike', 'tfc:rock_spike')
		.textureAll('ad_astra:block/permafrost')
		.soundType(global.STONE_CHARACS.permafrost.sound)
		.tagBlock('minecraft:mineable/pickaxe')
		.hardness(0.8)
		.resistance(0.8)
		.requiresTool(true)

	event.create('tfg:spike/red_granite_spike', 'tfc:rock_spike')
		.textureAll('gtceu:block/stones/red_granite/stone')
		.soundType(global.STONE_CHARACS.red_granite.sound)
		.tagBlock('minecraft:mineable/pickaxe')
		.hardness(0.8)
		.resistance(0.8)
		.requiresTool(true)

	// #endregion Spikes
	
	// #region Cobblestones

	// Deepslate
	event.create('tfg:rock/mossy_cobble_deepslate')
		.soundType(global.STONE_CHARACS.deepslate.sound)
		.tagBoth('forge:cobblestone')
		.tagBoth('forge:cobblestone/normal')
		.tagBoth(`tfc:${global.STONE_CHARACS.deepslate.type}_items`)
		.mapColor(global.STONE_CHARACS.deepslate.mapColor)
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('tfc:can_landslide')
		.fullBlock(true)
		.opaque(true)

	SHAPES.forEach(shape => {
		event.create(`tfg:rock/mossy_cobble_deepslate_${shape}`, shape)
			.soundType(global.STONE_CHARACS.deepslate.sound)
			.tagBoth(`tfg:rock_${shape}s`.replace(/ss/g, 's'))
			.tagBoth(`tfc:${global.STONE_CHARACS.deepslate.type}_items`)
			.mapColor(global.STONE_CHARACS.deepslate.mapColor)
			.tagBlock('minecraft:mineable/pickaxe')
			.fullBlock(true)
			.opaque(true)
	})

	// Blackstone
	event.create('tfg:rock/cobble_blackstone')
		.soundType(global.STONE_CHARACS.blackstone.sound)
		.tagBoth('forge:cobblestone')
		.tagBoth('forge:cobblestone/normal')
		.tagBoth(`tfc:${global.STONE_CHARACS.blackstone.type}_items`)
		.mapColor(global.STONE_CHARACS.blackstone.mapColor)
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('tfc:can_landslide')
		.fullBlock(true)
		.opaque(true)

	SHAPES.forEach(shape => {
		event.create(`tfg:rock/cobble_blackstone_${shape}`, shape)
			.soundType(global.STONE_CHARACS.blackstone.sound)
			.textureAll('minecraft:block/blackstone_top')
			.tagBoth(`tfg:rock_${shape}s`.replace(/ss/g, 's'))
			.tagBoth(`tfc:${global.STONE_CHARACS.blackstone.type}_items`)
			.mapColor(global.STONE_CHARACS.blackstone.mapColor)
			.tagBlock('minecraft:mineable/pickaxe')
			.fullBlock(true)
			.opaque(true)
	})

	event.create('tfg:rock/mossy_cobble_blackstone')
		.soundType(global.STONE_CHARACS.blackstone.sound)
		.tagBoth('forge:cobblestone')
		.tagBoth('forge:cobblestone/normal')
		.tagBoth(`tfc:${global.STONE_CHARACS.blackstone.type}_items`)
		.mapColor(global.STONE_CHARACS.blackstone.mapColor)
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('tfc:can_landslide')
		.fullBlock(true)
		.opaque(true)

	SHAPES.forEach(shape => {
		event.create(`tfg:rock/mossy_cobble_blackstone_${shape}`, shape)
			.soundType(global.STONE_CHARACS.blackstone.sound)
			.tagBoth(`tfg:rock_${shape}s`.replace(/ss/g, 's'))
			.tagBoth(`tfc:${global.STONE_CHARACS.blackstone.type}_items`)
			.mapColor(global.STONE_CHARACS.blackstone.mapColor)
			.tagBlock('minecraft:mineable/pickaxe')
			.fullBlock(true)
			.opaque(true)
	})

	// Dripstone
	event.create('tfg:rock/cobble_dripstone')
		.soundType(global.STONE_CHARACS.dripstone.sound)
		.tagBoth('forge:cobblestone')
		.tagBoth('forge:cobblestone/normal')
		.tagBoth(`tfc:${global.STONE_CHARACS.dripstone.type}_items`)
		.mapColor(global.STONE_CHARACS.dripstone.mapColor)
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('tfc:can_landslide')
		.fullBlock(true)
		.opaque(true)

	SHAPES.forEach(shape => {
		event.create(`tfg:rock/cobble_dripstone_${shape}`, shape)
			.soundType(global.STONE_CHARACS.dripstone.sound)
			.tagBoth(`tfg:rock_${shape}s`.replace(/ss/g, 's'))
			.tagBoth(`tfc:${global.STONE_CHARACS.dripstone.type}_items`)
			.mapColor(global.STONE_CHARACS.dripstone.mapColor)
			.tagBlock('minecraft:mineable/pickaxe')
			.fullBlock(true)
			.opaque(true)
	})

	event.create('tfg:rock/mossy_cobble_dripstone')
		.soundType(global.STONE_CHARACS.dripstone.sound)
		.tagBoth('forge:cobblestone')
		.tagBoth('forge:cobblestone/normal')
		.tagBoth(`tfc:${global.STONE_CHARACS.dripstone.type}_items`)
		.mapColor(global.STONE_CHARACS.dripstone.mapColor)
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('tfc:can_landslide')
		.fullBlock(true)
		.opaque(true)

	SHAPES.forEach(shape => {
		event.create(`tfg:rock/mossy_cobble_dripstone_${shape}`, shape)
			.soundType(global.STONE_CHARACS.dripstone.sound)
			.tagBoth(`tfg:rock_${shape}s`.replace(/ss/g, 's'))
			.tagBoth(`tfc:${global.STONE_CHARACS.dripstone.type}_items`)
			.mapColor(global.STONE_CHARACS.dripstone.mapColor)
			.tagBlock('minecraft:mineable/pickaxe')
			.fullBlock(true)
			.opaque(true)
	})

	// Crackrack
	event.create('tfg:rock/cobble_crackrack')
		.soundType(global.STONE_CHARACS.crackrack.sound)
		.tagBoth('forge:cobblestone')
		.tagBoth('forge:cobblestone/normal')
		.tagBoth(`tfc:${global.STONE_CHARACS.crackrack.type}_items`)
		.mapColor(global.STONE_CHARACS.crackrack.mapColor)
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('tfc:can_landslide')
		.fullBlock(true)
		.opaque(true)

	SHAPES.forEach(shape => {
		event.create(`tfg:rock/cobble_crackrack_${shape}`, shape)
			.soundType(global.STONE_CHARACS.crackrack.sound)
			.tagBoth(`tfg:rock_${shape}s`.replace(/ss/g, 's'))
			.tagBoth(`tfc:${global.STONE_CHARACS.crackrack.type}_items`)
			.mapColor(global.STONE_CHARACS.crackrack.mapColor)
			.tagBlock('minecraft:mineable/pickaxe')
			.fullBlock(true)
			.opaque(true)
	})

	event.create('tfg:rock/mossy_cobble_crackrack')
		.soundType(global.STONE_CHARACS.crackrack.sound)
		.tagBoth('forge:cobblestone')
		.tagBoth('forge:cobblestone/normal')
		.tagBoth(`tfc:${global.STONE_CHARACS.crackrack.type}_items`)
		.mapColor(global.STONE_CHARACS.crackrack.mapColor)
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('tfc:can_landslide')
		.fullBlock(true)
		.opaque(true)

	SHAPES.forEach(shape => {
		event.create(`tfg:rock/mossy_cobble_crackrack_${shape}`, shape)
			.soundType(global.STONE_CHARACS.crackrack.sound)
			.tagBoth(`tfg:rock_${shape}s`.replace(/ss/g, 's'))
			.tagBoth(`tfc:${global.STONE_CHARACS.crackrack.type}_items`)
			.mapColor(global.STONE_CHARACS.crackrack.mapColor)
			.tagBlock('minecraft:mineable/pickaxe')
			.fullBlock(true)
			.opaque(true)
	})

	// Moon
	event.create('tfg:rock/cobble_moon_wall', 'wall')
		.soundType(global.STONE_CHARACS.moon.sound)
		.textureAll('ad_astra:block/moon_cobblestone')
		.tagBoth('tfg:rock_walls')
		.tagBoth(`tfc:${global.STONE_CHARACS.moon.type}_items`)
		.mapColor(global.STONE_CHARACS.moon.mapColor)
		.tagBlock('minecraft:mineable/pickaxe')
		.fullBlock(true)
		.opaque(true)
	
	event.create('tfg:rock/mossy_cobble_moon')
		.soundType(global.STONE_CHARACS.moon.sound)
		.tagBoth('forge:cobblestone')
		.tagBoth('forge:cobblestone/normal')
		.tagBoth(`tfc:${global.STONE_CHARACS.moon.type}_items`)
		.mapColor(global.STONE_CHARACS.moon.mapColor)
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('tfc:can_landslide')
		.fullBlock(true)
		.opaque(true)
	
	SHAPES.forEach(shape => {
		event.create(`tfg:rock/mossy_cobble_moon_${shape}`, shape)
			.soundType(global.STONE_CHARACS.moon.sound)
			.tagBoth(`tfg:rock_${shape}s`.replace(/ss/g, 's'))
			.tagBoth(`tfc:${global.STONE_CHARACS.moon.type}_items`)
			.mapColor(global.STONE_CHARACS.moon.mapColor)
			.tagBlock('minecraft:mineable/pickaxe')
			.fullBlock(true)
			.opaque(true)
	})

	// Moon Deepslate
	event.create('tfg:rock/cobble_moon_deepslate')
		.soundType(global.STONE_CHARACS.moon_deepslate.sound)
		.tagBoth('forge:cobblestone')
		.tagBoth('forge:cobblestone/normal')
		.tagBoth(`tfc:${global.STONE_CHARACS.moon_deepslate.type}_items`)
		.mapColor(global.STONE_CHARACS.moon_deepslate.mapColor)
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('tfc:can_landslide')
		.fullBlock(true)
		.opaque(true)
	
	SHAPES.forEach(shape => {
		event.create(`tfg:rock/cobble_moon_deepslate_${shape}`, shape)
			.soundType(global.STONE_CHARACS.moon_deepslate.sound)
			.tagBoth(`tfg:rock_${shape}s`.replace(/ss/g, 's'))
			.tagBoth(`tfc:${global.STONE_CHARACS.moon_deepslate.type}_items`)
			.mapColor(global.STONE_CHARACS.moon_deepslate.mapColor)
			.tagBlock('minecraft:mineable/pickaxe')
			.fullBlock(true)
			.opaque(true)
	})
	
	event.create('tfg:rock/mossy_cobble_moon_deepslate')
		.soundType(global.STONE_CHARACS.moon_deepslate.sound)
		.tagBoth('forge:cobblestone')
		.tagBoth('forge:cobblestone/normal')
		.tagBoth(`tfc:${global.STONE_CHARACS.moon_deepslate.type}_items`)
		.mapColor(global.STONE_CHARACS.moon_deepslate.mapColor)
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('tfc:can_landslide')
		.fullBlock(true)
		.opaque(true)
	
	SHAPES.forEach(shape => {
		event.create(`tfg:rock/mossy_cobble_moon_deepslate_${shape}`, shape)
			.soundType(global.STONE_CHARACS.moon_deepslate.sound)
			.tagBoth(`tfg:rock_${shape}s`.replace(/ss/g, 's'))
			.tagBoth(`tfc:${global.STONE_CHARACS.moon_deepslate.type}_items`)
			.mapColor(global.STONE_CHARACS.moon_deepslate.mapColor)
			.tagBlock('minecraft:mineable/pickaxe')
			.fullBlock(true)
			.opaque(true)
	})
	
	// Mars
	event.create('tfg:rock/cobble_mars_wall', 'wall')
		.soundType(global.STONE_CHARACS.mars.sound)
		.textureAll('ad_astra:block/mars_cobblestone')
		.tagBoth('tfg:rock_walls')
		.tagBoth(`tfc:${global.STONE_CHARACS.mars.type}_items`)
		.mapColor(global.STONE_CHARACS.mars.mapColor)
		.tagBlock('minecraft:mineable/pickaxe')
		.fullBlock(true)
		.opaque(true)
		
	event.create('tfg:rock/mossy_cobble_mars')
		.soundType(global.STONE_CHARACS.mars.sound)
		.tagBoth('forge:cobblestone')
		.tagBoth('forge:cobblestone/normal')
		.tagBoth(`tfc:${global.STONE_CHARACS.mars.type}_items`)
		.mapColor(global.STONE_CHARACS.mars.mapColor)
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('tfc:can_landslide')
		.fullBlock(true)
		.opaque(true)
	
	SHAPES.forEach(shape => {
		event.create(`tfg:rock/mossy_cobble_mars_${shape}`, shape)
			.soundType(global.STONE_CHARACS.mars.sound)
			.tagBoth(`tfg:rock_${shape}s`.replace(/ss/g, 's'))
			.tagBoth(`tfc:${global.STONE_CHARACS.mars.type}_items`)
			.mapColor(global.STONE_CHARACS.mars.mapColor)
			.tagBlock('minecraft:mineable/pickaxe')
			.fullBlock(true)
			.opaque(true)
	})

	// Venus
	event.create('tfg:rock/cobble_venus_wall', 'wall')
		.soundType(global.STONE_CHARACS.venus.sound)
		.textureAll('ad_astra:block/venus_cobblestone')
		.tagBoth('tfg:rock_walls')
		.tagBoth(`tfc:${global.STONE_CHARACS.venus.type}_items`)
		.mapColor(global.STONE_CHARACS.venus.mapColor)
		.tagBlock('minecraft:mineable/pickaxe')
		.fullBlock(true)
		.opaque(true)

	event.create('tfg:rock/mossy_cobble_venus')
		.soundType(global.STONE_CHARACS.venus.sound)
		.tagBoth('forge:cobblestone')
		.tagBoth('forge:cobblestone/normal')
		.tagBoth(`tfc:${global.STONE_CHARACS.venus.type}_items`)
		.mapColor(global.STONE_CHARACS.venus.mapColor)
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('tfc:can_landslide')
		.fullBlock(true)
		.opaque(true)
	
	SHAPES.forEach(shape => {
		event.create(`tfg:rock/mossy_cobble_venus_${shape}`, shape)
			.soundType(global.STONE_CHARACS.venus.sound)
			.tagBoth(`tfg:rock_${shape}s`.replace(/ss/g, 's'))
			.tagBoth(`tfc:${global.STONE_CHARACS.venus.type}_items`)
			.mapColor(global.STONE_CHARACS.venus.mapColor)
			.tagBlock('minecraft:mineable/pickaxe')
			.fullBlock(true)
			.opaque(true)
	})

	// Mercury
	event.create('tfg:rock/cobble_mercury_wall', 'wall')
		.soundType(global.STONE_CHARACS.mercury.sound)
		.textureAll('ad_astra:block/mercury_cobblestone')
		.tagBoth('tfg:rock_walls')
		.tagBoth(`tfc:${global.STONE_CHARACS.mercury.type}_items`)
		.mapColor(global.STONE_CHARACS.mercury.mapColor)
		.tagBlock('minecraft:mineable/pickaxe')
		.fullBlock(true)
		.opaque(true)

	event.create('tfg:rock/mossy_cobble_mercury')
		.soundType(global.STONE_CHARACS.mercury.sound)
		.tagBoth('forge:cobblestone')
		.tagBoth('forge:cobblestone/normal')
		.tagBoth(`tfc:${global.STONE_CHARACS.mercury.type}_items`)
		.mapColor(global.STONE_CHARACS.mercury.mapColor)
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('tfc:can_landslide')
		.fullBlock(true)
		.opaque(true)
	
	SHAPES.forEach(shape => {
		event.create(`tfg:rock/mossy_cobble_mercury_${shape}`, shape)
			.soundType(global.STONE_CHARACS.mercury.sound)
			.tagBoth(`tfg:rock_${shape}s`.replace(/ss/g, 's'))
			.tagBoth(`tfc:${global.STONE_CHARACS.mercury.type}_items`)
			.mapColor(global.STONE_CHARACS.mercury.mapColor)
			.tagBlock('minecraft:mineable/pickaxe')
			.fullBlock(true)
			.opaque(true)
	})
	
	// Glacio
	event.create('tfg:rock/cobble_glacio_wall', 'wall')
		.soundType(global.STONE_CHARACS.glacio.sound)
		.textureAll('ad_astra:block/glacio_cobblestone')
		.tagBoth('tfg:rock_walls')
		.tagBoth(`tfc:${global.STONE_CHARACS.glacio.type}_items`)
		.mapColor(global.STONE_CHARACS.glacio.mapColor)
		.tagBlock('minecraft:mineable/pickaxe')
		.fullBlock(true)
		.opaque(true)

	event.create('tfg:rock/mossy_cobble_glacio')
		.soundType(global.STONE_CHARACS.glacio.sound)
		.tagBoth('forge:cobblestone')
		.tagBoth('forge:cobblestone/normal')
		.tagBoth(`tfc:${global.STONE_CHARACS.glacio.type}_items`)
		.mapColor(global.STONE_CHARACS.glacio.mapColor)
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('tfc:can_landslide')
		.fullBlock(true)
		.opaque(true)
	
	SHAPES.forEach(shape => {
		event.create(`tfg:rock/mossy_cobble_glacio_${shape}`, shape)
			.soundType(global.STONE_CHARACS.glacio.sound)
			.tagBoth(`tfg:rock_${shape}s`.replace(/ss/g, 's'))
			.tagBoth(`tfc:${global.STONE_CHARACS.glacio.type}_items`)
			.mapColor(global.STONE_CHARACS.glacio.mapColor)
			.tagBlock('minecraft:mineable/pickaxe')
			.fullBlock(true)
			.opaque(true)
	})
	
	// Permafrost
	event.create('tfg:rock/cobble_permafrost')
		.soundType(global.STONE_CHARACS.permafrost.sound)
		.tagBoth('forge:cobblestone')
		.mapColor(global.STONE_CHARACS.permafrost.mapColor)
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('tfc:can_landslide')
		.fullBlock(true)
		.opaque(true)

	SHAPES.forEach(shape => {
		event.create(`tfg:rock/cobble_permafrost_${shape}`, shape)
			.textureAll('ad_astra:block/permafrost_top')
			.soundType(global.STONE_CHARACS.permafrost.sound)
			.tagBoth(`tfg:rock_${shape}s`.replace(/ss/g, 's'))
			.mapColor(global.STONE_CHARACS.permafrost.mapColor)
			.tagBlock('minecraft:mineable/pickaxe')
			.fullBlock(true)
			.opaque(true)
	})
	
	event.create('tfg:rock/mossy_cobble_permafrost')
		.soundType(global.STONE_CHARACS.permafrost.sound)
		.tagBoth('forge:cobblestone')
		.mapColor(global.STONE_CHARACS.permafrost.mapColor)
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('tfc:can_landslide')
		.fullBlock(true)
		.opaque(true)
	
	SHAPES.forEach(shape => {
		event.create(`tfg:rock/mossy_cobble_permafrost_${shape}`, shape)
			.soundType(global.STONE_CHARACS.permafrost.sound)
			.tagBoth(`tfg:rock_${shape}s`.replace(/ss/g, 's'))
			.mapColor(global.STONE_CHARACS.permafrost.mapColor)
			.tagBlock('minecraft:mineable/pickaxe')
			.fullBlock(true)
			.opaque(true)
	})

	// Red Granite
	SHAPES.forEach(shape => {
		event.create(`tfg:rock/cobble_red_granite_${shape}`, shape)
			.soundType(global.STONE_CHARACS.red_granite.sound)
			.textureAll('gtceu:block/stones/red_granite/cobble')
			.tagBoth(`tfg:rock_${shape}s`.replace(/ss/g, 's'))
			.tagBoth(`tfc:${global.STONE_CHARACS.red_granite.type}_items`)
			.mapColor(global.STONE_CHARACS.red_granite.mapColor)
			.tagBlock('minecraft:mineable/pickaxe')
			.fullBlock(true)
			.opaque(true)
	})
	
	SHAPES.forEach(shape => {
		event.create(`tfg:rock/mossy_cobble_red_granite_${shape}`, shape)
			.soundType(global.STONE_CHARACS.red_granite.sound)
			.textureAll('gtceu:block/stones/red_granite/cobble_mossy')
			.tagBoth(`tfg:rock_${shape}s`.replace(/ss/g, 's'))
			.tagBoth(`tfc:${global.STONE_CHARACS.red_granite.type}_items`)
			.mapColor(global.STONE_CHARACS.red_granite.mapColor)
			.tagBlock('minecraft:mineable/pickaxe')
			.fullBlock(true)
			.opaque(true)
	})
	
	// #endregion Cobblestones
	
	// #region Gravels
	event.create('tfg:rock/gravel_deepslate')
		.soundType('gravel')
		.tagBoth('forge:gravel')
		.tagBoth('tfc:rock/gravel')
		.tagBoth(`tfc:${global.STONE_CHARACS.deepslate.type}_items`)
		.mapColor(global.STONE_CHARACS.deepslate.mapColor)
		.tagBlock('minecraft:mineable/shovel')
		.tagBlock('tfc:can_landslide')
		.fullBlock(true)
		.opaque(true)

	event.create('tfg:rock/gravel_blackstone')
		.soundType('gravel')
		.tagBoth('forge:gravel')
		.tagBoth('tfc:rock/gravel')
		.tagBoth(`tfc:${global.STONE_CHARACS.blackstone.type}_items`)
		.mapColor(global.STONE_CHARACS.blackstone.mapColor)
		.tagBlock('minecraft:mineable/shovel')
		.tagBlock('tfc:can_landslide')
		.fullBlock(true)
		.opaque(true)

	event.create('tfg:rock/gravel_dripstone')
		.soundType('gravel')
		.tagBoth('forge:gravel')
		.tagBoth('tfc:rock/gravel')
		.tagBoth(`tfc:${global.STONE_CHARACS.dripstone.type}_items`)
		.mapColor(global.STONE_CHARACS.dripstone.mapColor)
		.tagBlock('minecraft:mineable/shovel')
		.tagBlock('tfc:can_landslide')
		.fullBlock(true)
		.opaque(true)

	event.create('tfg:rock/gravel_crackrack')
		.soundType('gravel')
		.tagBoth('forge:gravel')
		.tagBoth('tfc:rock/gravel')
		.tagBoth(`tfc:${global.STONE_CHARACS.crackrack.type}_items`)
		.mapColor(global.STONE_CHARACS.crackrack.mapColor)
		.tagBlock('minecraft:mineable/shovel')
		.tagBlock('tfc:can_landslide')
		.fullBlock(true)
		.opaque(true)

	event.create('tfg:rock/gravel_moon')
		.soundType('gravel')
		.tagBoth('forge:gravel')
		.tagBoth('tfc:rock/gravel')
		.tagBoth(`tfc:${global.STONE_CHARACS.moon.type}_items`)
		.mapColor(global.STONE_CHARACS.moon.mapColor)
		.tagBlock('minecraft:mineable/shovel')
		.tagBlock('tfc:can_landslide')
		.fullBlock(true)
		.opaque(true)

	event.create('tfg:rock/gravel_moon_deepslate')
		.soundType('gravel')
		.tagBoth('forge:gravel')
		.tagBoth('tfc:rock/gravel')
		.tagBoth(`tfc:${global.STONE_CHARACS.moon_deepslate.type}_items`)
		.mapColor(global.STONE_CHARACS.moon_deepslate.mapColor)
		.tagBlock('minecraft:mineable/shovel')
		.tagBlock('tfc:can_landslide')
		.fullBlock(true)
		.opaque(true)
	
	event.create('tfg:rock/gravel_mars')
		.soundType('gravel')
		.tagBoth('forge:gravel')
		.tagBoth('tfc:rock/gravel')
		.tagBoth(`tfc:${global.STONE_CHARACS.mars.type}_items`)
		.mapColor(global.STONE_CHARACS.mars.mapColor)
		.tagBlock('minecraft:mineable/shovel')
		.tagBlock('tfc:can_landslide')
		.fullBlock(true)
		.opaque(true)
	
	event.create('tfg:rock/gravel_venus')
		.soundType('gravel')
		.tagBoth('forge:gravel')
		.tagBoth('tfc:rock/gravel')
		.tagBoth(`tfc:${global.STONE_CHARACS.venus.type}_items`)
		.mapColor(global.STONE_CHARACS.venus.mapColor)
		.tagBlock('minecraft:mineable/shovel')
		.tagBlock('tfc:can_landslide')
		.fullBlock(true)
		.opaque(true)
	
	event.create('tfg:rock/gravel_mercury')
		.soundType('gravel')
		.tagBoth('forge:gravel')
		.tagBoth('tfc:rock/gravel')
		.tagBoth(`tfc:${global.STONE_CHARACS.mercury.type}_items`)
		.mapColor(global.STONE_CHARACS.mercury.mapColor)
		.tagBlock('minecraft:mineable/shovel')
		.tagBlock('tfc:can_landslide')
		.fullBlock(true)
		.opaque(true)

	event.create('tfg:rock/gravel_glacio')
		.soundType('gravel')
		.tagBoth('forge:gravel')
		.tagBoth('tfc:rock/gravel')
		.tagBoth(`tfc:${global.STONE_CHARACS.glacio.type}_items`)
		.mapColor(global.STONE_CHARACS.glacio.mapColor)
		.tagBlock('minecraft:mineable/shovel')
		.tagBlock('tfc:can_landslide')
		.fullBlock(true)
		.opaque(true)

	event.create('tfg:rock/gravel_permafrost')
		.soundType('gravel')
		.tagBoth('forge:gravel')
		.tagBoth('tfc:rock/gravel')
		.mapColor(global.STONE_CHARACS.permafrost.mapColor)
		.tagBlock('minecraft:mineable/shovel')
		.tagBlock('tfc:can_landslide')
		.fullBlock(true)
		.opaque(true)
	
	event.create('tfg:rock/gravel_red_granite')
		.soundType('gravel')
		.tagBoth('forge:gravel')
		.tagBoth('tfc:rock/gravel')
		.tagBoth(`tfc:${global.STONE_CHARACS.red_granite.type}_items`)
		.mapColor(global.STONE_CHARACS.red_granite.mapColor)
		.tagBlock('minecraft:mineable/shovel')
		.tagBlock('tfc:can_landslide')
		.fullBlock(true)
		.opaque(true)

	// #endregion Gravels
	
	// #region Smooth (Polished/Cut) Stones

	event.create('tfg:rock/polished_crackrack')
		.soundType(global.STONE_CHARACS.crackrack.sound)
		.tagBoth('forge:smooth_stone')
		.tagBoth('tfc:igneous_intrusive_items')
		.tagBoth('tfc:rock/smooth')
		.mapColor('crimson_stem')
		.tagBlock('minecraft:mineable/pickaxe')
		.fullBlock(true)
		.opaque(true)

	SHAPES.forEach(shape => {
		event.create(`tfg:rock/polished_crackrack_${shape}`, shape)
			.soundType(global.STONE_CHARACS.crackrack.sound)
			.tagBoth(`tfg:rock_${shape}s`.replace(/ss/g, 's'))
			.tagBoth(`tfc:${global.STONE_CHARACS.crackrack.type}_items`)
			.mapColor(global.STONE_CHARACS.crackrack.mapColor)
			.tagBlock('minecraft:mineable/pickaxe')
			.fullBlock(true)
			.opaque(true)
	})

	event.create('tfg:rock/polished_moon_wall', 'wall')
		.soundType(global.STONE_CHARACS.moon.sound)
		.textureAll('ad_astra:block/polished_moon_stone')
		.tagBoth('tfg:rock_walls')
		.tagBoth(`tfc:${global.STONE_CHARACS.moon.type}_items`)
		.mapColor(global.STONE_CHARACS.moon.mapColor)
		.tagBlock('minecraft:mineable/pickaxe')
		.fullBlock(true)
		.opaque(true)
	
	event.create('tfg:rock/polished_moon_deepslate')
		.soundType(global.STONE_CHARACS.moon_deepslate.sound)
		.tagBoth('forge:smooth_stone')
		.tagBoth(`tfc:${global.STONE_CHARACS.moon_deepslate.type}_items`)
		.tagBoth('tfc:rock/smooth')
		.mapColor(global.STONE_CHARACS.moon_deepslate.mapColor)
		.tagBlock('minecraft:mineable/pickaxe')
		.fullBlock(true)
		.opaque(true)
	
	SHAPES.forEach(shape => {
		event.create(`tfg:rock/polished_moon_deepslate_${shape}`, shape)
			.soundType(global.STONE_CHARACS.moon_deepslate.sound)
			.tagBoth(`tfg:rock_${shape}s`.replace(/ss/g, 's'))
			.tagBoth(`tfc:${global.STONE_CHARACS.moon_deepslate.type}_items`)
			.mapColor(global.STONE_CHARACS.moon_deepslate.mapColor)
			.tagBlock('minecraft:mineable/pickaxe')
			.fullBlock(true)
			.opaque(true)
	})

	event.create('tfg:rock/polished_mars_wall', 'wall')
		.soundType(global.STONE_CHARACS.mars.sound)
		.textureAll('ad_astra:block/polished_mars_stone')
		.tagBoth('tfg:rock_walls')
		.tagBoth(`tfc:${global.STONE_CHARACS.mars.type}_items`)
		.mapColor(global.STONE_CHARACS.mars.mapColor)
		.tagBlock('minecraft:mineable/pickaxe')
		.fullBlock(true)
		.opaque(true)

	event.create('tfg:rock/polished_venus_wall', 'wall')
		.soundType(global.STONE_CHARACS.venus.sound)
		.textureAll('ad_astra:block/polished_venus_stone')
		.tagBoth('tfg:rock_walls')
		.tagBoth(`tfc:${global.STONE_CHARACS.venus.type}_items`)
		.mapColor(global.STONE_CHARACS.venus.mapColor)
		.tagBlock('minecraft:mineable/pickaxe')
		.fullBlock(true)
		.opaque(true)

	event.create('tfg:rock/polished_mercury_wall', 'wall')
		.soundType(global.STONE_CHARACS.mercury.sound)
		.textureAll('ad_astra:block/polished_mercury_stone')
		.tagBoth('tfg:rock_walls')
		.tagBoth(`tfc:${global.STONE_CHARACS.mercury.type}_items`)
		.mapColor(global.STONE_CHARACS.mercury.mapColor)
		.tagBlock('minecraft:mineable/pickaxe')
		.fullBlock(true)
		.opaque(true)

	event.create('tfg:rock/polished_glacio_wall', 'wall')
		.soundType(global.STONE_CHARACS.glacio.sound)
		.textureAll('ad_astra:block/polished_glacio_stone')
		.tagBoth('tfg:rock_walls')
		.tagBoth(`tfc:${global.STONE_CHARACS.glacio.type}_items`)
		.mapColor(global.STONE_CHARACS.glacio.mapColor)
		.tagBlock('minecraft:mineable/pickaxe')
		.fullBlock(true)
		.opaque(true)

	event.create('tfg:rock/polished_permafrost_wall', 'wall')
		.soundType(global.STONE_CHARACS.permafrost.sound)
		.textureAll('ad_astra:block/polished_permafrost')
		.tagBoth('tfg:rock_walls')
		.tagBoth(`tfc:${global.STONE_CHARACS.permafrost.type}_items`)
		.mapColor(global.STONE_CHARACS.permafrost.mapColor)
		.tagBlock('minecraft:mineable/pickaxe')
		.fullBlock(true)
		.opaque(true)

	SHAPES.forEach(shape => {
		event.create(`tfg:rock/polished_red_granite_${shape}`, shape)
			.soundType(global.STONE_CHARACS.red_granite.sound)
			.textureAll('gtceu:block/stones/red_granite/polished')
			.tagBoth(`tfg:rock_${shape}s`.replace(/ss/g, 's'))
			.tagBoth(`tfc:${global.STONE_CHARACS.red_granite.type}_items`)
			.mapColor(global.STONE_CHARACS.red_granite.mapColor)
			.tagBlock('minecraft:mineable/pickaxe')
			.fullBlock(true)
			.opaque(true)
	})
	
	// #endregion Smooth (Polished/Cut) Stones
	
	// #region Bricks / Decorative

	// Deepslate
	SHAPES.forEach(shape => {
		event.create(`tfg:rock/cracked_bricks_deepslate_${shape}`, shape)
			.soundType(global.STONE_CHARACS.deepslate.sound)
			.textureAll('minecraft:block/cracked_deepslate_bricks')
			.tagBoth(`tfg:brick_${shape}`.replace(/ss/g, 's'))
			.tagBoth(`tfc:${global.STONE_CHARACS.deepslate.type}_items`)
			.mapColor(global.STONE_CHARACS.deepslate.mapColor)
			.tagBlock('minecraft:mineable/pickaxe')
			.fullBlock(true)
			.opaque(true)
	})

	SHAPES.forEach(shape => {
		event.create(`tfg:rock/cracked_tiles_deepslate_${shape}`, shape)
			.soundType(global.STONE_CHARACS.deepslate.sound)
			.textureAll('minecraft:block/cracked_deepslate_tiles')
			.tagBoth(`tfg:brick_${shape}`.replace(/ss/g, 's'))
			.tagBoth(`tfc:${global.STONE_CHARACS.deepslate.type}_items`)
			.mapColor(global.STONE_CHARACS.deepslate.mapColor)
			.tagBlock('minecraft:mineable/pickaxe')
			.fullBlock(true)
			.opaque(true)
	})

	event.create('tfg:rock/mossy_bricks_deepslate')
		.soundType(global.STONE_CHARACS.deepslate.sound)
		.tagBoth('minecraft:stone_bricks')
		.tagBoth('forge:stone_bricks')
		.tagBoth('tfc:rock/bricks')
		.tagBoth('tfc:rock/mossy_bricks')
		.tagBoth(`tfc:${global.STONE_CHARACS.deepslate.type}_items`)
		.mapColor(global.STONE_CHARACS.deepslate.mapColor)
		.tagBlock('minecraft:mineable/pickaxe')
		.fullBlock(true)
		.opaque(true)

	SHAPES.forEach(shape => {
		event.create(`tfg:rock/mossy_bricks_deepslate_${shape}`, shape)
			.soundType(global.STONE_CHARACS.deepslate.sound)
			.tagBoth(`tfg:brick_${shape}`.replace(/ss/g, 's'))
			.tagBoth(`tfc:${global.STONE_CHARACS.deepslate.type}_items`)
			.mapColor(global.STONE_CHARACS.deepslate.mapColor)
			.tagBlock('minecraft:mineable/pickaxe')
			.fullBlock(true)
			.opaque(true)
	})

	// Blackstone
	SHAPES.forEach(shape => {
		event.create(`tfg:rock/cracked_bricks_blackstone_${shape}`, shape)
			.soundType(global.STONE_CHARACS.blackstone.sound)
			.textureAll('minecraft:block/cracked_polished_blackstone_bricks')
			.tagBoth(`tfg:brick_${shape}`.replace(/ss/g, 's'))
			.tagBoth(`tfc:${global.STONE_CHARACS.blackstone.type}_items`)
			.mapColor(global.STONE_CHARACS.blackstone.mapColor)
			.tagBlock('minecraft:mineable/pickaxe')
			.fullBlock(true)
			.opaque(true)
	})

	event.create('tfg:rock/mossy_bricks_blackstone')
		.soundType(global.STONE_CHARACS.blackstone.sound)
		.tagBoth('minecraft:stone_bricks')
		.tagBoth('forge:stone_bricks')
		.tagBoth('tfc:rock/bricks')
		.tagBoth('tfc:rock/mossy_bricks')
		.tagBoth(`tfc:${global.STONE_CHARACS.blackstone.type}_items`)
		.mapColor(global.STONE_CHARACS.blackstone.mapColor)
		.tagBlock('minecraft:mineable/pickaxe')
		.fullBlock(true)
		.opaque(true)

	SHAPES.forEach(shape => {
		event.create(`tfg:rock/mossy_bricks_blackstone_${shape}`, shape)
			.soundType(global.STONE_CHARACS.blackstone.sound)
			.tagBoth(`tfg:brick_${shape}`.replace(/ss/g, 's'))
			.tagBoth(`tfc:${global.STONE_CHARACS.blackstone.type}_items`)
			.mapColor(global.STONE_CHARACS.blackstone.mapColor)
			.tagBlock('minecraft:mineable/pickaxe')
			.fullBlock(true)
			.opaque(true)
	})

	// Dripstone
	event.create('tfg:rock/cracked_bricks_dripstone')
		.soundType(global.STONE_CHARACS.dripstone.sound)
		.tagBoth('minecraft:stone_bricks')
		.tagBoth('forge:stone_bricks')
		.tagBoth('tfc:rock/bricks')
		.tagBoth('tfc:rock/mossy_bricks')
		.tagBoth(`tfc:${global.STONE_CHARACS.dripstone.type}_items`)
		.mapColor(global.STONE_CHARACS.dripstone.mapColor)
		.tagBlock('minecraft:mineable/pickaxe')
		.fullBlock(true)
		.opaque(true)

	SHAPES.forEach(shape => {
		event.create(`tfg:rock/cracked_bricks_dripstone_${shape}`, shape)
			.soundType(global.STONE_CHARACS.dripstone.sound)
			.tagBoth(`tfg:brick_${shape}`.replace(/ss/g, 's'))
			.tagBoth(`tfc:${global.STONE_CHARACS.dripstone.type}_items`)
			.mapColor(global.STONE_CHARACS.dripstone.mapColor)
			.tagBlock('minecraft:mineable/pickaxe')
			.fullBlock(true)
			.opaque(true)
	})

	event.create('tfg:rock/mossy_bricks_dripstone')
		.soundType(global.STONE_CHARACS.dripstone.sound)
		.tagBoth('minecraft:stone_bricks')
		.tagBoth('forge:stone_bricks')
		.tagBoth('tfc:rock/bricks')
		.tagBoth('tfc:rock/mossy_bricks')
		.tagBoth(`tfc:${global.STONE_CHARACS.dripstone.type}_items`)
		.mapColor(global.STONE_CHARACS.dripstone.mapColor)
		.tagBlock('minecraft:mineable/pickaxe')
		.fullBlock(true)
		.opaque(true)

	SHAPES.forEach(shape => {
		event.create(`tfg:rock/mossy_bricks_dripstone_${shape}`, shape)
			.soundType(global.STONE_CHARACS.dripstone.sound)
			.tagBoth(`tfg:brick_${shape}`.replace(/ss/g, 's'))
			.tagBoth(`tfc:${global.STONE_CHARACS.dripstone.type}_items`)
			.mapColor(global.STONE_CHARACS.dripstone.mapColor)
			.tagBlock('minecraft:mineable/pickaxe')
			.fullBlock(true)
			.opaque(true)
	})

	// Crackrack
	SHAPES.forEach(shape => {
		event.create(`tfg:rock/cracked_bricks_nether_${shape}`, shape)
			.soundType(global.STONE_CHARACS.nether.sound)
			.textureAll('minecraft:block/cracked_nether_bricks')
			.tagBoth(`tfg:brick_${shape}`.replace(/ss/g, 's'))
			.tagBoth(`tfc:${global.STONE_CHARACS.nether.type}_items`)
			.mapColor(global.STONE_CHARACS.nether.mapColor)
			.tagBlock('minecraft:mineable/pickaxe')
			.fullBlock(true)
			.opaque(true)
	})

	event.create('tfg:rock/mossy_bricks_nether')
		.soundType(global.STONE_CHARACS.nether.sound)
		.tagBoth('minecraft:stone_bricks')
		.tagBoth('forge:stone_bricks')
		.tagBoth('tfc:rock/bricks')
		.tagBoth('tfc:rock/mossy_bricks')
		.tagBoth(`tfc:${global.STONE_CHARACS.nether.type}_items`)
		.mapColor(global.STONE_CHARACS.nether.mapColor)
		.tagBlock('minecraft:mineable/pickaxe')
		.fullBlock(true)
		.opaque(true)

	SHAPES.forEach(shape => {
		event.create(`tfg:rock/mossy_bricks_nether_${shape}`, shape)
			.soundType(global.STONE_CHARACS.nether.sound)
			.tagBoth(`tfg:brick_${shape}`.replace(/ss/g, 's'))
			.tagBoth(`tfc:${global.STONE_CHARACS.nether.type}_items`)
			.mapColor(global.STONE_CHARACS.nether.mapColor)
			.tagBlock('minecraft:mineable/pickaxe')
			.fullBlock(true)
			.opaque(true)
	})

	// Moon Stone
	SHAPES.forEach(shape => {
		event.create(`tfg:rock/cracked_bricks_moon_${shape}`, shape)
			.soundType(global.STONE_CHARACS.moon.sound)
			.textureAll('ad_astra:block/cracked_moon_stone_bricks')
			.tagBoth(`tfg:brick_${shape}`.replace(/ss/g, 's'))
			.tagBoth(`tfc:${global.STONE_CHARACS.moon.type}_items`)
			.mapColor(global.STONE_CHARACS.moon.mapColor)
			.tagBlock('minecraft:mineable/pickaxe')
			.fullBlock(true)
			.opaque(true)
	})

	event.create('tfg:rock/mossy_bricks_moon')
		.soundType(global.STONE_CHARACS.moon.sound)
		.tagBoth('minecraft:stone_bricks')
		.tagBoth('forge:stone_bricks')
		.tagBoth('tfc:rock/bricks')
		.tagBoth('tfc:rock/mossy_bricks')
		.tagBoth(`tfc:${global.STONE_CHARACS.moon.type}_items`)
		.mapColor(global.STONE_CHARACS.moon.mapColor)
		.tagBlock('minecraft:mineable/pickaxe')
		.fullBlock(true)
		.opaque(true)

	SHAPES.forEach(shape => {
		event.create(`tfg:rock/mossy_bricks_moon_${shape}`, shape)
			.soundType(global.STONE_CHARACS.moon.sound)
			.tagBoth(`tfg:brick_${shape}`.replace(/ss/g, 's'))
			.tagBoth(`tfc:${global.STONE_CHARACS.moon.type}_items`)
			.mapColor(global.STONE_CHARACS.moon.mapColor)
			.tagBlock('minecraft:mineable/pickaxe')
			.fullBlock(true)
			.opaque(true)
	})

	event.create('tfg:rock/chiseled_bricks_moon_wall', 'wall')
		.soundType(global.STONE_CHARACS.moon.sound)
		.textureAll('ad_astra:block/chiseled_moon_stone_bricks')
		.tagBoth('tfg:brick_walls')
		.tagBoth(`tfc:${global.STONE_CHARACS.moon.type}_items`)
		.mapColor(global.STONE_CHARACS.moon.mapColor)
		.tagBlock('minecraft:mineable/pickaxe')
		.fullBlock(true)
		.opaque(true)

	// Moon Deepslate
	event.create('tfg:rock/bricks_moon_deepslate')
		.soundType(global.STONE_CHARACS.moon_deepslate.sound)
		.tagBoth('minecraft:stone_bricks')
		.tagBoth('forge:stone_bricks')
		.tagBoth('tfc:rock/bricks')
		.tagBoth(`tfc:${global.STONE_CHARACS.moon_deepslate.type}_items`)
		.mapColor(global.STONE_CHARACS.moon_deepslate.mapColor)
		.tagBlock('minecraft:mineable/pickaxe')
		.fullBlock(true)
		.opaque(true)

	SHAPES.forEach(shape => {
		event.create(`tfg:rock/bricks_moon_deepslate_${shape}`, shape)
			.soundType(global.STONE_CHARACS.moon_deepslate.sound)
			.tagBoth(`tfg:brick_${shape}`.replace(/ss/g, 's'))
			.tagBoth(`tfc:${global.STONE_CHARACS.moon_deepslate.type}_items`)
			.mapColor(global.STONE_CHARACS.moon_deepslate.mapColor)
			.tagBlock('minecraft:mineable/pickaxe')
			.fullBlock(true)
			.opaque(true)
	})

	event.create('tfg:rock/cracked_bricks_moon_deepslate')
		.soundType(global.STONE_CHARACS.moon_deepslate.sound)
		.tagBoth('minecraft:stone_bricks')
		.tagBoth('forge:stone_bricks')
		.tagBoth('tfc:rock/bricks')
		.tagBoth('tfc:rock/cracked_bricks')
		.tagBoth(`tfc:${global.STONE_CHARACS.moon_deepslate.type}_items`)
		.mapColor(global.STONE_CHARACS.moon_deepslate.mapColor)
		.tagBlock('minecraft:mineable/pickaxe')
		.fullBlock(true)
		.opaque(true)
	
	SHAPES.forEach(shape => {
		event.create(`tfg:rock/cracked_bricks_moon_deepslate_${shape}`, shape)
			.soundType(global.STONE_CHARACS.moon_deepslate.sound)
			.tagBoth(`tfg:brick_${shape}`.replace(/ss/g, 's'))
			.tagBoth(`tfc:${global.STONE_CHARACS.moon_deepslate.type}_items`)
			.mapColor(global.STONE_CHARACS.moon_deepslate.mapColor)
			.tagBlock('minecraft:mineable/pickaxe')
			.fullBlock(true)
			.opaque(true)
	})

	event.create('tfg:rock/mossy_bricks_moon_deepslate')
		.soundType(global.STONE_CHARACS.moon_deepslate.sound)
		.tagBoth('minecraft:stone_bricks')
		.tagBoth('forge:stone_bricks')
		.tagBoth('tfc:rock/bricks')
		.tagBoth('tfc:rock/mossy_bricks')
		.tagBoth(`tfc:${global.STONE_CHARACS.moon_deepslate.type}_items`)
		.mapColor(global.STONE_CHARACS.moon_deepslate.mapColor)
		.tagBlock('minecraft:mineable/pickaxe')
		.fullBlock(true)
		.opaque(true)
	
	SHAPES.forEach(shape => {
		event.create(`tfg:rock/mossy_bricks_moon_deepslate_${shape}`, shape)
			.soundType(global.STONE_CHARACS.moon_deepslate.sound)
			.tagBoth(`tfg:brick_${shape}`.replace(/ss/g, 's'))
			.tagBoth(`tfc:${global.STONE_CHARACS.moon_deepslate.type}_items`)
			.mapColor(global.STONE_CHARACS.moon_deepslate.mapColor)
			.tagBlock('minecraft:mineable/pickaxe')
			.fullBlock(true)
			.opaque(true)
	})

	event.create('tfg:rock/chiseled_bricks_moon_deepslate')
		.soundType(global.STONE_CHARACS.moon_deepslate.sound)
		.tagBoth('minecraft:stone_bricks')
		.tagBoth('forge:stone_bricks')
		.tagBoth('tfc:rock/bricks')
		.tagBoth('tfc:rock/chiseled_bricks')
		.tagBoth(`tfc:${global.STONE_CHARACS.moon_deepslate.type}_items`)
		.mapColor(global.STONE_CHARACS.moon_deepslate.mapColor)
		.tagBlock('minecraft:mineable/pickaxe')
		.fullBlock(true)
		.opaque(true)

	SHAPES.forEach(shape => {
		event.create(`tfg:rock/chiseled_bricks_moon_deepslate_${shape}`, shape)
			.soundType(global.STONE_CHARACS.moon_deepslate.sound)
			.tagBoth(`tfg:brick_${shape}`.replace(/ss/g, 's'))
			.tagBoth(`tfc:${global.STONE_CHARACS.moon_deepslate.type}_items`)
			.mapColor(global.STONE_CHARACS.moon_deepslate.mapColor)
			.tagBlock('minecraft:mineable/pickaxe')
			.fullBlock(true)
			.opaque(true)
	})
	
	event.create('tfg:rock/pillar_moon_deepslate')
		.soundType(global.STONE_CHARACS.moon_deepslate.sound)
		.property(BlockProperties.AXIS)
		.placementState(event => event.set(BlockProperties.AXIS, event.clickedFace.axis))
		.tagBoth(`tfc:${global.STONE_CHARACS.moon_deepslate.type}_items`)
		.mapColor(global.STONE_CHARACS.moon_deepslate.mapColor)
		.tagBlock('minecraft:mineable/pickaxe')
		.fullBlock(true)
		.opaque(true)
	
	// Mars Stone
	SHAPES.forEach(shape => {
		event.create(`tfg:rock/cracked_bricks_mars_${shape}`, shape)
			.soundType(global.STONE_CHARACS.mars.sound)
			.textureAll('ad_astra:block/cracked_mars_stone_bricks')
			.tagBoth(`tfg:brick_${shape}`.replace(/ss/g, 's'))
			.tagBoth(`tfc:${global.STONE_CHARACS.mars.type}_items`)
			.mapColor(global.STONE_CHARACS.mars.mapColor)
			.tagBlock('minecraft:mineable/pickaxe')
			.fullBlock(true)
			.opaque(true)
	})

	event.create('tfg:rock/mossy_bricks_mars')
		.soundType(global.STONE_CHARACS.mars.sound)
		.tagBoth('minecraft:stone_bricks')
		.tagBoth('forge:stone_bricks')
		.tagBoth('tfc:rock/bricks')
		.tagBoth('tfc:rock/mossy_bricks')
		.tagBoth(`tfc:${global.STONE_CHARACS.mars.type}_items`)
		.mapColor(global.STONE_CHARACS.mars.mapColor)
		.tagBlock('minecraft:mineable/pickaxe')
		.fullBlock(true)
		.opaque(true)

	SHAPES.forEach(shape => {
		event.create(`tfg:rock/mossy_bricks_mars_${shape}`, shape)
			.soundType(global.STONE_CHARACS.mars.sound)
			.tagBoth(`tfg:brick_${shape}`.replace(/ss/g, 's'))
			.tagBoth(`tfc:${global.STONE_CHARACS.mars.type}_items`)
			.mapColor(global.STONE_CHARACS.mars.mapColor)
			.tagBlock('minecraft:mineable/pickaxe')
			.fullBlock(true)
			.opaque(true)
	})

	event.create('tfg:rock/chiseled_bricks_mars_wall', 'wall')
		.soundType(global.STONE_CHARACS.mars.sound)
		.textureAll('ad_astra:block/chiseled_mars_stone_bricks')
		.tagBoth('tfg:brick_walls')
		.tagBoth(`tfc:${global.STONE_CHARACS.mars.type}_items`)
		.mapColor(global.STONE_CHARACS.mars.mapColor)
		.tagBlock('minecraft:mineable/pickaxe')
		.fullBlock(true)
		.opaque(true)
	
	// Venus Stone
	SHAPES.forEach(shape => {
		event.create(`tfg:rock/cracked_bricks_venus_${shape}`, shape)
			.soundType(global.STONE_CHARACS.venus.sound)
			.textureAll('ad_astra:block/cracked_venus_stone_bricks')
			.tagBoth(`tfg:brick_${shape}`.replace(/ss/g, 's'))
			.tagBoth(`tfc:${global.STONE_CHARACS.venus.type}_items`)
			.mapColor(global.STONE_CHARACS.venus.mapColor)
			.tagBlock('minecraft:mineable/pickaxe')
			.fullBlock(true)
			.opaque(true)
	})

	event.create('tfg:rock/mossy_bricks_venus')
		.soundType(global.STONE_CHARACS.venus.sound)
		.tagBoth('minecraft:stone_bricks')
		.tagBoth('forge:stone_bricks')
		.tagBoth('tfc:rock/bricks')
		.tagBoth('tfc:rock/mossy_bricks')
		.tagBoth(`tfc:${global.STONE_CHARACS.venus.type}_items`)
		.mapColor(global.STONE_CHARACS.venus.mapColor)
		.tagBlock('minecraft:mineable/pickaxe')
		.fullBlock(true)
		.opaque(true)

	SHAPES.forEach(shape => {
		event.create(`tfg:rock/mossy_bricks_venus_${shape}`, shape)
			.soundType(global.STONE_CHARACS.venus.sound)
			.tagBoth(`tfg:brick_${shape}`.replace(/ss/g, 's'))
			.tagBoth(`tfc:${global.STONE_CHARACS.venus.type}_items`)
			.mapColor(global.STONE_CHARACS.venus.mapColor)
			.tagBlock('minecraft:mineable/pickaxe')
			.fullBlock(true)
			.opaque(true)
	})

	event.create('tfg:rock/chiseled_bricks_venus_wall', 'wall')
		.soundType(global.STONE_CHARACS.venus.sound)
		.textureAll('ad_astra:block/chiseled_venus_stone_bricks')
		.tagBoth('tfg:brick_walls')
		.tagBoth(`tfc:${global.STONE_CHARACS.venus.type}_items`)
		.mapColor(global.STONE_CHARACS.venus.mapColor)
		.tagBlock('minecraft:mineable/pickaxe')
		.fullBlock(true)
		.opaque(true)
	
	// Mercury Stone
	SHAPES.forEach(shape => {
		event.create(`tfg:rock/cracked_bricks_mercury_${shape}`, shape)
			.soundType(global.STONE_CHARACS.mercury.sound)
			.textureAll('ad_astra:block/cracked_mercury_stone_bricks')
			.tagBoth(`tfg:brick_${shape}`.replace(/ss/g, 's'))
			.tagBoth(`tfc:${global.STONE_CHARACS.mercury.type}_items`)
			.mapColor(global.STONE_CHARACS.mercury.mapColor)
			.tagBlock('minecraft:mineable/pickaxe')
			.fullBlock(true)
			.opaque(true)
	})

	event.create('tfg:rock/mossy_bricks_mercury')
		.soundType(global.STONE_CHARACS.mercury.sound)
		.tagBoth('minecraft:stone_bricks')
		.tagBoth('forge:stone_bricks')
		.tagBoth('tfc:rock/bricks')
		.tagBoth('tfc:rock/mossy_bricks')
		.tagBoth(`tfc:${global.STONE_CHARACS.mercury.type}_items`)
		.mapColor(global.STONE_CHARACS.mercury.mapColor)
		.tagBlock('minecraft:mineable/pickaxe')
		.fullBlock(true)
		.opaque(true)

	SHAPES.forEach(shape => {
		event.create(`tfg:rock/mossy_bricks_mercury_${shape}`, shape)
			.soundType(global.STONE_CHARACS.mercury.sound)
			.tagBoth(`tfg:brick_${shape}`.replace(/ss/g, 's'))
			.tagBoth(`tfc:${global.STONE_CHARACS.mercury.type}_items`)
			.mapColor(global.STONE_CHARACS.mercury.mapColor)
			.tagBlock('minecraft:mineable/pickaxe')
			.fullBlock(true)
			.opaque(true)
	})

	event.create('tfg:rock/chiseled_bricks_mercury_wall', 'wall')
		.soundType(global.STONE_CHARACS.mercury.sound)
		.textureAll('ad_astra:block/chiseled_mercury_stone_bricks')
		.tagBoth('tfg:brick_walls')
		.tagBoth(`tfc:${global.STONE_CHARACS.mercury.type}_items`)
		.mapColor(global.STONE_CHARACS.mercury.mapColor)
		.tagBlock('minecraft:mineable/pickaxe')
		.fullBlock(true)
		.opaque(true)
	
	// Glacio Stone
	SHAPES.forEach(shape => {
		event.create(`tfg:rock/cracked_bricks_glacio_${shape}`, shape)
			.soundType(global.STONE_CHARACS.glacio.sound)
			.textureAll('ad_astra:block/cracked_glacio_stone_bricks')
			.tagBoth(`tfg:brick_${shape}`.replace(/ss/g, 's'))
			.tagBoth(`tfc:${global.STONE_CHARACS.glacio.type}_items`)
			.mapColor(global.STONE_CHARACS.glacio.mapColor)
			.tagBlock('minecraft:mineable/pickaxe')
			.fullBlock(true)
			.opaque(true)
	})

	event.create('tfg:rock/mossy_bricks_glacio')
		.soundType(global.STONE_CHARACS.glacio.sound)
		.tagBoth('minecraft:stone_bricks')
		.tagBoth('forge:stone_bricks')
		.tagBoth('tfc:rock/bricks')
		.tagBoth('tfc:rock/mossy_bricks')
		.tagBoth(`tfc:${global.STONE_CHARACS.glacio.type}_items`)
		.mapColor(global.STONE_CHARACS.glacio.mapColor)
		.tagBlock('minecraft:mineable/pickaxe')
		.fullBlock(true)
		.opaque(true)

	SHAPES.forEach(shape => {
		event.create(`tfg:rock/mossy_bricks_glacio_${shape}`, shape)
			.soundType(global.STONE_CHARACS.glacio.sound)
			.tagBoth(`tfg:brick_${shape}`.replace(/ss/g, 's'))
			.tagBoth(`tfc:${global.STONE_CHARACS.glacio.type}_items`)
			.mapColor(global.STONE_CHARACS.glacio.mapColor)
			.tagBlock('minecraft:mineable/pickaxe')
			.fullBlock(true)
			.opaque(true)
	})

	event.create('tfg:rock/chiseled_bricks_glacio_wall', 'wall')
		.soundType(global.STONE_CHARACS.glacio.sound)
		.textureAll('ad_astra:block/chiseled_glacio_stone_bricks')
		.tagBoth('tfg:brick_walls')
		.tagBoth(`tfc:${global.STONE_CHARACS.glacio.type}_items`)
		.mapColor(global.STONE_CHARACS.glacio.mapColor)
		.tagBlock('minecraft:mineable/pickaxe')
		.fullBlock(true)
		.opaque(true)
	
	// Permafrost
	SHAPES.forEach(shape => {
		event.create(`tfg:rock/cracked_bricks_permafrost_${shape}`, shape)
			.soundType(global.STONE_CHARACS.permafrost.sound)
			.textureAll('ad_astra:block/cracked_permafrost_bricks')
			.tagBoth(`tfg:brick_${shape}`.replace(/ss/g, 's'))
			.tagBoth(`tfc:${global.STONE_CHARACS.permafrost.type}_items`)
			.mapColor(global.STONE_CHARACS.permafrost.mapColor)
			.tagBlock('minecraft:mineable/pickaxe')
			.fullBlock(true)
			.opaque(true)
	})

	event.create('tfg:rock/mossy_bricks_permafrost')
		.soundType(global.STONE_CHARACS.permafrost.sound)
		.tagBoth('minecraft:stone_bricks')
		.tagBoth('forge:stone_bricks')
		.tagBoth('tfc:rock/bricks')
		.tagBoth('tfc:rock/mossy_bricks')
		.mapColor(global.STONE_CHARACS.permafrost.mapColor)
		.tagBlock('minecraft:mineable/pickaxe')
		.fullBlock(true)
		.opaque(true)

	SHAPES.forEach(shape => {
		event.create(`tfg:rock/mossy_bricks_permafrost_${shape}`, shape)
			.soundType(global.STONE_CHARACS.permafrost.sound)
			.tagBoth(`tfg:brick_${shape}`.replace(/ss/g, 's'))
			.mapColor(global.STONE_CHARACS.permafrost.mapColor)
			.tagBlock('minecraft:mineable/pickaxe')
			.fullBlock(true)
			.opaque(true)
	})

	event.create('tfg:rock/chiseled_bricks_permafrost_wall', 'wall')
		.soundType(global.STONE_CHARACS.permafrost.sound)
		.textureAll('ad_astra:block/chiseled_permafrost_bricks')
		.tagBoth('tfg:brick_walls')
		.mapColor(global.STONE_CHARACS.permafrost.mapColor)
		.tagBlock('minecraft:mineable/pickaxe')
		.fullBlock(true)
		.opaque(true)

	// Red Granite
	
	SHAPES.forEach(shape => {
		event.create(`tfg:rock/bricks_red_granite_${shape}`, shape)
			.soundType(global.STONE_CHARACS.red_granite.sound)
			.textureAll('gtceu:block/stones/red_granite/bricks')
			.tagBoth(`tfg:brick_${shape}`.replace(/ss/g, 's'))
			.tagBoth(`tfc:${global.STONE_CHARACS.red_granite.type}_items`)
			.mapColor(global.STONE_CHARACS.red_granite.mapColor)
			.tagBlock('minecraft:mineable/pickaxe')
			.fullBlock(true)
			.opaque(true)
	})
	
	SHAPES.forEach(shape => {
		event.create(`tfg:rock/cracked_bricks_red_granite_${shape}`, shape)
			.soundType(global.STONE_CHARACS.red_granite.sound)
			.textureAll('gtceu:block/stones/red_granite/bricks_cracked')
			.tagBoth(`tfg:brick_${shape}`.replace(/ss/g, 's'))
			.tagBoth(`tfc:${global.STONE_CHARACS.red_granite.type}_items`)
			.mapColor(global.STONE_CHARACS.red_granite.mapColor)
			.tagBlock('minecraft:mineable/pickaxe')
			.fullBlock(true)
			.opaque(true)
	})

	SHAPES.forEach(shape => {
		event.create(`tfg:rock/mossy_bricks_red_granite_${shape}`, shape)
			.soundType(global.STONE_CHARACS.red_granite.sound)
			.textureAll('gtceu:block/stones/red_granite/bricks_mossy')
			.tagBoth(`tfg:brick_${shape}`.replace(/ss/g, 's'))
			.tagBoth(`tfc:${global.STONE_CHARACS.red_granite.type}_items`)
			.mapColor(global.STONE_CHARACS.red_granite.mapColor)
			.tagBlock('minecraft:mineable/pickaxe')
			.fullBlock(true)
			.opaque(true)
	})

	// #endregion Bricks / Decorative

	// #region Sandstone
	event.create('tfg:rock/smooth_red_sandstone_wall', 'wall')
		.soundType('stone')
		.textureAll('minecraft:block/red_sandstone_top')
		.mapColor('teracotta_red')
		.tagBlock('minecraft:mineable/pickaxe')
		.fullBlock(true)
		.opaque(true)

	event.create('tfg:rock/cut_red_sandstone_stairs', 'stairs')
		.soundType('stone')
		.textureAll('minecraft:block/cut_red_sandstone')
		.mapColor('teracotta_red')
		.tagBlock('minecraft:mineable/pickaxe')
		.fullBlock(true)
		.opaque(true)
		
	event.create('tfg:rock/cut_red_sandstone_wall', 'wall')
		.soundType('stone')
		.textureAll('minecraft:block/cut_red_sandstone')
		.mapColor('teracotta_red')
		.tagBlock('minecraft:mineable/pickaxe')
		.fullBlock(true)
		.opaque(true)

	event.create('tfg:rock/bricks_venus_sandstone_wall', 'wall')
		.soundType('stone')
		.textureAll('ad_astra:block/venus_sandstone_bricks')
		.mapColor(global.STONE_CHARACS.venus.mapColor)
		.tagBlock('minecraft:mineable/pickaxe')
		.fullBlock(true)
		.opaque(true)

	SHAPES.forEach(shape => {
		event.create(`tfg:rock/cracked_bricks_venus_sandstone_${shape}`, shape)
			.soundType(global.STONE_CHARACS.venus.sound)
			.textureAll('ad_astra:block/cracked_venus_sandstone_bricks')
			.tagBoth(`tfg:brick_${shape}`.replace(/ss/g, 's'))
			.mapColor(global.STONE_CHARACS.venus.mapColor)
			.tagBlock('minecraft:mineable/pickaxe')
			.fullBlock(true)
			.opaque(true)
	})

	// #endregion Sandstone

}