// priority: 0
"use strict";

global.FRAMEDBLOCKS_DISABLED_ITEMS = [
    "framedblocks:framed_soul_torch",
    "framedblocks:framed_torch",
    "framedblocks:framed_obsidian_pressure_plate",
];

/** @satisfies {Special.Item[]} */
global.FRAMED_HALF_BLOCKS = /** @type {const} */ ([
    "framedblocks:framed_slope",
    "framedblocks:framed_corner_slope",
    "framedblocks:framed_prism_corner",
    "framedblocks:framed_threeway_corner",
    "framedblocks:framed_slab",
    "framedblocks:framed_divided_slab",
    "framedblocks:framed_panel",
    "framedblocks:framed_divided_panel_horizontal",
    "framedblocks:framed_divided_panel_vertical",
    "framedblocks:framed_half_stairs",
    "framedblocks:framed_double_half_stairs",
    "framedblocks:framed_vertical_half_stairs",
    "framedblocks:framed_vertical_double_half_stairs",
    "framedblocks:framed_lattice_block",
    "framedblocks:framed_half_pillar",
    "framedblocks:framed_post",
    "framedblocks:framed_prism",
    "framedblocks:framed_sloped_prism",
    "framedblocks:framed_double_slope_slab",
    "framedblocks:framed_compound_slope_slab",
    "framedblocks:framed_inv_double_slope_slab",
    "framedblocks:framed_flat_inner_slope_slab_corner",
    "framedblocks:framed_flat_double_slope_slab_corner",
    "framedblocks:framed_double_slope_panel",
    "framedblocks:framed_compound_slope_panel",
    "framedblocks:framed_inv_double_slope_panel",
    "framedblocks:framed_flat_inner_slope_panel_corner",
    "framedblocks:framed_flat_double_slope_panel_corner",
    "framedblocks:framed_flat_inv_double_slope_panel_corner",
    "framedblocks:framed_pyramid_slab",
    "framedblocks:framed_half_slope",
    "framedblocks:framed_double_half_slope",
    "framedblocks:framed_centered_slab",
    "framedblocks:framed_centered_panel",
    "framedblocks:framed_checkered_slab",
    "framedblocks:framed_checkered_panel",
]);

/** @satisfies {Special.Item[]} */
global.FRAMED_TINY_BLOCKS = /** @type {const} */ ([
    "framedblocks:framed_slope_edge",
    "framedblocks:framed_slab_edge",
    "framedblocks:framed_slab_corner",
    "framedblocks:framed_corner_pillar",
    "framedblocks:framed_button",
    "framedblocks:framed_stone_button",
    "framedblocks:framed_floor_board",
    "framedblocks:framed_wall_board",
    "framedblocks:framed_corner_strip",
    "framedblocks:framed_pane",
    "framedblocks:framed_bars",
    "framedblocks:framed_horizontal_pane",
    "framedblocks:framed_slope_slab",
    "framedblocks:framed_flat_slope_slab_corner",
    "framedblocks:framed_slope_panel",
    "framedblocks:framed_flat_slope_panel_corner",
    "framedblocks:framed_small_corner_slope_panel",
    "framedblocks:framed_small_inner_corner_slope_panel",
    "framedblocks:framed_small_double_corner_slope_panel",
    "framedblocks:framed_mini_cube",
]);
