# Config options for jellie stats.
entities:
  biotiteJellie:
    # Maximum familiarity that a wild jellie can reach.
    # Default: 1
    familiarityCap: 1.0

    # How many days it takes a jellie to reach adulthood.
    # Default: 16
    adulthoodDays: 16

    # How many uses a jellie has before becoming old.
    # Default: 120
    uses: 120

    # Does jellie eat rotten food.
    # Default: false
    eatsRottenFood: false

    # How long it takes for a jellie to produce products.
    # Default: 23500
    produceTicks: 23500

    # Minimum familiarity needed for jellie to produce products.
    # Default: 0.15
    produceFamiliarity: 0.15

    # How many children a jellie can have at once.
    # Default: 1
    childCount: 2

    # How long it takes for a jellie to be born.
    # Default: 32
    gestationDays: 16

  certusJellie:
    # Maximum familiarity that a wild jellie can reach.
    # Default: 1
    familiarityCap: 1.0

    # How many days it takes a jellie to reach adulthood.
    # Default: 16
    adulthoodDays: 16

    # How many uses a jellie has before becoming old.
    # Default: 120
    uses: 120

    # Does jellie eat rotten food.
    # Default: false
    eatsRottenFood: false

    # How long it takes for a jellie to produce products.
    # Default: 23500
    produceTicks: 23500

    # Minimum familiarity needed for jellie to produce products.
    # Default: 0.15
    produceFamiliarity: 0.15

    # How many children a jellie can have at once.
    # Default: 1
    childCount: 2

    # How long it takes for a jellie to be born.
    # Default: 32
    gestationDays: 16

  glowberryJellie:
    # Maximum familiarity that a wild jellie can reach.
    # Default: 1
    familiarityCap: 1.0

    # How many days it takes a jellie to reach adulthood.
    # Default: 16
    adulthoodDays: 16

    # How many uses a jellie has before becoming old.
    # Default: 120
    uses: 120

    # Does jellie eat rotten food.
    # Default: false
    eatsRottenFood: false

    # How long it takes for a jellie to produce products.
    # Default: 23500
    produceTicks: 23500

    # Minimum familiarity needed for jellie to produce products.
    # Default: 0.15
    produceFamiliarity: 0.15

    # How many children a jellie can have at once.
    # Default: 1
    childCount: 2

    # How long it takes for a jellie to be born.
    # Default: 32
    gestationDays: 16

  herbalJellie:
    # Maximum familiarity that a wild jellie can reach.
    # Default: 1
    familiarityCap: 1.0

    # How many days it takes a jellie to reach adulthood.
    # Default: 16
    adulthoodDays: 16

    # How many uses a jellie has before becoming old.
    # Default: 120
    uses: 120

    # Does jellie eat rotten food.
    # Default: false
    eatsRottenFood: false

    # How long it takes for a jellie to produce products.
    # Default: 23500
    produceTicks: 23500

    # Minimum familiarity needed for jellie to produce products.
    # Default: 0.15
    produceFamiliarity: 0.15

    # How many children a jellie can have at once.
    # Default: 1
    childCount: 2

    # How long it takes for a jellie to be born.
    # Default: 32
    gestationDays: 16

  iceJellie:
    # Maximum familiarity that a wild jellie can reach.
    # Default: 1
    familiarityCap: 1.0

    # How many days it takes a jellie to reach adulthood.
    # Default: 16
    adulthoodDays: 16

    # How many uses a jellie has before becoming old.
    # Default: 120
    uses: 120

    # Does jellie eat rotten food.
    # Default: false
    eatsRottenFood: false

    # How long it takes for a jellie to produce products.
    # Default: 23500
    produceTicks: 23500

    # Minimum familiarity needed for jellie to produce products.
    # Default: 0.15
    produceFamiliarity: 0.15

    # How many children a jellie can have at once.
    # Default: 1
    childCount: 2

    # How long it takes for a jellie to be born.
    # Default: 32
    gestationDays: 16

  latexJellie:
    # Maximum familiarity that a wild jellie can reach.
    # Default: 1
    familiarityCap: 1.0

    # How many days it takes a jellie to reach adulthood.
    # Default: 16
    adulthoodDays: 16

    # How many uses a jellie has before becoming old.
    # Default: 120
    uses: 120

    # Does jellie eat rotten food.
    # Default: false
    eatsRottenFood: false

    # How long it takes for a jellie to produce products.
    # Default: 23500
    produceTicks: 23500

    # Minimum familiarity needed for jellie to produce products.
    # Default: 0.15
    produceFamiliarity: 0.15

    # How many children a jellie can have at once.
    # Default: 1
    childCount: 2

    # How long it takes for a jellie to be born.
    # Default: 32
    gestationDays: 16

  lavaJellie:
    # Maximum familiarity that a wild jellie can reach.
    # Default: 1
    familiarityCap: 1.0

    # How many days it takes a jellie to reach adulthood.
    # Default: 16
    adulthoodDays: 16

    # How many uses a jellie has before becoming old.
    # Default: 120
    uses: 120

    # Does jellie eat rotten food.
    # Default: false
    eatsRottenFood: false

    # How long it takes for a jellie to produce products.
    # Default: 23500
    produceTicks: 23500

    # Minimum familiarity needed for jellie to produce products.
    # Default: 0.15
    produceFamiliarity: 0.15

    # How many children a jellie can have at once.
    # Default: 1
    childCount: 2

    # How long it takes for a jellie to be born.
    # Default: 32
    gestationDays: 16

  penteticJellie:
    # Maximum familiarity that a wild jellie can reach.
    # Default: 1
    familiarityCap: 1.0

    # How many days it takes a jellie to reach adulthood.
    # Default: 16
    adulthoodDays: 16

    # How many uses a jellie has before becoming old.
    # Default: 120
    uses: 120

    # Does jellie eat rotten food.
    # Default: false
    eatsRottenFood: false

    # How long it takes for a jellie to produce products.
    # Default: 23500
    produceTicks: 23500

    # Minimum familiarity needed for jellie to produce products.
    # Default: 0.15
    produceFamiliarity: 0.15

    # How many children a jellie can have at once.
    # Default: 1
    childCount: 2

    # How long it takes for a jellie to be born.
    # Default: 32
    gestationDays: 16

  phosphorumJellie:
    # Maximum familiarity that a wild jellie can reach.
    # Default: 1
    familiarityCap: 1.0

    # How many days it takes a jellie to reach adulthood.
    # Default: 16
    adulthoodDays: 16

    # How many uses a jellie has before becoming old.
    # Default: 120
    uses: 120

    # Does jellie eat rotten food.
    # Default: false
    eatsRottenFood: false

    # How long it takes for a jellie to produce products.
    # Default: 23500
    produceTicks: 23500

    # Minimum familiarity needed for jellie to produce products.
    # Default: 0.15
    produceFamiliarity: 0.15

    # How many children a jellie can have at once.
    # Default: 1
    childCount: 2

    # How long it takes for a jellie to be born.
    # Default: 32
    gestationDays: 16

  plantJellie:
    # Maximum familiarity that a wild jellie can reach.
    # Default: 1
    familiarityCap: 1.0

    # How many days it takes a jellie to reach adulthood.
    # Default: 16
    adulthoodDays: 16

    # How many uses a jellie has before becoming old.
    # Default: 120
    uses: 120

    # Does jellie eat rotten food.
    # Default: false
    eatsRottenFood: false

    # How long it takes for a jellie to produce products.
    # Default: 23500
    produceTicks: 23500

    # Minimum familiarity needed for jellie to produce products.
    # Default: 0.15
    produceFamiliarity: 0.15

    # How many children a jellie can have at once.
    # Default: 1
    childCount: 2

    # How long it takes for a jellie to be born.
    # Default: 32
    gestationDays: 16

  rockJellie:
    # Maximum familiarity that a wild jellie can reach.
    # Default: 1
    familiarityCap: 1.0

    # How many days it takes a jellie to reach adulthood.
    # Default: 16
    adulthoodDays: 16

    # How many uses a jellie has before becoming old.
    # Default: 120
    uses: 120

    # Does jellie eat rotten food.
    # Default: false
    eatsRottenFood: false

    # How long it takes for a jellie to produce products.
    # Default: 23500
    produceTicks: 23500

    # Minimum familiarity needed for jellie to produce products.
    # Default: 0.15
    produceFamiliarity: 0.15

    # How many children a jellie can have at once.
    # Default: 1
    childCount: 2

    # How long it takes for a jellie to be born.
    # Default: 32
    gestationDays: 16

  springJellie:
    # Maximum familiarity that a wild jellie can reach.
    # Default: 1
    familiarityCap: 1.0

    # How many days it takes a jellie to reach adulthood.
    # Default: 16
    adulthoodDays: 16

    # How many uses a jellie has before becoming old.
    # Default: 120
    uses: 120

    # Does jellie eat rotten food.
    # Default: false
    eatsRottenFood: false

    # How long it takes for a jellie to produce products.
    # Default: 23500
    produceTicks: 23500

    # Minimum familiarity needed for jellie to produce products.
    # Default: 0.15
    produceFamiliarity: 0.15

    # How many children a jellie can have at once.
    # Default: 1
    childCount: 2

    # How long it takes for a jellie to be born.
    # Default: 32
    gestationDays: 16

  pyritieJellie:
    # Maximum familiarity that a wild jellie can reach.
    # Default: 1
    familiarityCap: 1.0

    # How many days it takes a jellie to reach adulthood.
    # Default: 16
    adulthoodDays: 16

    # How many uses a jellie has before becoming old.
    # Default: 120
    uses: 120

    # Does jellie eat rotten food.
    # Default: false
    eatsRottenFood: false

    # How long it takes for a jellie to produce products.
    # Default: 23500
    produceTicks: 23500

    # Minimum familiarity needed for jellie to produce products.
    # Default: 0.15
    produceFamiliarity: 0.15

    # How many children a jellie can have at once.
    # Default: 1
    childCount: 2

    # How long it takes for a jellie to be born.
    # Default: 32
    gestationDays: 16

  redeixJellie:
    # Maximum familiarity that a wild jellie can reach.
    # Default: 1
    familiarityCap: 1.0

    # How many days it takes a jellie to reach adulthood.
    # Default: 16
    adulthoodDays: 16

    # How many uses a jellie has before becoming old.
    # Default: 120
    uses: 120

    # Does jellie eat rotten food.
    # Default: false
    eatsRottenFood: false

    # How long it takes for a jellie to produce products.
    # Default: 23500
    produceTicks: 23500

    # Minimum familiarity needed for jellie to produce products.
    # Default: 0.15
    produceFamiliarity: 0.15

    # How many children a jellie can have at once.
    # Default: 1
    childCount: 2

    # How long it takes for a jellie to be born.
    # Default: 32
    gestationDays: 16

  tetoJellie:
    # Maximum familiarity that a wild jellie can reach.
    # Default: 1
    familiarityCap: 1.0

    # How many days it takes a jellie to reach adulthood.
    # Default: 16
    adulthoodDays: 16

    # How many uses a jellie has before becoming old.
    # Default: 120
    uses: 120

    # Does jellie eat rotten food.
    # Default: false
    eatsRottenFood: false

    # How long it takes for a jellie to produce products.
    # Default: 23500
    produceTicks: 23500

    # Minimum familiarity needed for jellie to produce products.
    # Default: 0.15
    produceFamiliarity: 0.15

    # How many children a jellie can have at once.
    # Default: 1
    childCount: 2

    # How long it takes for a jellie to be born.
    # Default: 32
    gestationDays: 16

