#Percentage chance for a water particle to spawn each tick that the player is wet. 0 to turn off
#Range: 0 ~ 100
drippiness = 30
#For all ARGB values, set to 00000000 to disable the feature in that season
#Change temperature display to Fahrenheit.
useFahrenheit = false
#Offset the GUI elements. Useful if you're using a resource pack that changes the health or hunger bars
#Range: 0.0 ~ 3.4028234663852886E38
guiOffset = 8.0

