// priority: 0

global.SPECIES_DISABLED_BLOCKS = [
	'species:red_suspicious_sand',
	'species:bone_bark',
	'species:bone_vertebra',
	'species:bone_spike',
	'species:alphacene_moss_block',
	'species:alphacene_moss_carpet',
	'species:alphacene_grass_block',
	'species:alphacene_mushroom_block',
	'species:alphacene_mushroom_growth',
	'species:cruncher_pellet',
	'species:frozen_meat',
	'species:frozen_hair'
];

global.SPECIES_DISABLED_ITEMS = [
	'species:deepfish_bucket',
	'species:bone_spike',
	'species:ancient_pinecone',
	'species:petrified_egg',
	'species:alphacene_grass',
	'species:alphacene_tall_grass',
	'species:alphacene_mushroom',
	'species:cruncher_egg',
	'species:ichor_bottle',
	'species:youth_potion',
	'species:springling_egg',
	'species:wraptor_egg',
	'species:chaindelier',
	'species:spectralibur_pedestal',
	'species:wicked_candle',
	'species:bewereager_head',
	'species:quake_head',
	'species:ghoul_head',
	'species:deflector_dummy',
	'species:wicked_mask',
	'species:wicked_swapper',
	'species:spectralibur',
	'species:ricoshield',
	'species:smoke_bomb',
	'species:wicked_dope',
	'species:cracked_wraptor_egg',
	'species:monster_meal',
	'species:wicked_treat',
	'species:ghoul_tongue',
	'species:broken_links',
	'species:werefang',
	'species:wicked_wax',
	'species:kinetic_core'
];