// priority: 0

/**
 * Список хранит предметы, 
 * у которых должны быть удалены тэги и они должны быть скрыты в REI.
 */
global.TFC_DISABLED_ITEMS = [
    // Blocks
    'tfc:metal/block/bismuth', 
    'tfc:metal/block/bismuth_bronze', 
    'tfc:metal/block/black_bronze', 
    'tfc:metal/block/bronze', 
    'tfc:metal/block/brass', 
    'tfc:metal/block/copper', 
    'tfc:metal/block/gold', 
    'tfc:metal/block/nickel', 
    'tfc:metal/block/rose_gold', 
    'tfc:metal/block/silver', 
    'tfc:metal/block/tin', 
    'tfc:metal/block/zinc', 
    'tfc:metal/block/sterling_silver', 
    'tfc:metal/block/wrought_iron', 
    'tfc:metal/block/cast_iron', 
    'tfc:metal/block/steel', 
    'tfc:metal/block/black_steel', 
    'tfc:metal/block/blue_steel', 
    'tfc:metal/block/red_steel',

    // Stairs
    'tfc:metal/block/bismuth_stairs', 
    'tfc:metal/block/bismuth_bronze_stairs', 
    'tfc:metal/block/black_bronze_stairs', 
    'tfc:metal/block/bronze_stairs', 
    'tfc:metal/block/brass_stairs', 
    'tfc:metal/block/copper_stairs', 
    'tfc:metal/block/gold_stairs', 
    'tfc:metal/block/nickel_stairs', 
    'tfc:metal/block/rose_gold_stairs', 
    'tfc:metal/block/silver_stairs', 
    'tfc:metal/block/tin_stairs', 
    'tfc:metal/block/zinc_stairs', 
    'tfc:metal/block/sterling_silver_stairs', 
    'tfc:metal/block/wrought_iron_stairs', 
    'tfc:metal/block/cast_iron_stairs', 
    'tfc:metal/block/steel_stairs', 
    'tfc:metal/block/black_steel_stairs', 
    'tfc:metal/block/blue_steel_stairs', 
    'tfc:metal/block/red_steel_stairs',

    // Slabs
    'tfc:metal/block/bismuth_slab', 
    'tfc:metal/block/bismuth_bronze_slab', 
    'tfc:metal/block/black_bronze_slab', 
    'tfc:metal/block/bronze_slab', 
    'tfc:metal/block/brass_slab', 
    'tfc:metal/block/copper_slab', 
    'tfc:metal/block/gold_slab', 
    'tfc:metal/block/nickel_slab', 
    'tfc:metal/block/rose_gold_slab', 
    'tfc:metal/block/silver_slab', 
    'tfc:metal/block/tin_slab', 
    'tfc:metal/block/zinc_slab', 
    'tfc:metal/block/sterling_silver_slab', 
    'tfc:metal/block/wrought_iron_slab', 
    'tfc:metal/block/cast_iron_slab', 
    'tfc:metal/block/steel_slab', 
    'tfc:metal/block/black_steel_slab', 
    'tfc:metal/block/blue_steel_slab', 
    'tfc:metal/block/red_steel_slab',

    // Ingots
    "tfc:metal/ingot/bismuth",
    "tfc:metal/ingot/bismuth_bronze",
    "tfc:metal/ingot/black_bronze",
    "tfc:metal/ingot/bronze",
    "tfc:metal/ingot/rose_gold",
    "tfc:metal/ingot/sterling_silver",
    "tfc:metal/ingot/wrought_iron",
    "tfc:metal/ingot/steel",
    "tfc:metal/ingot/black_steel",
    "tfc:metal/ingot/red_steel",
    "tfc:metal/ingot/blue_steel",
    "tfc:metal/ingot/brass",
    "tfc:metal/ingot/nickel",
    "tfc:metal/ingot/silver",
    "tfc:metal/ingot/tin",
    "tfc:metal/ingot/zinc",
    "tfc:metal/ingot/cast_iron",
    "tfc:metal/ingot/copper",
    "tfc:metal/ingot/gold",

    // Double Ingots
    "tfc:metal/double_ingot/bismuth",
    "tfc:metal/double_ingot/bismuth_bronze",
    "tfc:metal/double_ingot/black_bronze",
    "tfc:metal/double_ingot/bronze",
    "tfc:metal/double_ingot/rose_gold",
    "tfc:metal/double_ingot/sterling_silver",
    "tfc:metal/double_ingot/wrought_iron",
    "tfc:metal/double_ingot/steel",
    "tfc:metal/double_ingot/black_steel",
    "tfc:metal/double_ingot/red_steel",
    "tfc:metal/double_ingot/blue_steel",
    "tfc:metal/double_ingot/brass",
    "tfc:metal/double_ingot/nickel",
    "tfc:metal/double_ingot/silver",
    "tfc:metal/double_ingot/tin",
    "tfc:metal/double_ingot/zinc",
    "tfc:metal/double_ingot/cast_iron",
    "tfc:metal/double_ingot/copper",
    "tfc:metal/double_ingot/gold",
    
    // Sheets
    "tfc:metal/sheet/bismuth",
    "tfc:metal/sheet/bismuth_bronze",
    "tfc:metal/sheet/black_bronze",
    "tfc:metal/sheet/bronze",
    "tfc:metal/sheet/rose_gold",
    "tfc:metal/sheet/sterling_silver",
    "tfc:metal/sheet/wrought_iron",
    "tfc:metal/sheet/cast_iron",
    "tfc:metal/sheet/steel",
    "tfc:metal/sheet/black_steel",
    "tfc:metal/sheet/red_steel",
    "tfc:metal/sheet/blue_steel",
    "tfc:metal/sheet/brass",
    "tfc:metal/sheet/copper",
    "tfc:metal/sheet/gold",
    "tfc:metal/sheet/nickel",
    "tfc:metal/sheet/silver",
    "tfc:metal/sheet/tin",
    "tfc:metal/sheet/zinc",
    "tfc:metal/sheet/cast_iron",
    
    // Double Sheets
    "tfc:metal/double_sheet/bismuth",
    "tfc:metal/double_sheet/bismuth_bronze",
    "tfc:metal/double_sheet/black_bronze",
    "tfc:metal/double_sheet/bronze",
    "tfc:metal/double_sheet/rose_gold",
    "tfc:metal/double_sheet/sterling_silver",
    "tfc:metal/double_sheet/wrought_iron",
    "tfc:metal/double_sheet/cast_iron",
    "tfc:metal/double_sheet/steel",
    "tfc:metal/double_sheet/black_steel",
    "tfc:metal/double_sheet/red_steel",
    "tfc:metal/double_sheet/blue_steel",
    "tfc:metal/double_sheet/brass",
    "tfc:metal/double_sheet/copper",
    "tfc:metal/double_sheet/gold",
    "tfc:metal/double_sheet/nickel",
    "tfc:metal/double_sheet/silver",
    "tfc:metal/double_sheet/tin",
    "tfc:metal/double_sheet/zinc",
    "tfc:metal/double_sheet/cast_iron",
    
    // Rods
    "tfc:metal/rod/bismuth",
    "tfc:metal/rod/bismuth_bronze",
    "tfc:metal/rod/black_bronze",
    "tfc:metal/rod/bronze",
    "tfc:metal/rod/rose_gold",
    "tfc:metal/rod/sterling_silver",
    "tfc:metal/rod/wrought_iron",
    "tfc:metal/rod/cast_iron",
    "tfc:metal/rod/steel",
    "tfc:metal/rod/black_steel",
    "tfc:metal/rod/red_steel",
    "tfc:metal/rod/blue_steel",
    "tfc:metal/rod/brass",
    "tfc:metal/rod/copper",
    "tfc:metal/rod/gold",
    "tfc:metal/rod/nickel",
    "tfc:metal/rod/silver",
    "tfc:metal/rod/tin",
    "tfc:metal/rod/zinc",
    "tfc:metal/rod/cast_iron",
    
    // Tool Heads
    // Copper
    'tfc:metal/pickaxe/copper', 
    'tfc:metal/pickaxe_head/copper', 
    'tfc:metal/axe/copper', 
    'tfc:metal/axe_head/copper', 
    'tfc:metal/shovel/copper', 
    'tfc:metal/shovel_head/copper', 
    'tfc:metal/hoe/copper', 
    'tfc:metal/hoe_head/copper', 
    'tfc:metal/hammer/copper', 
    'tfc:metal/hammer_head/copper', 
    'tfc:metal/saw/copper', 
    'tfc:metal/saw_blade/copper', 
    'tfc:metal/sword/copper', 
    'tfc:metal/sword_blade/copper', 
    'tfc:metal/knife/copper', 
    'tfc:metal/knife_blade/copper', 
    'tfc:metal/scythe/copper', 
    'tfc:metal/scythe_blade/copper',

    // Bismuth Bronze
    'tfc:metal/pickaxe/bismuth_bronze', 
    'tfc:metal/pickaxe_head/bismuth_bronze', 
    'tfc:metal/axe/bismuth_bronze', 
    'tfc:metal/axe_head/bismuth_bronze', 
    'tfc:metal/shovel/bismuth_bronze', 
    'tfc:metal/shovel_head/bismuth_bronze', 
    'tfc:metal/hoe/bismuth_bronze', 
    'tfc:metal/hoe_head/bismuth_bronze', 
    'tfc:metal/hammer/bismuth_bronze', 
    'tfc:metal/hammer_head/bismuth_bronze', 
    'tfc:metal/saw/bismuth_bronze', 
    'tfc:metal/saw_blade/bismuth_bronze', 
    'tfc:metal/sword/bismuth_bronze', 
    'tfc:metal/sword_blade/bismuth_bronze', 
    'tfc:metal/knife/bismuth_bronze', 
    'tfc:metal/knife_blade/bismuth_bronze', 
    'tfc:metal/scythe/bismuth_bronze', 
    'tfc:metal/scythe_blade/bismuth_bronze',

    // Bronze
    'tfc:metal/pickaxe/bronze', 
    'tfc:metal/pickaxe_head/bronze', 
    'tfc:metal/axe/bronze', 
    'tfc:metal/axe_head/bronze', 
    'tfc:metal/shovel/bronze', 
    'tfc:metal/shovel_head/bronze', 
    'tfc:metal/hoe/bronze', 
    'tfc:metal/hoe_head/bronze', 
    'tfc:metal/hammer/bronze', 
    'tfc:metal/hammer_head/bronze', 
    'tfc:metal/saw/bronze', 
    'tfc:metal/saw_blade/bronze', 
    'tfc:metal/sword/bronze', 
    'tfc:metal/sword_blade/bronze', 
    'tfc:metal/knife/bronze', 
    'tfc:metal/knife_blade/bronze', 
    'tfc:metal/scythe/bronze', 
    'tfc:metal/scythe_blade/bronze',

    // Black Bronze
    'tfc:metal/pickaxe/black_bronze', 
    'tfc:metal/pickaxe_head/black_bronze', 
    'tfc:metal/axe/black_bronze', 
    'tfc:metal/axe_head/black_bronze', 
    'tfc:metal/shovel/black_bronze', 
    'tfc:metal/shovel_head/black_bronze', 
    'tfc:metal/hoe/black_bronze', 
    'tfc:metal/hoe_head/black_bronze', 
    'tfc:metal/hammer/black_bronze', 
    'tfc:metal/hammer_head/black_bronze', 
    'tfc:metal/saw/black_bronze', 
    'tfc:metal/saw_blade/black_bronze', 
    'tfc:metal/sword/black_bronze', 
    'tfc:metal/sword_blade/black_bronze', 
    'tfc:metal/knife/black_bronze', 
    'tfc:metal/knife_blade/black_bronze', 
    'tfc:metal/scythe/black_bronze', 
    'tfc:metal/scythe_blade/black_bronze',

    // Wrought Iron
    'tfc:metal/pickaxe/wrought_iron', 
    'tfc:metal/pickaxe_head/wrought_iron', 
    'tfc:metal/axe/wrought_iron', 
    'tfc:metal/axe_head/wrought_iron', 
    'tfc:metal/shovel/wrought_iron', 
    'tfc:metal/shovel_head/wrought_iron', 
    'tfc:metal/hoe/wrought_iron', 
    'tfc:metal/hoe_head/wrought_iron', 
    'tfc:metal/hammer/wrought_iron', 
    'tfc:metal/hammer_head/wrought_iron', 
    'tfc:metal/saw/wrought_iron', 
    'tfc:metal/saw_blade/wrought_iron', 
    'tfc:metal/sword/wrought_iron', 
    'tfc:metal/sword_blade/wrought_iron', 
    'tfc:metal/knife/wrought_iron', 
    'tfc:metal/knife_blade/wrought_iron', 
    'tfc:metal/scythe/wrought_iron', 
    'tfc:metal/scythe_blade/wrought_iron',

    // Steel
    'tfc:metal/pickaxe/steel', 
    'tfc:metal/pickaxe_head/steel', 
    'tfc:metal/axe/steel', 
    'tfc:metal/axe_head/steel', 
    'tfc:metal/shovel/steel', 
    'tfc:metal/shovel_head/steel', 
    'tfc:metal/hoe/steel', 
    'tfc:metal/hoe_head/steel', 
    'tfc:metal/hammer/steel', 
    'tfc:metal/hammer_head/steel', 
    'tfc:metal/saw/steel', 
    'tfc:metal/saw_blade/steel', 
    'tfc:metal/sword/steel', 
    'tfc:metal/sword_blade/steel', 
    'tfc:metal/knife/steel', 
    'tfc:metal/knife_blade/steel', 
    'tfc:metal/scythe/steel', 
    'tfc:metal/scythe_blade/steel',

    // Black Steel
    'tfc:metal/pickaxe/black_steel', 
    'tfc:metal/pickaxe_head/black_steel', 
    'tfc:metal/axe/black_steel', 
    'tfc:metal/axe_head/black_steel', 
    'tfc:metal/shovel/black_steel', 
    'tfc:metal/shovel_head/black_steel', 
    'tfc:metal/hoe/black_steel', 
    'tfc:metal/hoe_head/black_steel', 
    'tfc:metal/hammer/black_steel', 
    'tfc:metal/hammer_head/black_steel', 
    'tfc:metal/saw/black_steel', 
    'tfc:metal/saw_blade/black_steel', 
    'tfc:metal/sword/black_steel', 
    'tfc:metal/sword_blade/black_steel', 
    'tfc:metal/knife/black_steel', 
    'tfc:metal/knife_blade/black_steel', 
    'tfc:metal/scythe/black_steel', 
    'tfc:metal/scythe_blade/black_steel',

    // Red Steel
    'tfc:metal/pickaxe/red_steel', 
    'tfc:metal/pickaxe_head/red_steel', 
    'tfc:metal/axe/red_steel', 
    'tfc:metal/axe_head/red_steel', 
    'tfc:metal/shovel/red_steel', 
    'tfc:metal/shovel_head/red_steel', 
    'tfc:metal/hoe/red_steel', 
    'tfc:metal/hoe_head/red_steel', 
    'tfc:metal/hammer/red_steel', 
    'tfc:metal/hammer_head/red_steel', 
    'tfc:metal/saw/red_steel', 
    'tfc:metal/saw_blade/red_steel', 
    'tfc:metal/sword/red_steel', 
    'tfc:metal/sword_blade/red_steel', 
    'tfc:metal/knife/red_steel', 
    'tfc:metal/knife_blade/red_steel', 
    'tfc:metal/scythe/red_steel', 
    'tfc:metal/scythe_blade/red_steel',

    // Blue Steel
    'tfc:metal/pickaxe/blue_steel', 
    'tfc:metal/pickaxe_head/blue_steel', 
    'tfc:metal/axe/blue_steel', 
    'tfc:metal/axe_head/blue_steel', 
    'tfc:metal/shovel/blue_steel', 
    'tfc:metal/shovel_head/blue_steel', 
    'tfc:metal/hoe/blue_steel', 
    'tfc:metal/hoe_head/blue_steel', 
    'tfc:metal/hammer/blue_steel', 
    'tfc:metal/hammer_head/blue_steel', 
    'tfc:metal/saw/blue_steel', 
    'tfc:metal/saw_blade/blue_steel', 
    'tfc:metal/sword/blue_steel', 
    'tfc:metal/sword_blade/blue_steel', 
    'tfc:metal/knife/blue_steel', 
    'tfc:metal/knife_blade/blue_steel', 
    'tfc:metal/scythe/blue_steel', 
    'tfc:metal/scythe_blade/blue_steel',
    
    // Ores
    'tfc:ore/poor_native_copper', 
    'tfc:ore/normal_native_copper', 
    'tfc:ore/rich_native_copper',
    'tfc:ore/poor_native_gold', 
    'tfc:ore/normal_native_gold', 
    'tfc:ore/rich_native_gold', 
    'tfc:ore/poor_hematite', 
    'tfc:ore/normal_hematite', 
    'tfc:ore/rich_hematite', 
    'tfc:ore/rich_tetrahedrite', 
    'tfc:ore/normal_tetrahedrite', 
    'tfc:ore/poor_tetrahedrite',
    'tfc:ore/rich_sphalerite', 
    'tfc:ore/normal_sphalerite', 
    'tfc:ore/poor_sphalerite', 
    'tfc:ore/rich_limonite', 
    'tfc:ore/normal_limonite', 
    'tfc:ore/poor_limonite', 
    'tfc:ore/rich_magnetite', 
    'tfc:ore/normal_magnetite', 
    'tfc:ore/poor_magnetite', 
    'tfc:ore/rich_malachite', 
    'tfc:ore/normal_malachite', 
    'tfc:ore/poor_malachite', 
    'tfc:ore/rich_garnierite', 
    'tfc:ore/normal_garnierite', 
    'tfc:ore/poor_garnierite', 
    'tfc:ore/rich_bismuthinite', 
    'tfc:ore/normal_bismuthinite', 
    'tfc:ore/poor_bismuthinite', 
    'tfc:ore/rich_cassiterite', 
    'tfc:ore/normal_cassiterite', 
    'tfc:ore/poor_cassiterite', 
    'tfc:ore/rich_native_silver', 
    'tfc:ore/normal_native_silver', 
    'tfc:ore/poor_native_silver',

    // Gems
    'tfc:gem/amethyst', 
    'tfc:gem/diamond', 
    'tfc:gem/lapis_lazuli', 
    'tfc:gem/emerald', 
    'tfc:gem/pyrite', 
    'tfc:gem/opal', 
    'tfc:gem/ruby', 
    'tfc:gem/sapphire', 
    'tfc:gem/topaz', 
    'tfc:ore/amethyst', 
    'tfc:ore/diamond', 
    'tfc:ore/lapis_lazuli', 
    'tfc:ore/emerald', 
    'tfc:ore/pyrite', 
    'tfc:ore/opal', 
    'tfc:ore/ruby', 
    'tfc:ore/sapphire', 
    'tfc:ore/topaz',

    'tfc:ore/graphite', 
    'tfc:ore/sulfur', 
    'tfc:ore/cinnabar', 
    'tfc:ore/cryolite', 
    'tfc:ore/saltpeter', 
    'tfc:ore/borax', 
    'tfc:ore/sylvite',
    'tfc:ore/bituminous_coal',
    'tfc:ore/lignite',
    'tfc:ore/halite',

    // Axles
    'tfc:wood/axle/acacia',
    'tfc:wood/axle/ash',
    'tfc:wood/axle/aspen',
    'tfc:wood/axle/birch',
    'tfc:wood/axle/blackwood',
    'tfc:wood/axle/chestnut',
    'tfc:wood/axle/douglas_fir',
    'tfc:wood/axle/hickory',
    'tfc:wood/axle/kapok',
    'tfc:wood/axle/mangrove',
    'tfc:wood/axle/maple',
    'tfc:wood/axle/oak',
    'tfc:wood/axle/palm',
    'tfc:wood/axle/pine',
    'tfc:wood/axle/rosewood',
    'tfc:wood/axle/sequoia',
    'tfc:wood/axle/spruce',
    'tfc:wood/axle/sycamore',
    'tfc:wood/axle/white_cedar',
    'tfc:wood/axle/willow',

    // Bladed Axles
    'tfc:wood/bladed_axle/acacia',
    'tfc:wood/bladed_axle/ash',
    'tfc:wood/bladed_axle/aspen',
    'tfc:wood/bladed_axle/birch',
    'tfc:wood/bladed_axle/blackwood',
    'tfc:wood/bladed_axle/chestnut',
    'tfc:wood/bladed_axle/douglas_fir',
    'tfc:wood/bladed_axle/hickory',
    'tfc:wood/bladed_axle/kapok',
    'tfc:wood/bladed_axle/mangrove',
    'tfc:wood/bladed_axle/maple',
    'tfc:wood/bladed_axle/oak',
    'tfc:wood/bladed_axle/palm',
    'tfc:wood/bladed_axle/pine',
    'tfc:wood/bladed_axle/rosewood',
    'tfc:wood/bladed_axle/sequoia',
    'tfc:wood/bladed_axle/spruce',
    'tfc:wood/bladed_axle/sycamore',
    'tfc:wood/bladed_axle/white_cedar',
    'tfc:wood/bladed_axle/willow',

    // Encased Axles
    'tfc:wood/encased_axle/acacia',
    'tfc:wood/encased_axle/ash',
    'tfc:wood/encased_axle/aspen',
    'tfc:wood/encased_axle/birch',
    'tfc:wood/encased_axle/blackwood',
    'tfc:wood/encased_axle/chestnut',
    'tfc:wood/encased_axle/douglas_fir',
    'tfc:wood/encased_axle/hickory',
    'tfc:wood/encased_axle/kapok',
    'tfc:wood/encased_axle/mangrove',
    'tfc:wood/encased_axle/maple',
    'tfc:wood/encased_axle/oak',
    'tfc:wood/encased_axle/palm',
    'tfc:wood/encased_axle/pine',
    'tfc:wood/encased_axle/rosewood',
    'tfc:wood/encased_axle/sequoia',
    'tfc:wood/encased_axle/spruce',
    'tfc:wood/encased_axle/sycamore',
    'tfc:wood/encased_axle/white_cedar',
    'tfc:wood/encased_axle/willow',

    // Clutches
    'tfc:wood/clutch/acacia',
    'tfc:wood/clutch/ash',
    'tfc:wood/clutch/aspen',
    'tfc:wood/clutch/birch',
    'tfc:wood/clutch/blackwood',
    'tfc:wood/clutch/chestnut',
    'tfc:wood/clutch/douglas_fir',
    'tfc:wood/clutch/hickory',
    'tfc:wood/clutch/kapok',
    'tfc:wood/clutch/mangrove',
    'tfc:wood/clutch/maple',
    'tfc:wood/clutch/oak',
    'tfc:wood/clutch/palm',
    'tfc:wood/clutch/pine',
    'tfc:wood/clutch/rosewood',
    'tfc:wood/clutch/sequoia',
    'tfc:wood/clutch/spruce',
    'tfc:wood/clutch/sycamore',
    'tfc:wood/clutch/white_cedar',
    'tfc:wood/clutch/willow',

    // Gear Boxes
    'tfc:wood/gear_box/acacia',
    'tfc:wood/gear_box/ash',
    'tfc:wood/gear_box/aspen',
    'tfc:wood/gear_box/birch',
    'tfc:wood/gear_box/blackwood',
    'tfc:wood/gear_box/chestnut',
    'tfc:wood/gear_box/douglas_fir',
    'tfc:wood/gear_box/hickory',
    'tfc:wood/gear_box/kapok',
    'tfc:wood/gear_box/mangrove',
    'tfc:wood/gear_box/maple',
    'tfc:wood/gear_box/oak',
    'tfc:wood/gear_box/palm',
    'tfc:wood/gear_box/pine',
    'tfc:wood/gear_box/rosewood',
    'tfc:wood/gear_box/sequoia',
    'tfc:wood/gear_box/spruce',
    'tfc:wood/gear_box/sycamore',
    'tfc:wood/gear_box/white_cedar',
    'tfc:wood/gear_box/willow',

    // Water Wheels  
    'tfc:wood/water_wheel/acacia', 
    'tfc:wood/water_wheel/ash', 
    'tfc:wood/water_wheel/aspen',
    'tfc:wood/water_wheel/birch', 
    'tfc:wood/water_wheel/blackwood', 
    'tfc:wood/water_wheel/chestnut', 
    'tfc:wood/water_wheel/douglas_fir', 
    'tfc:wood/water_wheel/hickory', 
    'tfc:wood/water_wheel/kapok', 
    'tfc:wood/water_wheel/mangrove', 
    'tfc:wood/water_wheel/maple', 
    'tfc:wood/water_wheel/oak', 
    'tfc:wood/water_wheel/palm', 
    'tfc:wood/water_wheel/pine', 
    'tfc:wood/water_wheel/rosewood', 
    'tfc:wood/water_wheel/sequoia', 
    'tfc:wood/water_wheel/spruce', 
    'tfc:wood/water_wheel/sycamore', 
    'tfc:wood/water_wheel/white_cedar', 
    'tfc:wood/water_wheel/willow',

    // Boat
    'tfc:wood/boat/acacia', 
    'tfc:wood/boat/ash', 
    'tfc:wood/boat/aspen',
    'tfc:wood/boat/birch', 
    'tfc:wood/boat/blackwood', 
    'tfc:wood/boat/chestnut', 
    'tfc:wood/boat/douglas_fir', 
    'tfc:wood/boat/hickory', 
    'tfc:wood/boat/kapok', 
    'tfc:wood/boat/mangrove', 
    'tfc:wood/boat/maple', 
    'tfc:wood/boat/oak', 
    'tfc:wood/boat/palm', 
    'tfc:wood/boat/pine', 
    'tfc:wood/boat/rosewood', 
    'tfc:wood/boat/sequoia', 
    'tfc:wood/boat/spruce', 
    'tfc:wood/boat/sycamore', 
    'tfc:wood/boat/white_cedar', 
    'tfc:wood/boat/willow',

    // Windmill Blades
    "tfc:windmill_blade",
    "tfc:orange_windmill_blade",
    "tfc:magenta_windmill_blade",
    "tfc:light_blue_windmill_blade",
    "tfc:yellow_windmill_blade",
    "tfc:lime_windmill_blade",
    "tfc:pink_windmill_blade",
    "tfc:gray_windmill_blade",
    "tfc:light_gray_windmill_blade",
    "tfc:cyan_windmill_blade",
    "tfc:purple_windmill_blade",
    "tfc:blue_windmill_blade",
    "tfc:brown_windmill_blade",
    "tfc:green_windmill_blade",
    "tfc:red_windmill_blade",
    "tfc:black_windmill_blade",

    // Каменные инстрменты
    'tfc:stone/knife_head/igneous_extrusive', 
    'tfc:stone/knife_head/igneous_intrusive', 
    'tfc:stone/knife_head/metamorphic', 
    'tfc:stone/knife_head/sedimentary', 
    
    'tfc:stone/knife/igneous_extrusive', 
    'tfc:stone/knife/igneous_intrusive', 
    'tfc:stone/knife/metamorphic',
    'tfc:stone/knife/sedimentary', 
    
    'tfc:stone/axe_head/igneous_extrusive', 
    'tfc:stone/axe_head/igneous_intrusive', 
    'tfc:stone/axe_head/metamorphic', 
    'tfc:stone/axe_head/sedimentary', 
    
    'tfc:stone/axe/igneous_extrusive', 
    'tfc:stone/axe/igneous_intrusive', 
    'tfc:stone/axe/metamorphic', 
    'tfc:stone/axe/sedimentary', 
    
    'tfc:stone/shovel_head/igneous_extrusive', 
    'tfc:stone/shovel_head/igneous_intrusive', 
    'tfc:stone/shovel_head/metamorphic', 
    'tfc:stone/shovel_head/sedimentary',
    
    'tfc:stone/shovel/igneous_extrusive', 
    'tfc:stone/shovel/igneous_intrusive', 
    'tfc:stone/shovel/metamorphic', 
    'tfc:stone/shovel/sedimentary', 
    
    'tfc:stone/hammer_head/igneous_extrusive', 
    'tfc:stone/hammer_head/igneous_intrusive', 
    'tfc:stone/hammer_head/metamorphic', 
    'tfc:stone/hammer_head/sedimentary', 
    
    'tfc:stone/hammer/igneous_extrusive', 
    'tfc:stone/hammer/igneous_intrusive', 
    'tfc:stone/hammer/metamorphic', 
    'tfc:stone/hammer/sedimentary', 
    
    'tfc:stone/hoe_head/igneous_extrusive', 
    'tfc:stone/hoe_head/igneous_intrusive', 
    'tfc:stone/hoe_head/metamorphic', 
    'tfc:stone/hoe_head/sedimentary', 
    
    'tfc:stone/hoe/igneous_extrusive', 
    'tfc:stone/hoe/igneous_intrusive', 
    'tfc:stone/hoe/metamorphic', 
    'tfc:stone/hoe/sedimentary', 

    // Other
    "tfc:trip_hammer",
    'tfc:steel_pipe',
    'tfc:steel_pump',
    'tfc:crankshaft',
    'tfc:hand_wheel_base', 
    'tfc:hand_wheel',
];

/**
 * Хранит список всех имен типов камней в TFC.
 */
global.TFC_STONE_TYPES = [
    'gabbro', 
    'shale', 
    'claystone', 
    'limestone', 
    'conglomerate', 
    'dolomite', 
    'chert', 
    'chalk', 
    'rhyolite', 
    'dacite', 
    'quartzite', 
    'slate', 
    'phyllite', 
    'schist', 
    'gneiss', 
    'marble',
    'basalt', // Есть в GT
    'diorite', // Есть в GT
    'andesite', // Есть в GT
    'granite' // Есть в GT
];

global.TFC_WOOD_TYPES = [
    "acacia", // Есть в Minecraft
    "ash",
    "aspen",
    "birch", // Есть в Minecraft
    "blackwood",
    "chestnut",
    "douglas_fir",
    "hickory",
    "kapok",
    "mangrove",
    "maple",
    "oak", // Есть в Minecraft
    "palm",
    "pine",
    "rosewood",
    "sequoia",
    "spruce",
    "sycamore",
    "white_cedar",
    "willow"
];

global.TFC_MUD_TYPES = [
    'silt',
    'loam',
    'sandy_loam',
    'silty_loam'
];

global.TFC_WOOD_ITEM_TYPES_TO_WOOD_DUST = {
    '#tfc:lumber': { name: 'lumber', output: ['1x gtceu:wood_dust'] },
    '#tfc:support_beams': { name: 'support_beams', output: ['2x gtceu:wood_dust'] },
    // '#minecraft:boats': { name: 'boats', output: ['5x gtceu:wood_dust'] },
    '#tfc:minecarts': { name: 'minecarts', output: ['5x gtceu:wood_dust', '1x gtceu:small_wrought_iron_dust'] },
    '#minecraft:signs': { name: 'signs', output: ['1x gtceu:wood_dust'] },
    '#minecraft:hanging_signs': { name: 'hanging_signs', output: ['1x gtceu:wood_dust'] },
    '#minecraft:logs': { name: 'logs', output: ['6x gtceu:wood_dust'] },
    '#minecraft:planks': { name: 'planks', output: ['1x gtceu:wood_dust'] },
    '#tfc:bookshelves': { name: 'bookshelves', output: ['6x gtceu:wood_dust'] },
    '#minecraft:wooden_doors': { name: 'wooden_doors', output: ['2x gtceu:wood_dust'] },
    '#minecraft:wooden_trapdoors': { name: 'wooden_trapdoors', output: ['2x gtceu:wood_dust'] },
    '#minecraft:wooden_fences': { name: 'wooden_fences', output: ['1x gtceu:wood_dust'] },
    '#forge:fence_gates/wooden': { name: 'wooden_fence_gates', output: ['1x gtceu:wood_dust'] },
    '#minecraft:wooden_buttons': { name: 'wooden_buttons', output: ['1x gtceu:wood_dust'] },
    '#minecraft:wooden_pressure_plates': { name: 'wooden_pressure_plates', output: ['1x gtceu:wood_dust'] },
    '#minecraft:wooden_slabs': { name: 'wooden_slabs', output: ['2x gtceu:wood_dust'] },
    '#minecraft:wooden_stairs': { name: 'wooden_stairs', output: ['2x gtceu:wood_dust'] },
    '#tfc:tool_racks': { name: 'tool_racks', output: ['1x gtceu:wood_dust'] },
    '#tfc:twigs': { name: 'twigs', output: ['1x gtceu:wood_dust'] },
    '#tfc:workbenches': { name: 'workbenches', output: ['1x gtceu:wood_dust'] },
    '#forge:chests/wooden': { name: 'wooden_chests', output: ['8x gtceu:wood_dust'] },
    // '#tfg:only_trapped_wooden_chests': { name: 'trapped_wooden_chests', output: ['8x gtceu:wood_dust', '1x gtceu:wrought_iron_small_dust'] },
    '#tfc:looms': { name: 'looms', output: ['2x gtceu:wood_dust'] },
    '#tfc:sluices': { name: 'sluices', output: ['4x gtceu:wood_dust'] },
    '#tfc:barrels': { name: 'barrels', output: ['2x gtceu:wood_dust'] },
    '#tfc:lecterns': { name: 'lecterns', output: ['4x gtceu:wood_dust'] },
    '#tfc:scribing_tables': { name: 'scribing_tables', output: ['1x gtceu:wood_dust'] },
    '#tfc:jar_shelves': { name: 'jar_shelves', output: ['1x gtceu:wood_dust'] },
    // '#tfc:axles': { name: 'axles', output: ['1x gtceu:wood_dust'] },
    // '#tfg:bladed_axles': { name: 'bladed_axles', output: ['1x gtceu:wood_dust'] },
    // '#tfc:clutches': { name: 'clutches', output: ['1x gtceu:wood_dust'] },
    // '#tfc:gear_boxes': { name: 'gear_boxes', output: ['3x gtceu:wood_dust'] },
    // '#tfc:water_wheels': { name: 'water_wheels', output: ['4x gtceu:wood_dust'] },
    '#tfcastikorcarts:cart_wheel': { name: '', output: ['1x gtceu:wood_dust'] },
    '#tfcastikorcarts:plow': { name: 'plow', output: ['2x gtceu:wood_dust'] },
    '#tfcastikorcarts:animal_cart': { name: 'animal_cart', output: ['2x gtceu:wood_dust'] },
    '#tfcastikorcarts:supply_cart': { name: 'supply_cart', output: ['2x gtceu:wood_dust'] },
    '#firmalife:food_shelves': { name: 'food_shelves', output: ['2x gtceu:wood_dust'] },
    '#firmalife:hangers': { name: 'hangers', output: ['1x gtceu:wood_dust'] },
};

/**
 * Хранит названия типов полублоков из камня в TFC.
 */
global.TFC_ROCK_SLAB_BLOCK_TYPES = [
    'raw',
    'smooth',
    'bricks',
    'cobble',
    'mossy_bricks',
    'mossy_cobble',
    'cracked_bricks'
];

/**
 * Хранит названия цветов песка в TFC.
 */
global.SAND_COLORS = [
    'brown',
    'white',
    'black',
    'red',
    'yellow',
    'green',
    'pink'
];

global.TFC_SIMPLE_MATERIALS = [
    "gypsum",
    "cinnabar",
    "cryolite",
    "saltpeter",
    "sylvite",
    "borax",
    "halite",
    "amethyst",
    "opal",
    "pyrite",
    "topaz",
    "bituminous_coal",
    "lignite",
    "graphite",
    "sulfur",
    "diamond",
    "emerald",
    "lapis_lazuli",
    "ruby",
    "sapphire"
]

global.TFC_ORE_TYPES = [
    "poor",
    "normal",
    "rich"
];

global.TFC_ORE_MATERIALS = [
    "bismuthinite",
    "cassiterite",
    "garnierite",
    "hematite",
    "limonite",
    "magnetite",
    "malachite",
    "native_copper",
    "native_gold",
    "native_silver",
    "sphalerite",
    "tetrahedrite"
];

global.TFC_FURNACE_MOLD_RECIPE_COMPONENTS = [
    { input: 'tfc:ceramic/unfired_ingot_mold', output: 'tfc:ceramic/ingot_mold', name: 'ingot_mold' },
    { input: 'tfc:ceramic/unfired_pickaxe_head_mold', output: 'tfc:ceramic/pickaxe_head_mold', name: 'pickaxe_head_mold' },
    { input: 'tfc:ceramic/unfired_propick_head_mold', output: 'tfc:ceramic/propick_head_mold', name: 'propick_head_mold' },
    { input: 'tfc:ceramic/unfired_axe_head_mold', output: 'tfc:ceramic/axe_head_mold', name: 'axe_head_mold' },
    { input: 'tfc:ceramic/unfired_shovel_head_mold', output: 'tfc:ceramic/shovel_head_mold', name: 'shovel_head_mold' },
    { input: 'tfc:ceramic/unfired_hoe_head_mold', output: 'tfc:ceramic/hoe_head_mold', name: 'hoe_head_mold' },
    { input: 'tfc:ceramic/unfired_chisel_head_mold', output: 'tfc:ceramic/chisel_head_mold', name: 'chisel_head_mold' },
    { input: 'tfc:ceramic/unfired_hammer_head_mold', output: 'tfc:ceramic/hammer_head_mold', name: 'hammer_head_mold' },
    { input: 'tfc:ceramic/unfired_saw_blade_mold', output: 'tfc:ceramic/saw_blade_mold', name: 'saw_blade_mold' },
    { input: 'tfc:ceramic/unfired_javelin_head_mold', output: 'tfc:ceramic/javelin_head_mold', name: 'javelin_head_mold' },
    { input: 'tfc:ceramic/unfired_sword_blade_mold', output: 'tfc:ceramic/sword_blade_mold', name: 'sword_blade_mold' },
    { input: 'tfc:ceramic/unfired_mace_head_mold', output: 'tfc:ceramic/mace_head_mold', name: 'mace_head_mold' },
    { input: 'tfc:ceramic/unfired_knife_blade_mold', output: 'tfc:ceramic/knife_blade_mold', name: 'knife_blade_mold' },
    { input: 'tfc:ceramic/unfired_scythe_blade_mold', output: 'tfc:ceramic/scythe_blade_mold', name: 'scythe_blade_mold' },
    { input: 'tfc:ceramic/unfired_bell_mold', output: 'tfc:ceramic/bell_mold', name: 'bell_mold' },
    { input: 'tfc:ceramic/unfired_fire_ingot_mold', output: 'tfc:ceramic/fire_ingot_mold', name: 'fire_ingot_mold' },
    { input: 'tfc:ceramic/unfired_brick', output: 'minecraft:brick', name: 'brick' },
    { input: 'tfc:ceramic/unfired_crucible', output: 'tfc:crucible', name: 'crucible' },
    { input: 'tfc:ceramic/unfired_flower_pot', output: 'minecraft:flower_pot', name: 'flower_pot' },
    { input: 'tfc:ceramic/unfired_pan', output: 'tfc:pan/empty', name: 'pan' },
    { input: 'tfc:ceramic/unfired_blowpipe', output: 'tfc:ceramic_blowpipe', name: 'ceramic_blowpipe' },
    { input: 'tfc:ceramic/unfired_bowl', output: 'tfc:ceramic/bowl', name: 'bowl' },
    { input: 'tfc:ceramic/unfired_fire_brick', output: 'tfc:ceramic/fire_brick', name: 'fire_brick' },
    { input: 'tfc:ceramic/unfired_jug', output: 'tfc:ceramic/jug', name: 'jug' },
    { input: 'tfc:ceramic/unfired_pot', output: 'tfc:ceramic/pot', name: 'pot' },
    { input: 'tfc:ceramic/unfired_spindle_head', output: 'tfc:ceramic/spindle_head', name: 'spindle_head' },
    { input: 'tfc:ceramic/unfired_vessel', output: 'tfc:ceramic/vessel', name: 'vessel' },
    { input: 'tfc:ceramic/unfired_large_vessel', output: 'tfc:ceramic/large_vessel', name: 'large_vessel' },
    { input: 'tfcchannelcasting:unfired_channel', output: 'tfcchannelcasting:channel', name: 'channel' },
    { input: 'tfcchannelcasting:unfired_mold_table', output: 'tfcchannelcasting:mold_table', name: 'mold_table' },
];

global.TFC_CLAY_TO_UNFIRED_MOLD_RECIPE_COMPONENTS = [
    { input: '5x minecraft:clay_ball', output: 'tfc:ceramic/unfired_ingot_mold', name: 'ingot_mold' },
    { input: '5x minecraft:clay_ball', output: 'tfc:ceramic/unfired_pickaxe_head_mold', name: 'pickaxe_head_mold' },
    { input: '5x minecraft:clay_ball', output: 'tfc:ceramic/unfired_propick_head_mold', name: 'propick_head_mold' },
    { input: '5x minecraft:clay_ball', output: 'tfc:ceramic/unfired_axe_head_mold', name: 'axe_head_mold' },
    { input: '5x minecraft:clay_ball', output: 'tfc:ceramic/unfired_shovel_head_mold', name: 'shovel_head_mold' },
    { input: '5x minecraft:clay_ball', output: 'tfc:ceramic/unfired_hoe_head_mold', name: 'hoe_head_mold' },
    { input: '5x minecraft:clay_ball', output: 'tfc:ceramic/unfired_chisel_head_mold', name: 'chisel_head_mold' },
    { input: '5x minecraft:clay_ball', output: 'tfc:ceramic/unfired_hammer_head_mold', name: 'hammer_head_mold' },
    { input: '5x minecraft:clay_ball', output: 'tfc:ceramic/unfired_saw_blade_mold', name: 'saw_blade_mold' },
    { input: '5x minecraft:clay_ball', output: 'tfc:ceramic/unfired_javelin_head_mold', name: 'javelin_head_mold' },
    { input: '5x minecraft:clay_ball', output: 'tfc:ceramic/unfired_sword_blade_mold', name: 'sword_blade_mold' },
    { input: '5x minecraft:clay_ball', output: 'tfc:ceramic/unfired_mace_head_mold', name: 'mace_head_mold' },
    { input: '5x minecraft:clay_ball', output: 'tfc:ceramic/unfired_knife_blade_mold', name: 'knife_blade_mold' },
    { input: '5x minecraft:clay_ball', output: 'tfc:ceramic/unfired_scythe_blade_mold', name: 'scythe_blade_mold' },
    { input: '5x minecraft:clay_ball', output: 'tfc:ceramic/unfired_bell_mold', name: 'bell_mold' },
    { input: '5x minecraft:clay_ball', output: 'tfc:ceramic/unfired_brick', name: 'brick' },
    { input: '5x minecraft:clay_ball', output: 'tfc:ceramic/unfired_flower_pot', name: 'flower_pot' },
    { input: '5x minecraft:clay_ball', output: 'tfc:ceramic/unfired_pan', name: 'pan' },
    { input: '5x minecraft:clay_ball', output: 'tfc:ceramic/unfired_blowpipe', name: 'ceramic_blowpipe' },
    { input: '5x minecraft:clay_ball', output: 'tfc:ceramic/unfired_bowl', name: 'bowl' },
    { input: '5x minecraft:clay_ball', output: 'tfc:ceramic/unfired_jug', name: 'jug' },
    { input: '5x minecraft:clay_ball', output: 'tfc:ceramic/unfired_pot', name: 'pot' },
    { input: '5x minecraft:clay_ball', output: 'tfc:ceramic/unfired_spindle_head', name: 'spindle_head' },
    { input: '5x minecraft:clay_ball', output: 'tfc:ceramic/unfired_vessel', name: 'vessel' },
    { input: '5x minecraft:clay_ball', output: 'tfc:ceramic/unfired_large_vessel', name: 'large_vessel' },
    { input: '5x tfc:fire_clay', output: 'tfc:ceramic/unfired_fire_ingot_mold', name: 'fire_ingot_mold' },
    { input: '5x tfc:fire_clay', output: '3x tfc:ceramic/unfired_fire_brick', name: 'fire_brick' },
    { input: '5x tfc:fire_clay', output: 'tfc:ceramic/unfired_crucible', name: 'crucible' },
    { input: '5x tfc:fire_clay', output: 'tfcchannelcasting:unfired_channel', name: 'channel' },
    { input: '5x tfc:fire_clay', output: 'tfcchannelcasting:unfired_mold_table', name: 'mold_table' },
];

global.TFC_BATCH_TO_BOTTLE_ASSEMBLING_RECIPE_COMPONENTS = [
    { input: 'tfc:silica_glass_batch', output: 'tfc:silica_glass_bottle', name: 'silica_glass_bottle' },
    { input: 'tfc:hematitic_glass_batch', output: 'tfc:hematitic_glass_bottle', name: 'hematitic_glass_bottle' },
    { input: 'tfc:olivine_glass_batch', output: 'tfc:olivine_glass_bottle', name: 'olivine_glass_bottle' },
    { input: 'tfc:volcanic_glass_batch', output: 'tfc:volcanic_glass_bottle', name: 'volcanic_glass_bottle' },
];

global.TFC_FURNACE_MEAT_RECIPE_COMPONENTS = [
    { input: 'tfc:food/horse_meat', output: 'tfc:food/cooked_horse_meat', name: 'cooked_horse_meat' }, 
    { input: 'tfc:food/bear', output: 'tfc:food/cooked_bear', name: 'cooked_bear' }, 
    { input: 'tfc:food/mutton', output: 'tfc:food/cooked_mutton', name: 'cooked_mutton' }, 
    { input: 'tfc:food/pheasant', output: 'tfc:food/cooked_pheasant', name: 'cooked_pheasant' }, 
    { input: 'tfc:food/quail', output: 'tfc:food/cooked_quail', name: 'cooked_quail' }, 
    { input: 'tfc:food/chicken', output: 'tfc:food/cooked_chicken', name: 'cooked_chicken' }, 
    { input: 'tfc:food/pork', output: 'tfc:food/cooked_pork', name: 'cooked_pork' }, 
    { input: 'tfc:food/beef', output: 'tfc:food/cooked_beef', name: 'cooked_beef' }, 
    { input: 'tfc:food/crappie', output: 'tfc:food/cooked_crappie', name: 'cooked_crappie' }, 
    { input: 'tfc:food/lake_trout', output: 'tfc:food/cooked_lake_trout', name: 'cooked_lake_trout' }, 
    { input: 'tfc:food/largemouth_bass', output: 'tfc:food/cooked_largemouth_bass', name: 'cooked_largemouth_bass' }, 
    { input: 'tfc:food/rainbow_trout', output: 'tfc:food/cooked_rainbow_trout', name: 'cooked_rainbow_trout' }, 
    { input: 'tfc:food/salmon', output: 'tfc:food/cooked_salmon', name: 'cooked_salmon' }, 
    { input: 'tfc:food/smallmouth_bass', output: 'tfc:food/cooked_smallmouth_bass', name: 'cooked_smallmouth_bass' }, 
    { input: 'tfc:food/camelidae', output: 'tfc:food/cooked_camelidae', name: 'cooked_camelidae' }, 
    { input: 'tfc:food/frog_legs', output: 'tfc:food/cooked_frog_legs', name: 'cooked_frog_legs' }, 
    { input: 'tfc:food/gran_feline', output: 'tfc:food/cooked_gran_feline', name: 'cooked_gran_feline' }, 
    { input: 'tfc:food/turtle', output: 'tfc:food/cooked_turtle', name: 'cooked_turtle' }, 
    { input: 'tfc:food/cod', output: 'tfc:food/cooked_cod', name: 'cooked_cod' }, 
    { input: 'tfc:food/tropical_fish', output: 'tfc:food/cooked_tropical_fish', name: 'cooked_tropical_fish' }, 
    { input: 'tfc:food/calamari', output: 'tfc:food/cooked_calamari', name: 'cooked_calamari' }, 
    { input: 'tfc:food/shellfish', output: 'tfc:food/cooked_shellfish', name: 'cooked_shellfish' }, 
    { input: 'tfc:food/bluegill', output: 'tfc:food/cooked_bluegill', name: 'cooked_bluegill' }, 
    { input: 'tfc:food/turkey', output: 'tfc:food/cooked_turkey', name: 'cooked_turkey' }, 
    { input: 'tfc:food/peafowl', output: 'tfc:food/cooked_peafowl', name: 'cooked_peafowl' }, 
    { input: 'tfc:food/grouse', output: 'tfc:food/cooked_grouse', name: 'cooked_grouse' }, 
    { input: 'tfc:food/venison', output: 'tfc:food/cooked_venison', name: 'cooked_venison' }, 
    { input: 'tfc:food/wolf', output: 'tfc:food/cooked_wolf', name: 'cooked_wolf' }, 
    { input: 'tfc:food/rabbit', output: 'tfc:food/cooked_rabbit', name: 'cooked_rabbit' }, 
    { input: 'tfc:food/hyena', output: 'tfc:food/cooked_hyena', name: 'cooked_hyena' }, 
    { input: 'tfc:food/duck', output: 'tfc:food/cooked_duck', name: 'cooked_duck' }, 
    { input: 'tfc:food/chevon', output: 'tfc:food/cooked_chevon', name: 'cooked_chevon' },
    { input: 'minecraft:egg', output: 'tfc:food/cooked_egg', name: 'cooked_egg' },
];

global.TFC_QUERN_POWDER_RECIPE_COMPONENTS = [
    { input: '#forge:dusts/coke', output: '4x tfc:powder/coke', name: 'coke_powder' },
    { input: '#forge:dusts/amethyst', output: '4x tfc:powder/amethyst', name: 'amethyst_powder' },
    { input: '#forge:dusts/diamond', output: '4x tfc:powder/diamond', name: 'diamond_powder' },
    { input: '#forge:dusts/emerald', output: '4x tfc:powder/emerald', name: 'emerald_powder' },
    { input: '#forge:dusts/lapis', output: '4x tfc:powder/lapis_lazuli', name: 'lapis_powder' },
    { input: '#forge:dusts/opal', output: '4x tfc:powder/opal', name: 'opal_powder' },
    { input: '#forge:dusts/pyrite', output: '4x tfc:powder/pyrite', name: 'pyrite_powder' },
    { input: '#forge:dusts/ruby', output: '4x tfc:powder/ruby', name: 'ruby_powder' },
    { input: '#forge:dusts/sapphire', output: '4x tfc:powder/sapphire', name: 'sapphire_powder' },
    { input: '#forge:dusts/topaz', output: '4x tfc:powder/topaz', name: 'topaz_powder' },
    { input: '#forge:dusts/gold', output: '4x tfc:powder/native_gold', name: 'gold_powder' },
    { input: '#forge:dusts/silver', output: '4x tfc:powder/native_silver', name: 'silver_powder' },
    { input: '#forge:dusts/copper', output: '4x tfc:powder/native_copper', name: 'copper_powder' },
    { input: '#forge:dusts/cassiterite', output: '4x tfc:powder/cassiterite', name: 'cassiterite_powder' },
    { input: '#forge:dusts/bismuth', output: '4x tfc:powder/bismuthinite', name: 'bismuth_powder' },
    { input: '#forge:dusts/garnierite', output: '4x tfc:powder/garnierite', name: 'garnierite_powder' },
    { input: '#forge:dusts/nickel', output: '4x tfc:powder/garnierite', name: 'nickel_powder' },
    { input: '#forge:dusts/sphalerite', output: '4x tfc:powder/sphalerite', name: 'sphalerite_powder' },
    { input: '#forge:dusts/magnetite', output: '4x tfc:powder/magnetite', name: 'magnetite_powder' },
    { input: '#forge:dusts/tetrahedrite', output: '4x tfc:powder/tetrahedrite', name: 'tetrahedrite_powder' },
    { input: '#forge:dusts/malachite', output: '4x tfc:powder/malachite', name: 'malachite_powder' },
    { input: '#forge:dusts/yellow_limonite', output: '4x tfc:powder/limonite', name: 'limonite_powder' },
    { input: '#forge:dusts/hematite', output: '4x tfc:powder/hematite', name: 'hematite_powder' },
    { input: '#forge:dusts/cinnabar', output: '4x minecraft:redstone', name: 'cinnabar_powder' },
    { input: '#forge:dusts/sulfur', output: '4x tfc:powder/sulfur', name: 'sulfur_powder' },
    { input: '#forge:dusts/saltpeter', output: '4x tfc:powder/saltpeter', name: 'saltpeter_powder' },
    { input: '#forge:dusts/salt', output: '4x tfc:powder/salt', name: 'salt_powder' },
    { input: '#forge:dusts/graphite', output: '4x tfc:powder/graphite', name: 'graphite_powder' },
    { input: '#forge:dusts/borax', output: '4x tfc:powder/flux', name: 'flux_powder' },
    { input: '#forge:dusts/soda_ash', output: '4x tfc:powder/soda_ash', name: 'soda_ash' },
    { input: 'minecraft:charcoal', output: '2x tfc:powder/charcoal', name: 'charcoal' },
];

global.TFC_QUERN_GRAIN_RECIPE_COMPONENTS = [
    { input: 'tfc:food/barley', output: 'tfc:food/barley_grain', name: 'barley_grain' },
    { input: 'tfc:food/maize', output: 'tfc:food/maize_grain', name: 'maize_grain' },
    { input: 'tfc:food/oat', output: 'tfc:food/oat_grain', name: 'oat_grain' },
    { input: 'tfc:food/rye', output: 'tfc:food/rye_grain', name: 'rye_grain' },
    { input: 'tfc:food/rice', output: 'tfc:food/rice_grain', name: 'rice_grain' },
    { input: 'tfc:food/wheat', output: 'tfc:food/wheat_grain', name: 'wheat_grain' },
];

global.TFC_QUERN_FLOUR_RECIPE_COMPONENTS = [
    { input: 'tfc:food/barley_grain', output: '2x tfc:food/barley_flour', name: 'barley_flour' },
    { input: 'tfc:food/maize_grain', output: '2x tfc:food/maize_flour', name: 'maize_flour' },
    { input: 'tfc:food/oat_grain', output: '2x tfc:food/oat_flour', name: 'oat_flour' },
    { input: 'tfc:food/rye_grain', output: '2x tfc:food/rye_flour', name: 'rye_flour' },
    { input: 'tfc:food/rice_grain', output: '2x tfc:food/rice_flour', name: 'rice_flour' },
    { input: 'tfc:food/wheat_grain', output: '2x tfc:food/wheat_flour', name: 'wheat_flour' },
];

global.TFC_MIXER_FLATBREAD_DOUGH_RECIPE_COMPONENTS = [
    { input: 'tfc:food/barley_flour', output: '2x tfc:food/barley_dough', name: 'tfc_barley_dough' },
    { input: 'tfc:food/maize_flour', output: '2x tfc:food/maize_dough', name: 'tfc_maize_dough' },
    { input: 'tfc:food/oat_flour', output: '2x tfc:food/oat_dough', name: 'tfc_oat_dough' },
    { input: 'tfc:food/rye_flour', output: '2x tfc:food/rye_dough', name: 'tfc_rye_dough' },
    { input: 'tfc:food/rice_flour', output: '2x tfc:food/rice_dough', name: 'tfc_rice_dough' },
    { input: 'tfc:food/wheat_flour', output: '2x tfc:food/wheat_dough', name: 'tfc_wheat_dough' },
];

global.TFC_FURNACE_BREAD_RECIPE_COMPONENTS = [
    { input: 'firmalife:food/barley_dough', output: 'tfc:food/barley_bread', name: 'barley_bread' },
    { input: 'firmalife:food/maize_dough', output: 'tfc:food/maize_bread', name: 'maize_bread' },
    { input: 'firmalife:food/oat_dough', output: 'tfc:food/oat_bread', name: 'oat_bread' },
    { input: 'firmalife:food/rye_dough', output: 'tfc:food/rye_bread', name: 'rye_bread' },
    { input: 'firmalife:food/rice_dough', output: 'tfc:food/rice_bread', name: 'rice_bread' },
    { input: 'firmalife:food/wheat_dough', output: 'tfc:food/wheat_bread', name: 'wheat_bread' },
];

global.TFC_GREENHOUSE_FRUIT_RECIPE_COMPONENTS = [
    { input: 'tfc:plant/cherry_sapling', fluid_amount: 8000, output: '3x tfc:food/cherry', name: 'cherry' },
    { input: 'tfc:plant/green_apple_sapling', fluid_amount: 8000, output: '3x tfc:food/green_apple', name: 'green_apple' },
    { input: 'tfc:plant/lemon_sapling', fluid_amount: 8000, output: '3x tfc:food/lemon', name: 'lemon' },
    { input: 'tfc:plant/olive_sapling', fluid_amount: 8000, output: '3x tfc:food/olive', name: 'olive' },
    { input: 'tfc:plant/orange_sapling', fluid_amount: 8000, output: '3x tfc:food/orange', name: 'orange' },
    { input: 'tfc:plant/peach_sapling', fluid_amount: 8000, output: '3x tfc:food/peach', name: 'peach' },
    { input: 'tfc:plant/plum_sapling', fluid_amount: 8000, output: '3x tfc:food/plum', name: 'plum' },
    { input: 'tfc:plant/red_apple_sapling', fluid_amount: 8000, output: '3x tfc:food/red_apple', name: 'red_apple' },
    { input: 'tfc:plant/banana_sapling', fluid_amount:8000, output: '3x tfc:food/banana', name: 'banana' },
];

global.TFC_GREENHOUSE_VEGETABLE_RECIPE_COMPONENTS = [
    { input: 'tfc:seeds/barley', fluid_amount: 4000, output: '3x tfc:food/barley', name: 'barley' },
    { input: 'tfc:seeds/oat', fluid_amount: 4000, output: '3x tfc:food/oat', name: 'oat' },
    { input: 'tfc:seeds/rye', fluid_amount: 4000, output: '3x tfc:food/rye', name: 'rye' },
    { input: 'tfc:seeds/maize', fluid_amount: 4000, output: '3x tfc:food/maize', name: 'maize' },
    { input: 'tfc:seeds/wheat', fluid_amount: 4000, output: '3x tfc:food/wheat', name: 'wheat' },
    { input: 'tfc:seeds/rice', fluid_amount: 4000, output: '3x tfc:food/rice', name: 'rice' },
    { input: 'tfc:seeds/beet', fluid_amount: 4000, output: '3x tfc:food/beet', name: 'beet' },
    { input: 'tfc:seeds/cabbage', fluid_amount: 4000, output: '3x tfc:food/cabbage', name: 'cabbage' },
    { input: 'tfc:seeds/carrot', fluid_amount: 4000, output: '3x tfc:food/carrot', name: 'carrot' },
    { input: 'tfc:seeds/green_bean', fluid_amount: 4000, output: '3x tfc:food/green_bean', name: 'green_bean' },
    { input: 'tfc:seeds/garlic', fluid_amount: 4000, output: '3x tfc:food/garlic', name: 'garlic' },
    { input: 'tfc:seeds/potato', fluid_amount: 4000, output: '3x tfc:food/potato', name: 'potato' },
    { input: 'tfc:seeds/onion', fluid_amount: 4000, output: '3x tfc:food/onion', name: 'onion' },
    { input: 'tfc:seeds/soybean', fluid_amount: 4000, output: '3x tfc:food/soybean', name: 'soybean' },
    { input: 'tfc:seeds/squash', fluid_amount: 4000, output: '3x tfc:food/squash', name: 'squash' },
    { input: 'tfc:seeds/sugarcane', fluid_amount: 4000, output: '3x tfc:food/sugarcane', name: 'sugarcane' },
    { input: 'tfc:seeds/tomato', fluid_amount: 4000, output: '3x tfc:food/tomato', name: 'tomato' },
    { input: 'tfc:seeds/jute', fluid_amount: 4000, output: '3x tfc:jute', name: 'jute' },
    { input: 'tfc:seeds/papyrus', fluid_amount: 4000, output: '3x tfc:papyrus', name: 'papyrus' },
    { input: 'tfc:seeds/pumpkin', fluid_amount: 4000, output: '3x tfc:pumpkin', name: 'pumpkin' },
    { input: 'tfc:seeds/melon', fluid_amount: 4000, output: '3x tfc:melon', name: 'melon' },
    { input: 'tfc:seeds/red_bell_pepper', fluid_amount: 4000, output: '3x tfc:food/red_bell_pepper', name: 'red_bell_pepper' },
    { input: 'tfc:seeds/yellow_bell_pepper', fluid_amount: 4000, output: '3x tfc:food/yellow_bell_pepper', name: 'yellow_bell_pepper' },
];

global.TFC_GREENHOUSE_BERRY_RECIPE_COMPONENTS = [
    { input: 'tfc:plant/snowberry_bush', fluid_amount: 6000, output: '3x tfc:food/snowberry', name: 'snowberry' },
    { input: 'tfc:plant/bunchberry_bush', fluid_amount: 6000, output: '3x tfc:food/bunchberry', name: 'bunchberry' },
    { input: 'tfc:plant/gooseberry_bush', fluid_amount: 6000, output: '3x tfc:food/gooseberry', name: 'gooseberry' },
    { input: 'tfc:plant/cloudberry_bush', fluid_amount: 6000, output: '3x tfc:food/cloudberry', name: 'cloudberry' },
    { input: 'tfc:plant/strawberry_bush', fluid_amount: 6000, output: '3x tfc:food/strawberry', name: 'strawberry' },
    { input: 'tfc:plant/wintergreen_berry_bush', fluid_amount: 6000, output: '3x tfc:food/wintergreen_berry', name: 'wintergreen_berry' },
    { input: 'tfc:plant/blackberry_bush', fluid_amount: 6000, output: '3x tfc:food/blackberry', name: 'blackberry' },
    { input: 'tfc:plant/raspberry_bush', fluid_amount: 6000, output: '3x tfc:food/raspberry', name: 'raspberry' },
    { input: 'tfc:plant/blueberry_bush', fluid_amount: 6000, output: '3x tfc:food/blueberry', name: 'blueberry' },
    { input: 'tfc:plant/elderberry_bush', fluid_amount: 6000, output: '3x tfc:food/elderberry', name: 'elderberry' },
    { input: 'tfc:plant/cranberry_bush', fluid_amount: 6000, output: '3x tfc:food/cranberry', name: 'cranberry' },
];

global.calcAmountOfMetal = (defaultAmount, percents) => {
    const value = defaultAmount / (100 / percents)
    return (value % 2 == 0) ? value : Math.round(value) - 1
}