// priority: 0
"use strict";

/**
 * Список хранит предметы, 
 * у которых должны быть удалены тэги и они должны быть скрыты в REI.
 */
global.CREATE_DISABLED_ITEMS = [
    // Ores
    'create:zinc_ore',
    'create:deepslate_zinc_ore', 

    // Raw Ores
    'create:raw_zinc', 

    // Raw Block Ores
    'create:raw_zinc_block', 
    
    // Sheets
    'create:iron_sheet', 

    // Flour
    'create:wheat_flour',
    'create:wheat_flour',

    // Vergilium Blocks
    'create:veridium', 
    'create:cut_veridium', 
    'create:cut_veridium_stairs', 
    'create:cut_veridium_slab', 
    'create:cut_veridium_wall', 
    'create:polished_cut_veridium', 
    'create:polished_cut_veridium_stairs', 
    'create:polished_cut_veridium_slab', 
    'create:polished_cut_veridium_wall', 
    'create:cut_veridium_bricks', 
    'create:cut_veridium_brick_stairs', 
    'create:cut_veridium_brick_slab', 
    'create:cut_veridium_brick_wall', 
    'create:small_veridium_bricks', 
    'create:small_veridium_brick_stairs', 
    'create:small_veridium_brick_slab', 
    'create:small_veridium_brick_wall', 
    'create:layered_veridium', 
    'create:veridium_pillar',

    // Scoria
    'create:scoria', 
    'create:cut_scoria', 
    'create:cut_scoria_stairs', 
    'create:cut_scoria_slab', 
    'create:cut_scoria_wall', 
    'create:polished_cut_scoria', 
    'create:polished_cut_scoria_stairs', 
    'create:polished_cut_scoria_slab', 
    'create:polished_cut_scoria_wall', 
    'create:cut_scoria_bricks', 
    'create:cut_scoria_brick_stairs', 
    'create:cut_scoria_brick_slab', 
    'create:cut_scoria_brick_wall', 
    'create:small_scoria_bricks', 
    'create:small_scoria_brick_stairs', 
    'create:small_scoria_brick_slab', 
    'create:small_scoria_brick_wall', 
    'create:layered_scoria', 
    'create:scoria_pillar',

    // Ochrium
    'create:ochrum', 
    'create:cut_ochrum', 
    'create:cut_ochrum_stairs', 
    'create:cut_ochrum_slab', 
    'create:cut_ochrum_wall', 
    'create:polished_cut_ochrum', 
    'create:polished_cut_ochrum_stairs', 
    'create:polished_cut_ochrum_slab', 
    'create:polished_cut_ochrum_wall', 
    'create:cut_ochrum_bricks', 
    'create:cut_ochrum_brick_stairs', 
    'create:cut_ochrum_brick_slab', 
    'create:cut_ochrum_brick_wall', 
    'create:small_ochrum_bricks', 
    'create:small_ochrum_brick_stairs', 
    'create:small_ochrum_brick_slab', 
    'create:small_ochrum_brick_wall',
    'create:layered_ochrum', 
    'create:ochrum_pillar',

    // Cringite
    'create:crimsite', 
    'create:cut_crimsite', 
    'create:cut_crimsite_stairs', 
    'create:cut_crimsite_slab', 
    'create:cut_crimsite_wall', 
    'create:polished_cut_crimsite', 
    'create:polished_cut_crimsite_stairs', 
    'create:polished_cut_crimsite_slab', 
    'create:polished_cut_crimsite_wall', 
    'create:cut_crimsite_bricks', 
    'create:cut_crimsite_brick_stairs', 
    'create:cut_crimsite_brick_slab', 
    'create:cut_crimsite_brick_wall', 
    'create:small_crimsite_bricks', 
    'create:small_crimsite_brick_stairs', 
    'create:small_crimsite_brick_slab', 
    'create:small_crimsite_brick_wall', 
    'create:layered_crimsite', 
    'create:crimsite_pillar',

    // Tuff
    'create:cut_tuff', 
    'create:cut_tuff_stairs', 
    'create:cut_tuff_slab', 
    'create:cut_tuff_wall', 
    'create:polished_cut_tuff',
    'create:polished_cut_tuff_stairs', 
    'create:polished_cut_tuff_slab', 
    'create:polished_cut_tuff_wall',
    'create:cut_tuff_bricks', 
    'create:cut_tuff_brick_stairs', 
    'create:cut_tuff_brick_slab', 
    'create:cut_tuff_brick_wall', 
    'create:small_tuff_bricks', 
    'create:small_tuff_brick_stairs', 
    'create:small_tuff_brick_slab', 
    'create:small_tuff_brick_wall', 
    'create:layered_tuff', 
    'create:tuff_pillar',


    // Shit Glass
    'create:crimson_window', 
    'create:warped_window', 
    'create:oak_window', 
    'create:spruce_window', 
    'create:birch_window', 
    'create:jungle_window', 
    'create:acacia_window', 
    'create:oak_window_pane', 
    'create:spruce_window_pane', 
    'create:birch_window_pane', 
    'create:jungle_window_pane', 
    'create:acacia_window_pane', 
    'create:crimson_window_pane',
    'create:warped_window_pane', 

    // Blocks
    'create:andesite_alloy_block',  
    'create:experience_block',

    // Cardboard (create 6)
    'create:cardboard_chestplate',
    'create:cardboard_helmet',
    'create:cardboard_leggings',
    'create:cardboard_boots',
    'create:cardboard_sword',
    'create:pulp',

    // Other
    'create:honey_bucket', 
    'create:chocolate_bucket',
    'create:crushed_raw_quicksilver', 
    'create:crushed_raw_aluminum', 
    'create:crushed_raw_uranium', 
    'create:crushed_raw_nickel', 
    'create:creative_blaze_cake', 
    'create:blaze_cake', 
    'create:blaze_cake_base', 
    'create:sturdy_sheet', 
    'create:polished_rose_quartz', 
    'create:cinder_flour', 
    'create:dough', 
    'create:bar_of_chocolate', 
    'create:sweet_roll', 
    'create:chocolate_glazed_berries', 
    'create:honeyed_apple', 
    'create:builders_tea', 
    'create:andesite_alloy', 
    'create:chromatic_compound', 
    'create:shadow_steel', 
    'create:refined_radiance', 
    'create:crushed_raw_platinum', 
    'create:crushed_raw_osmium', 
    'create:crushed_raw_iron', 
    'create:experience_nugget',
    'create:tree_fertilizer', 
    'create:handheld_worldshaper', 
    'create:creative_crate', 
    'create:creative_fluid_tank',
    'create:unprocessed_obsidian_sheet',
    'create:creative_motor',
    'create:refined_radiance_casing', 
    'create:shadow_steel_casing', 
    'create:wooden_bracket', 
    'create:red_sand_paper',
    'create:empty_blaze_burner',
    'create:minecart_contraption',
    'create:furnace_minecart_contraption',
    'create:chest_minecart_contraption',
    'create:mechanical_pump',
    'create:peculiar_bell',
    'create:haunted_bell',
    'create:adjustable_chain_gearshift'
];
