// priority: 0

/**
 * Список хранит предметы, 
 * у которых должны быть удалены тэги и они должны быть скрыты в REI.
 */
global.CREATE_DISABLED_ITEMS = [
    // Ores
    'create:zinc_ore',
    'create:deepslate_zinc_ore', 

    // Raw Ores
    'create:raw_zinc', 

    // Raw Block Ores
    'create:raw_zinc_block', 
    
    // Nuggets
    'create:copper_nugget',
    'create:zinc_nugget', 
    'create:brass_nugget', 
    
    // Sheets
    'create:copper_sheet', 
    'create:brass_sheet', 
    'create:iron_sheet', 
    'create:golden_sheet', 
    
    // Ingot
    'create:zinc_ingot', 
    'create:brass_ingot',

    // Flour
    'create:wheat_flour',
    'create:wheat_flour',

    // Vergilium Blocks
    'create:veridium', 
    'create:cut_veridium', 
    'create:cut_veridium_stairs', 
    'create:cut_veridium_slab', 
    'create:cut_veridium_wall', 
    'create:polished_cut_veridium', 
    'create:polished_cut_veridium_stairs', 
    'create:polished_cut_veridium_slab', 
    'create:polished_cut_veridium_wall', 
    'create:cut_veridium_bricks', 
    'create:cut_veridium_brick_stairs', 
    'create:cut_veridium_brick_slab', 
    'create:cut_veridium_brick_wall', 
    'create:small_veridium_bricks', 
    'create:small_veridium_brick_stairs', 
    'create:small_veridium_brick_slab', 
    'create:small_veridium_brick_wall', 
    'create:layered_veridium', 
    'create:veridium_pillar',

    // Scorchia
    'create:scorchia', 
    'create:cut_scorchia', 
    'create:cut_scorchia_stairs', 
    'create:cut_scorchia_slab', 
    'create:cut_scorchia_wall', 
    'create:polished_cut_scorchia', 
    'create:polished_cut_scorchia_stairs', 
    'create:polished_cut_scorchia_slab', 
    'create:polished_cut_scorchia_wall', 
    'create:cut_scorchia_bricks', 
    'create:cut_scorchia_brick_stairs', 
    'create:cut_scorchia_brick_slab', 
    'create:cut_scorchia_brick_wall', 
    'create:small_scorchia_bricks', 
    'create:small_scorchia_brick_stairs', 
    'create:small_scorchia_brick_slab',
    'create:small_scorchia_brick_wall', 
    'create:layered_scorchia', 
    'create:scorchia_pillar',

    // Scoria
    'create:scoria', 
    'create:cut_scoria', 
    'create:cut_scoria_stairs', 
    'create:cut_scoria_slab', 
    'create:cut_scoria_wall', 
    'create:polished_cut_scoria', 
    'create:polished_cut_scoria_stairs', 
    'create:polished_cut_scoria_slab', 
    'create:polished_cut_scoria_wall', 
    'create:cut_scoria_bricks', 
    'create:cut_scoria_brick_stairs', 
    'create:cut_scoria_brick_slab', 
    'create:cut_scoria_brick_wall', 
    'create:small_scoria_bricks', 
    'create:small_scoria_brick_stairs', 
    'create:small_scoria_brick_slab', 
    'create:small_scoria_brick_wall', 
    'create:layered_scoria', 
    'create:scoria_pillar',

    // Ochrium
    'create:ochrum', 
    'create:cut_ochrum', 
    'create:cut_ochrum_stairs', 
    'create:cut_ochrum_slab', 
    'create:cut_ochrum_wall', 
    'create:polished_cut_ochrum', 
    'create:polished_cut_ochrum_stairs', 
    'create:polished_cut_ochrum_slab', 
    'create:polished_cut_ochrum_wall', 
    'create:cut_ochrum_bricks', 
    'create:cut_ochrum_brick_stairs', 
    'create:cut_ochrum_brick_slab', 
    'create:cut_ochrum_brick_wall', 
    'create:small_ochrum_bricks', 
    'create:small_ochrum_brick_stairs', 
    'create:small_ochrum_brick_slab', 
    'create:small_ochrum_brick_wall',
    'create:layered_ochrum', 
    'create:ochrum_pillar',

    // Limestone
    'create:limestone', 
    'create:cut_limestone', 
    'create:cut_limestone_stairs', 
    'create:cut_limestone_slab', 
    'create:cut_limestone_wall', 
    'create:polished_cut_limestone', 
    'create:polished_cut_limestone_stairs', 
    'create:polished_cut_limestone_slab', 
    'create:polished_cut_limestone_wall', 
    'create:cut_limestone_bricks', 
    'create:cut_limestone_brick_stairs', 
    'create:cut_limestone_brick_slab', 
    'create:cut_limestone_brick_wall', 
    'create:small_limestone_bricks', 
    'create:small_limestone_brick_stairs', 
    'create:small_limestone_brick_slab', 
    'create:small_limestone_brick_wall', 
    'create:layered_limestone', 
    'create:limestone_pillar',

    // Cringite
    'create:crimsite', 
    'create:cut_crimsite', 
    'create:cut_crimsite_stairs', 
    'create:cut_crimsite_slab', 
    'create:cut_crimsite_wall', 
    'create:polished_cut_crimsite', 
    'create:polished_cut_crimsite_stairs', 
    'create:polished_cut_crimsite_slab', 
    'create:polished_cut_crimsite_wall', 
    'create:cut_crimsite_bricks', 
    'create:cut_crimsite_brick_stairs', 
    'create:cut_crimsite_brick_slab', 
    'create:cut_crimsite_brick_wall', 
    'create:small_crimsite_bricks', 
    'create:small_crimsite_brick_stairs', 
    'create:small_crimsite_brick_slab', 
    'create:small_crimsite_brick_wall', 
    'create:layered_crimsite', 
    'create:crimsite_pillar',

    // Kingdom of Asura (Mushoku Tensei)
    'create:asurine', 
    'create:cut_asurine', 
    'create:cut_asurine_stairs', 
    'create:cut_asurine_slab', 
    'create:cut_asurine_wall', 
    'create:polished_cut_asurine',
    'create:polished_cut_asurine_stairs', 
    'create:polished_cut_asurine_slab', 
    'create:polished_cut_asurine_wall', 
    'create:cut_asurine_bricks', 
    'create:cut_asurine_brick_stairs', 
    'create:cut_asurine_brick_slab', 
    'create:cut_asurine_brick_wall', 
    'create:small_asurine_bricks', 
    'create:small_asurine_brick_stairs', 
    'create:small_asurine_brick_slab', 
    'create:small_asurine_brick_wall', 
    'create:layered_asurine', 
    'create:asurine_pillar',

    // Tuff
    'create:cut_tuff', 
    'create:cut_tuff_stairs', 
    'create:cut_tuff_slab', 
    'create:cut_tuff_wall', 
    'create:polished_cut_tuff',
    'create:polished_cut_tuff_stairs', 
    'create:polished_cut_tuff_slab', 
    'create:polished_cut_tuff_wall',
    'create:cut_tuff_bricks', 
    'create:cut_tuff_brick_stairs', 
    'create:cut_tuff_brick_slab', 
    'create:cut_tuff_brick_wall', 
    'create:small_tuff_bricks', 
    'create:small_tuff_brick_stairs', 
    'create:small_tuff_brick_slab', 
    'create:small_tuff_brick_wall', 
    'create:layered_tuff', 
    'create:tuff_pillar',

    // Deepslate
    'create:cut_deepslate', 
    'create:cut_deepslate_stairs', 
    'create:cut_deepslate_slab', 
    'create:cut_deepslate_wall', 
    'create:polished_cut_deepslate', 
    'create:polished_cut_deepslate_stairs', 
    'create:polished_cut_deepslate_slab', 
    'create:polished_cut_deepslate_wall', 
    'create:cut_deepslate_bricks', 
    'create:cut_deepslate_brick_stairs', 
    'create:cut_deepslate_brick_slab', 
    'create:cut_deepslate_brick_wall', 
    'create:small_deepslate_bricks', 
    'create:small_deepslate_brick_stairs', 
    'create:small_deepslate_brick_slab', 
    'create:small_deepslate_brick_wall', 
    'create:layered_deepslate', 
    'create:deepslate_pillar',

    // Dripstone
    'create:cut_dripstone', 
    'create:cut_dripstone_stairs', 
    'create:cut_dripstone_slab',
    'create:cut_dripstone_wall', 
    'create:polished_cut_dripstone', 
    'create:polished_cut_dripstone_stairs', 
    'create:polished_cut_dripstone_slab', 
    'create:polished_cut_dripstone_wall', 
    'create:cut_dripstone_bricks', 
    'create:cut_dripstone_brick_stairs', 
    'create:cut_dripstone_brick_slab', 
    'create:cut_dripstone_brick_wall', 
    'create:small_dripstone_bricks', 
    'create:small_dripstone_brick_stairs', 
    'create:small_dripstone_brick_slab', 
    'create:small_dripstone_brick_wall', 
    'create:layered_dripstone', 
    'create:dripstone_pillar',

    // Calcite
    'create:cut_calcite', 
    'create:cut_calcite_stairs', 
    'create:cut_calcite_slab', 
    'create:cut_calcite_wall', 
    'create:polished_cut_calcite', 
    'create:polished_cut_calcite_stairs', 
    'create:polished_cut_calcite_slab', 
    'create:polished_cut_calcite_wall', 
    'create:cut_calcite_bricks', 
    'create:cut_calcite_brick_stairs', 
    'create:cut_calcite_brick_slab', 
    'create:cut_calcite_brick_wall', 
    'create:small_calcite_bricks', 
    'create:small_calcite_brick_stairs', 
    'create:small_calcite_brick_slab', 
    'create:small_calcite_brick_wall', 
    'create:layered_calcite', 
    'create:calcite_pillar',

    // Andesite
    'create:cut_andesite', 
    'create:cut_andesite_stairs',
    'create:cut_andesite_slab', 
    'create:cut_andesite_wall', 
    'create:polished_cut_andesite', 
    'create:polished_cut_andesite_stairs', 
    'create:polished_cut_andesite_slab', 
    'create:polished_cut_andesite_wall', 
    'create:cut_andesite_bricks', 
    'create:cut_andesite_brick_stairs', 
    'create:cut_andesite_brick_slab', 
    'create:cut_andesite_brick_wall', 
    'create:small_andesite_bricks', 
    'create:small_andesite_brick_stairs', 
    'create:small_andesite_brick_slab', 
    'create:small_andesite_brick_wall', 
    'create:layered_andesite', 
    'create:andesite_pillar',

    // Diorite
    'create:cut_diorite', 
    'create:cut_diorite_stairs', 
    'create:cut_diorite_slab', 
    'create:cut_diorite_wall', 
    'create:polished_cut_diorite', 
    'create:polished_cut_diorite_stairs', 
    'create:polished_cut_diorite_slab', 
    'create:polished_cut_diorite_wall', 
    'create:cut_diorite_bricks', 
    'create:cut_diorite_brick_stairs', 
    'create:cut_diorite_brick_slab', 
    'create:cut_diorite_brick_wall', 
    'create:small_diorite_bricks', 
    'create:small_diorite_brick_stairs', 
    'create:small_diorite_brick_slab', 
    'create:small_diorite_brick_wall', 
    'create:layered_diorite', 
    'create:diorite_pillar',

    // Granite
    'create:cut_granite', 
    'create:cut_granite_stairs', 
    'create:cut_granite_slab', 
    'create:cut_granite_wall', 
    'create:polished_cut_granite', 
    'create:polished_cut_granite_stairs', 
    'create:polished_cut_granite_slab', 
    'create:polished_cut_granite_wall', 
    'create:cut_granite_bricks', 
    'create:cut_granite_brick_stairs', 
    'create:cut_granite_brick_slab', 
    'create:cut_granite_brick_wall', 
    'create:small_granite_bricks', 
    'create:small_granite_brick_stairs', 
    'create:small_granite_brick_slab', 
    'create:small_granite_brick_wall', 
    'create:layered_granite', 
    'create:granite_pillar',

    // Shit Glass
    'create:tiled_glass', 
    'create:framed_glass', 
    'create:horizontal_framed_glass', 
    'create:vertical_framed_glass', 
    'create:tiled_glass_pane', 
    'create:horizontal_framed_glass_pane', 
    'create:vertical_framed_glass_pane', 
    'create:oak_window', 
    'create:spruce_window', 
    'create:birch_window', 
    'create:jungle_window', 
    'create:acacia_window', 
    'create:dark_oak_window', 
    'create:mangrove_window', 
    'create:crimson_window', 
    'create:warped_window', 
    'create:ornate_iron_window', 
    'create:oak_window_pane', 
    'create:spruce_window_pane', 
    'create:birch_window_pane', 
    'create:jungle_window_pane', 
    'create:acacia_window_pane', 
    'create:dark_oak_window_pane', 
    'create:mangrove_window_pane', 
    'create:crimson_window_pane',
    'create:warped_window_pane', 
    'create:ornate_iron_window_pane',

    // Blocks
    'create:zinc_block', 
    'create:andesite_alloy_block', 
    'create:brass_block', 
    'create:industrial_iron_block', 
    'create:experience_block',
    'create:rose_quartz_block', 
    'create:rose_quartz_tiles', 
    'create:small_rose_quartz_tiles',

    // Shit Copper Blocks (Когда гребаный Create стал модом про декор)
    'create:oxidized_copper_tiles', 
    'create:copper_tile_slab', 
    'create:exposed_copper_tile_slab', 
    'create:weathered_copper_tile_slab', 
    'create:oxidized_copper_tile_slab', 
    'create:copper_tile_stairs', 
    'create:exposed_copper_tile_stairs', 
    'create:weathered_copper_tile_stairs', 
    'create:oxidized_copper_tile_stairs', 
    'create:copper_shingles', 
    'create:exposed_copper_shingles', 
    'create:weathered_copper_shingles', 
    'create:oxidized_copper_shingles', 
    'create:copper_shingle_slab', 
    'create:exposed_copper_shingle_slab', 
    'create:weathered_copper_shingle_slab', 
    'create:oxidized_copper_shingle_slab', 
    'create:copper_shingle_stairs', 
    'create:exposed_copper_shingle_stairs', 
    'create:weathered_copper_shingle_stairs', 
    'create:oxidized_copper_shingle_stairs', 
    'create:waxed_copper_shingles', 
    'create:waxed_exposed_copper_shingles', 
    'create:waxed_weathered_copper_shingles', 
    'create:waxed_oxidized_copper_shingles', 
    'create:waxed_copper_shingle_slab', 
    'create:waxed_exposed_copper_shingle_slab', 
    'create:waxed_weathered_copper_shingle_slab', 
    'create:waxed_oxidized_copper_shingle_slab', 
    'create:waxed_copper_shingle_stairs', 
    'create:waxed_exposed_copper_shingle_stairs', 
    'create:waxed_weathered_copper_shingle_stairs', 
    'create:waxed_oxidized_copper_shingle_stairs', 
    'create:copper_tiles', 
    'create:exposed_copper_tiles', 
    'create:weathered_copper_tiles',
    'create:waxed_copper_tiles', 
    'create:waxed_exposed_copper_tiles', 
    'create:waxed_weathered_copper_tiles', 
    'create:waxed_oxidized_copper_tiles', 
    'create:waxed_copper_tile_slab', 
    'create:waxed_exposed_copper_tile_slab', 
    'create:waxed_weathered_copper_tile_slab', 
    'create:waxed_oxidized_copper_tile_slab', 
    'create:waxed_copper_tile_stairs', 
    'create:waxed_exposed_copper_tile_stairs',
    'create:waxed_weathered_copper_tile_stairs', 
    'create:waxed_oxidized_copper_tile_stairs',

    // Other
    'create:honey_bucket', 
    'create:chocolate_bucket',
    'create:crushed_raw_lead', 
    'create:crushed_raw_quicksilver', 
    'create:crushed_raw_aluminum', 
    'create:crushed_raw_uranium', 
    'create:crushed_raw_nickel', 
    'create:rose_quartz_lamp', 
    'create:netherite_backtank', 
    'create:netherite_backtank_placeable', 
    'create:creative_blaze_cake', 
    'create:blaze_cake', 
    'create:blaze_cake_base', 
    'create:sturdy_sheet', 
    'create:powdered_obsidian', 
    'create:polished_rose_quartz', 
    'create:rose_quartz', 
    'create:cinder_flour', 
    'create:dough', 
    'create:bar_of_chocolate', 
    'create:sweet_roll', 
    'create:chocolate_glazed_berries', 
    'create:honeyed_apple', 
    'create:builders_tea', 
    'create:andesite_alloy', 
    'create:chromatic_compound', 
    'create:shadow_steel', 
    'create:refined_radiance', 
    'create:crushed_raw_tin', 
    'create:crushed_raw_silver', 
    'create:crushed_raw_platinum', 
    'create:crushed_raw_osmium', 
    'create:crushed_raw_zinc', 
    'create:crushed_raw_copper', 
    'create:crushed_raw_gold', 
    'create:crushed_raw_iron', 
    'create:experience_nugget',
    'create:andesite_bars', 
    'create:brass_bars', 
    'create:copper_bars', 
    'create:tree_fertilizer', 
    'create:netherite_diving_boots', 
    'create:netherite_diving_helmet', 
    'create:handheld_worldshaper', 
    'create:creative_crate', 
    'create:creative_fluid_tank',
    'create:unprocessed_obsidian_sheet',
    'create:creative_motor',
    'create:refined_radiance_casing', 
    'create:shadow_steel_casing', 
    'create:wooden_bracket', 
    'create:blaze_burner',
    'create:sand_paper',
    'create:red_sand_paper',
    'create:empty_blaze_burner',
    'create:minecart_contraption',
    'create:furnace_minecart_contraption',
    'create:chest_minecart_contraption',
    'create:framed_glass_pane'
];