// priority: 0

global.ALEKI_ROOFS_DISABLED_ITEMS = [
    "alekiroofs:mud_brick_roofing",
    "alekiroofs:sandstone_roofing",
    "alekiroofs:smooth_sandstone_roofing",
    "alekiroofs:red_sandstone_roofing",
    "alekiroofs:smooth_red_sandstone_roofing",
    "alekiroofs:oak_roofing",
    "alekiroofs:spruce_roofing",
    "alekiroofs:birch_roofing",
    "alekiroofs:jungle_roofing",
    "alekiroofs:acacia_roofing",
    "alekiroofs:dark_oak_roofing",
    "alekiroofs:mangrove_roofing",
    "alekiroofs:cherry_roofing",
    "alekiroofs:crimson_roofing",
    "alekiroofs:warped_roofing",
    "alekiroofs:cobbled_deepslate_roofing",
    "alekiroofs:polished_deepslate_roofing",
    "alekiroofs:deepslate_tile_roofing",
    "alekiroofs:deepslate_brick_roofing",
    "alekiroofs:andesite_roofing",
    "alekiroofs:polished_andesite_roofing",
    "alekiroofs:granite_roofing",
    "alekiroofs:polished_granite_roofing",
    "alekiroofs:diorite_roofing",
    "alekiroofs:polished_diorite_roofing",
    "alekiroofs:stone_roofing",
    "alekiroofs:cobblestone_roofing",
    "alekiroofs:mossy_cobblestone_roofing",
    "alekiroofs:stone_brick_roofing",
    "alekiroofs:mossy_stone_brick_roofing",
    "alekiroofs:purpur_roofing",
    "alekiroofs:end_stone_brick_roofing",
];