// priority: 0

global.MEGA_SELLS_DISABLED_ITEMS = [
    'megacells:mega_energy_cell',
    'megacells:sky_steel_block',
    'megacells:sky_steel_ingot',

    'megacells:decompression_module',
    'megacells:bulk_item_cell',
    'megacells:bulk_cell_component',
    'megacells:compression_card',

    'megacells:cell_component_1m',
    'megacells:cell_component_4m',
    'megacells:cell_component_16m',
    'megacells:cell_component_64m',
    'megacells:cell_component_256m',
    'megacells:item_storage_cell_1m',
    'megacells:item_storage_cell_4m',
    'megacells:item_storage_cell_16m',
    'megacells:item_storage_cell_64m',
    'megacells:item_storage_cell_256m',
    'megacells:fluid_storage_cell_1m',
    'megacells:fluid_storage_cell_4m',
    'megacells:fluid_storage_cell_16m',
    'megacells:fluid_storage_cell_64m',
    'megacells:fluid_storage_cell_256m',
    'megacells:portable_item_cell_1m',
    'megacells:portable_item_cell_4m',
    'megacells:portable_item_cell_16m',
    'megacells:portable_item_cell_64m',
    'megacells:portable_item_cell_256m',
    'megacells:portable_fluid_cell_1m',
    'megacells:portable_fluid_cell_4m',
    'megacells:portable_fluid_cell_16m',
    'megacells:portable_fluid_cell_64m',
    'megacells:portable_fluid_cell_256m',
    'megacells:1m_crafting_storage',
    'megacells:4m_crafting_storage',
    'megacells:16m_crafting_storage',
    'megacells:64m_crafting_storage',
    'megacells:256m_crafting_storage',
    'megacells:mega_crafting_unit',
    'megacells:mega_crafting_monitor',
    'megacells:mega_crafting_accelerator',
    'megacells:cell_dock',
]