name: Project Build
run-name: "📦 Project Build #${{ github.run_number }}"
on:
  push:
    branches:
      - dev
      - main
      - feature/workflows

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DEV_ENVIRONMENT: ${{ github.ref_name != 'main' }}

jobs:    
  info:
    name: 🖥️ Project Info
    uses: TerraFirmaGreg-Team/Actions-Workflows/.github/workflows/modpack/info.yml@main
    with:
      stable_branch: main
      dev_branch: dev
      enable_dev_mode: true
      changelog_path: CHANGELOG.md
      pakku_diff_enabled: true
  
  create-pr:
    name: 🤝 Create Release PR
    needs: [info]
    if: ${{ needs.info.outputs.make_pr == 'true' }}
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0

      - name: 📄 Changelog Parser
        id: changelog
        uses: coditory/changelog-parser@v1.0.2
        with:
          path: CHANGELOG.md
        continue-on-error: true

      - name: 🔍 Check existing PRs
        id: check_existing_pr
        uses: actions/github-script@v8.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          result-encoding: string
          script: |
            try {
              const { data: prs } = await github.rest.pulls.list({
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: 'open',
                head: `${context.repo.owner}:dev`,
                base: 'main'
              });

              core.setOutput('exists', prs.length > 0);
              console.log(`ℹ️ PR exists: ${prs.length > 0}`);
            } catch (error) {
              core.setFailed(`❌ PR check failed: ${error}`);
              core.setOutput('exists', true);
            }

      - name: 🔍 Create Pull Request if tag not found
        if: ${{ steps.check_existing_pr.outputs.exists == 'false' }}
        uses: devops-infra/action-pull-request@v0.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: dev
          target_branch: main
          milestone: ${{ steps.changelog.outputs.version }}
          ignore_users: "dependabot"
          draft: true
          title: 'Release: ${{ steps.changelog.outputs.version }}'
          body: |
            **This is an automated Pull Request from the dev branch.**
            📃 **Name**: ${{ needs.info.outputs.project_name }}
            📃 **Release**:  `${{ steps.changelog.outputs.version }}`
            📃 **Release Type**: `${{ needs.info.outputs.release_type }}`
            📃 **Loader**: `${{ needs.info.outputs.loader_type }}-${{ needs.info.outputs.loader_version }}`

            ${{ needs.info.outputs.changelog }}

  build-project:
    name: 📦 Build Project
    needs: [info]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: 🔄 Replace strings
        shell: bash
        run: |
          set +e

          VERSION=${{ needs.info.outputs.project_version }}
          LOADER_VERSION=${{ needs.info.outputs.loader_version }}
          LOADER_TYPE=${{ needs.info.outputs.loader_type }}
          MINECRAFT_VERSION=${{ needs.info.outputs.mc_version }}


          sed -i -e "s/DEV/${VERSION}/g" pakku.json
          sed -i -e "s/DEV/${VERSION}/g" config/mod-director/modpack.json
          sed -i -e "s/DEV/${VERSION}/g" config/fancymenu/customization/gui_main_menu.txt

          sed -i -e "s/DEV/${VERSION}/g" .pakku/multimc-overrides/instance.cfg
          sed -i -e "s/LOADER_VERSION/${LOADER_VERSION}/g" .pakku/multimc-overrides/mmc-pack.json
          sed -i -e "s/LOADER_TYPE/${LOADER_TYPE}/g" .pakku/multimc-overrides/mmc-pack.json
          sed -i -e "s/MINECRAFT_VERSION/${MINECRAFT_VERSION}/g" .pakku/multimc-overrides/mmc-pack.json

          sed -i -e "s/LOADER_VERSION/${LOADER_VERSION}/g" .pakku/server-overrides/forge-auto-install.txt
          sed -i -e "s/LOADER_TYPE/${LOADER_TYPE}/g" .pakku/server-overrides/forge-auto-install.txt
          sed -i -e "s/MINECRAFT_VERSION/${MINECRAFT_VERSION}/g" .pakku/server-overrides/forge-auto-install.txt

      - name: 📝 Cache pakku
        uses: actions/cache@v4.3.0
        id: cache
        with:
          path: build/.cache
          key: pakku-cache-${{ hashFiles('pakku-lock.json') }}
          restore-keys: pakku-cache-

      - name: 📦 Export modpack
        run: |
          curl https://github.com/juraj-hrivnak/pakku/releases/latest/download/pakku.jar -o pakku.jar -L -J
          java -jar pakku.jar fetch
          java -jar pakku.jar export

          mkdir -p .pakku/multimc-overrides/flame
          mkdir -p .pakku/multimc-overrides/mods

      - name: 📁 Preparing the artifact curseforge
        run: |
          cd ./build/curseforge/
          mv *.zip $(basename -s .zip *.zip)-curseforge.zip
          
      - name: 🚀 Upload artifact CurseForge
        uses: actions/upload-artifact@v4.6.2
        with:
          name: ${{ needs.info.outputs.project_full_name }}-curseforge
          path: ./build/curseforge/${{ needs.info.outputs.project_full_name }}-curseforge.zip
          if-no-files-found: error

      - name: 📁 Preparing the artifact modrinth
        run: |
          cd ./build/modrinth/
          mv *.mrpack $(basename -s .mrpack *.mrpack)-modrinth.mrpack

      - name: 🚀 Upload artifact modrinth
        uses: actions/upload-artifact@v4.6.2
        with:
          name: ${{ needs.info.outputs.project_full_name }}-modrinth
          path: ./build/modrinth/${{ needs.info.outputs.project_full_name }}-modrinth.mrpack
          if-no-files-found: warn

      - name: 📁 Preparing the artifact multimc
        run: |
          mkdir -p .pakku/multimc-overrides/flame
          mkdir -p .pakku/multimc-overrides/mods

          mv -vf .pakku/multimc-overrides ./build/multimc

          cp -vf ./build/.cache/curseforge/manifest.json ./build/multimc/flame/manifest.json

          cp -rf ./build/.cache/curseforge/overrides ./build/multimc/.minecraft
          cp -rf ./mods ./build/multimc/.minecraft/

          cd ./build/multimc/
          zip -r ${{ needs.info.outputs.project_full_name }}-multimc.zip icon.png mmc-pack.json instance.cfg .minecraft/ flame/
      
      - name: 🚀 Upload artifact multimc
        uses: actions/upload-artifact@v4.6.2
        with:
          name: ${{ needs.info.outputs.project_full_name }}-multimc
          path: ./build/multimc/${{ needs.info.outputs.project_full_name }}-multimc.zip
          if-no-files-found: error

      - name: 📁 Preparing the artifact server
        run: |
          cd ./build/serverpack/
          mv *.zip $(basename -s .zip *.zip)-serverpack.zip

      - name: 🚀 Upload artifact server
        uses: actions/upload-artifact@v4.6.2
        with:
          name: ${{ needs.info.outputs.project_full_name }}-serverpack
          path: ./build/serverpack/${{ needs.info.outputs.project_full_name }}-serverpack.zip
          if-no-files-found: error

  release-github:
    name: 🚀 Release to GitHub
    needs: [info, build-project]
    runs-on: ubuntu-latest
    if: ${{ needs.info.outputs.make_release == 'true' }}
    outputs:
      url: ${{ steps.release.outputs.url }}

    steps:
      - name: 📦 Checkout
        uses: actions/checkout@v5.0.0

      - name: 📦 Download artifact
        uses: actions/download-artifact@v5.0.0
        with:
          merge-multiple: true

      - name: 🔍 Check if artifact exist
        id: check_artifact
        shell: bash
        run: |
          if [ ! -f ${{ needs.info.outputs.project_full_name }}-curseforge.zip ]; then
            echo '::error::No value found for artifact `curseforge.zip`.' && exit 1
          fi
          # if [ ! -f ${{ needs.info.outputs.project_full_name }}-modrinth.mrpack ]; then
          #   echo '::error::No value found for artifact `modrinth.mrpack`.' && exit 1
          # fi
          if [ ! -f ${{ needs.info.outputs.project_full_name }}-serverpack.zip ]; then
            echo '::error::No value found for artifact `serverpack.zip`.' && exit 1
          fi
          if [ ! -f ${{ needs.info.outputs.project_full_name }}-multimc.zip ]; then
            echo '::error::No value found for artifact `multimc.zip`.' && exit 1
          fi
          echo "✔️ All artifacts found"

      - name: 📄 Format diff
        id: format_diff
        if: ${{ needs.info.outputs.diff != '' }}
        uses: roamingowl/template-output-with-eta@v2.0.0
        with:
          template: |
            ```markdown
            ${{ needs.info.outputs.diff }}
            ```

      - name: 🚀 Create release
        id: release
        uses: softprops/action-gh-release@v2.3.4
        with:
          name: ${{ needs.info.outputs.project_version }}
          tag_name: ${{ needs.info.outputs.project_version }}
          target_commitish: ${{ github.ref_name }}
          body: |
            ${{ needs.info.outputs.changelog }}
            ${{ steps.format_diff.outputs.text }}
          files: |
            ${{ needs.info.outputs.project_full_name }}-curseforge.zip
            ${{ needs.info.outputs.project_full_name }}-modrinth.mrpack
            ${{ needs.info.outputs.project_full_name }}-serverpack.zip
            ${{ needs.info.outputs.project_full_name }}-multimc.zip
          prerelease: ${{ needs.info.outputs.release_type != 'release' }}
          generate_release_notes: true
          token: ${{ secrets.GITHUB_TOKEN }}

  release-curseforge:
    name: 🚀 Release to CurseForge
    needs: [info, build-project, release-github]
    runs-on: ubuntu-latest
    if: ${{ needs.info.outputs.make_release == 'true' }}
    outputs:
      id: ${{ steps.release.outputs.id }}

    steps:
      - name: 🔒 Check if CURSEFORGE_TOKEN exist
        shell: bash
        run: |
          if [ "${{ secrets.CURSEFORGE_TOKEN }}" == '' ]; then
            echo '::error::No value found for secret key `CURSEFORGE_TOKEN`. See https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-a-repository' && exit 1
          fi  

      - name: 📦 Download artifact
        uses: actions/download-artifact@v5.0.0
        with:
          merge-multiple: true

      - name: 🔍 Check if artifact exist
        id: check_artifact
        shell: bash
        run: |
          if [ ! -f ${{ needs.info.outputs.project_full_name }}-curseforge.zip ]; then
            echo '::error::No value found for artifact `curseforge.zip`.' && exit 1
          fi
          if [ ! -f ${{ needs.info.outputs.project_full_name }}-serverpack.zip ]; then
            echo '::error::No value found for artifact `serverpack.zip`.' && exit 1
          fi
          echo "✔️ All artifacts found"

      - name: 🚀 Upload Curseforge
        id: release
        uses: Xikaro/upload-curseforge-modpack-action@1.1.1
        with:
          api-token: ${{ secrets.CURSEFORGE_TOKEN }}
          project-id: ${{ vars.CURSEFORGE_ID }}
          display-name: ${{ needs.info.outputs.project_full_name }}
          modpack-path: ${{ needs.info.outputs.project_full_name }}-curseforge.zip
          server-display-name: ${{ needs.info.outputs.project_full_name }}-serverpack
          modpack-server-path: ${{ needs.info.outputs.project_full_name }}-serverpack.zip
          changelog: |
            ${{ needs.info.outputs.changelog }}
            ${{ needs.info.outputs.diff }}
          changelog-format: markdown
          game-version: ${{ needs.info.outputs.mc_version }}
          release-type: ${{ needs.info.outputs.release_type }}

  release-modrinth:
      name: 🚀 Release to Modrinth
      needs: [info, build-project, release-github]
      runs-on: ubuntu-latest
      if: ${{ needs.info.outputs.make_release == 'true' }}
      outputs:
        id: ${{ steps.release.outputs.id }}

      steps:
        - name: 🔒 Check if MODRINTH_API_TOKEN exist
          shell: bash
          run: |
            if [ "${{ secrets.MODRINTH_TOKEN }}" == '' ]; then
              echo '::error::No value found for secret key `MODRINTH_TOKEN`. See https://docs.github.com/en/  actionssecurity-guides/  encrypted-secrets#creating-encrypted-secrets-for-a-repository' && exit 1
            fi  
    
        - name: 📦 Download artifact
          uses: actions/download-artifact@v5.0.0
          with:
            merge-multiple: true

        - name: 🔍 Check if artifact exist
          id: check_artifact
          shell: bash
          run: |
            if [ ! -f ${{ needs.info.outputs.project_full_name }}-modrinth.mrpack ]; then
              echo '::error::No value found for artifact `modrinth.mrpack`.' && exit 1
            fi
            echo "✔️ All artifacts found"
    
        # - name: 🚀 Upload Modrinth
        #   id: release
        #   uses: Xikaro/upload-curseforge-modpack-action@1.1.1
        #   with:
        #     api-token: ${{ secrets.MODRINTH_TOKEN }}
        #     project-id: ${{ vars.MODRINTH_ID }}
        #     modpack-path: ${{ needs.info.outputs.project_full_name }}-modrinth.mrpack
        #     changelog: ${{ needs.info.outputs.changelog }}
        #     changelog-format: markdown
        #     game-version: ${{ needs.info.outputs.mc_version }}
        #     display-name: ${{ needs.info.outputs.project_full_name }}

        #     release-type: ${{ needs.info.outputs.release_type }}

  discord-message:
    name: 📱 Discord Message
    needs: [info, release-github, release-curseforge]
    runs-on: ubuntu-latest
    steps:
      - name: ✂️ Truncate Changelog
        id: truncated
        uses: cisox/read-more-action@v1.0.2
        with:
          text: '${{ needs.info.outputs.changelog }}'
          max_chars: '1450'

      - name: 📨 Send Discord message
        uses: hugoalh/send-discord-webhook-ghaction@v7.0.5
        with:
          key: ${{ secrets.DISCORD_RELEASES }}
          username: "TerraFirmaGreg"
          avatar_url: "https://raw.githubusercontent.com/TerraFirmaGreg-Team/.github/main/branding/logo.png"
          content_links_no_embed: .+
          content: |
            **Release**: `${{ needs.info.outputs.project_version }}`
            **Release Type**: `${{ needs.info.outputs.release_type }}`
            **Game Version**: `${{ needs.info.outputs.mc_version }}`

            [CurseForge](https://www.curseforge.com/minecraft/modpacks/terrafirmagreg-modern/files/${{ needs.release-curseforge.outputs.id }}) • [GitHub](${{ needs.release-github.outputs.url }}) • [Issues](https://github.com/${{ github.repository }}/issues)
            ```markdown
            ${{ steps.truncated.outputs.text  }}
            - ...```
            ** [Read more...](${{ needs.release-github.outputs.url }}) **
